<?php
// auth-generated by FilterConfigHandler
// date: 01/10/2019 17:26:34
require_once('/Applications/MAMP/htdocs/18031/lianxi1/open/install/webapp/filter/LoginFilter.class.php');
require_once('/Applications/MAMP/htdocs/18031/lianxi1/open/install/webapp/filter/ThdFilter.class.php');
require_once('/Applications/MAMP/htdocs/18031/lianxi1/open/install/webapp/filter/SedFilter.class.php');
$filters = array();
$filter = new ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$filter = new LoginFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new ThdFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new SedFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>