<?php
 $adaik =  array (
  'qq_name' => '醉玲珑#无证之罪#权力的游戏第七季',
  'huandeng_1' => 'images/web/1.jpeg',
  'huandeng_url_1' => 'http://www.tuana.cn',
  'huandeng_2' => 'images/web/2.jpeg',
  'huandeng_url_2' => 'http://www.tuana.cn',
  'huandeng_3' => 'images/web/3.jpeg',
  'huandeng_url_3' => 'http://www.tuana.cn',
  'huandeng_4' => 'images/web/4.jpeg',
  'huandeng_url_4' => 'http://www.tuana.cn',
  'huandeng_5' => 'images/web/5.jpeg',
  'huandeng_url_5' => 'http://www.tuana.cn',
  'm_suiji_1' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/m/m1.jpg" border="0" width="100%" height="100%"  /></a>',
  'm_suiji_2' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/m/m2.jpg" border="0" width="100%" height="100%"  /></a>',
  'm_suiji_3' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/m/m3.jpg" border="0" width="100%" height="100%"  /></a>',
  'm_suiji_4' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/m/m4.jpg" border="0" width="100%" height="100%"  /></a>',
  'm_suiji_5' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/m/m5.jpg" border="0" width="100%" height="100%"  /></a>',
  'movie_ad' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/bottomads.gif" style="width:100%"></a>',
  'tv_ad' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/bottomads.gif" style="width:100%"></a>',
  'zongyi_ad' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/bottomads.gif" style="width:100%"></a>',
  'dongman_ad' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/bottomads.gif" style="width:100%"></a>',
  'play_up' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/play_up.gif" border="0" usemap="#Map" style="width:100%">',
  'jiazai_ad' => '<a href="http://www.tuana.cn" target="_blank"><img src="images/jiazai.png" width="100%"></a>',
  'play_ad' => '<img id="addid" src="images/1280jiazai.png" style="display: none;width:100%;border: 2px solid #ff6651">',
  'cebian1_ad' => '<a class="style02" href="http://www.tuana.cn" target="_blank"><strong>关注微信</strong><div class="article-wechats"> </br> <img src="images/qrcode.png"></div> </a>',
  'cebian2_ad' => '<a class="style02" href="http://www.tuana.cn" target="_blank"><strong>优惠券</strong><h2>爱艺VIP券券-优惠购物</h2><p>淘宝天猫内部优惠券,公开优惠券搜索，省钱购买！
领取内部优惠券，一样的东西，领券购买一般比自己直接买【省30%-60%】不等，券额多大就是省多少钱！</p></a>',
  'cebian3_ad' => '<h3>广告赞助</h3><div class="textwidget"><a href="http://www.tuana.cn" target="_blank"><img src="images/jianzhi.png" width="100%"></a></div>',
  'cebian4_ad' => '<a class="style01" href="http://www.tuana.cn" target="_blank"><strong>广而告知</strong><h2>更好的影院</h2><p>1.扁平化、简洁风、多功能配置，优秀的电脑、平板、手机支持，响应式布局，不同设备不同展示效果...2.视频全自动采集，不需人工干预，懒人必备！</p></a>',
  'foot' => '',
  'hometopnotice' => '',
  'hometopright' => '',
  'homelink' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>