<?php
// auth-generated by DefineConfigHandler
// date: 01/10/2019 17:27:55
define('MO_DEFAULT_MODULE', 'Default');
define('MO_DEFAULT_ACTION', 'Index');
define('MO_ERROR_404_MODULE', 'Default');
define('MO_ERROR_404_ACTION', 'Error404');
define('MO_LOGIN_MODULE', 'Default');
define('MO_LOGIN_ACTION', 'Login');
define('MO_MODULE_DISABLED_MODULE', 'Default');
define('MO_MODULE_DISABLED_ACTION', 'ModuleDisabled');
define('MO_SECURE_MODULE', 'Default');
define('MO_SECURE_ACTION', 'Secure');
define('MO_UNAVAILABLE_MODULE', 'Default');
define('MO_UNAVAILABLE_ACTION', 'Unavailable');
define('MO_AVAILABLE', true);
define('MO_ACTION_ACCESSOR', 'action');
define('MO_MODULE_ACCESSOR', 'module');
define('MO_CONTENT_TYPE', 'html');
define('MO_MOD_PUB', '/modpub');
define('MO_PATH_INFO_ARRAY', 'SERVER');
define('MO_PATH_INFO_KEY', 'PATH_INFO');
define('MO_URL_FORMAT', 'GET');
define('MO_USE_DATABASE', false);
define('MO_USE_SECURITY', true);
define('MO_USER_NAMESPACE', 'org/mojavi');
?>