<?php
// auth-generated by ModuleConfigHandler
// date: 01/11/2019 09:04:32
define('MOD_BGCOLOR_ENABLED', true);
define('MOD_BGCOLOR_TITLE', 'bgcolor Mojavi Module');
define('MOD_BGCOLOR_VERSION', 1.0);
define('MOD_BGCOLOR_NAME', 'bgcolor');
define('MOD_BGCOLOR_AUTHOR', 'fly');
define('MOD_BGCOLOR_HOMEPAGE', null);
define('MOD_BGCOLOR_UPDATE_URL', null);
define('MOD_BGCOLOR_DESCRIPTION', 'bgcolor Mojavi Module');
?>