<?php
// auth-generated by ModuleConfigHandler
// date: 01/10/2019 17:51:18
define('MOD_SIGN_ENABLED', true);
define('MOD_SIGN_TITLE', 'sign Mojavi Module');
define('MOD_SIGN_VERSION', 1.0);
define('MOD_SIGN_NAME', 'sign');
define('MOD_SIGN_AUTHOR', 'dhb');
define('MOD_SIGN_HOMEPAGE', null);
define('MOD_SIGN_UPDATE_URL', null);
define('MOD_SIGN_DESCRIPTION', 'sign Mojavi Module');
?>