<?php
// auth-generated by ModuleConfigHandler
// date: 01/11/2019 09:14:55
define('MOD_ARTICLE_ENABLED', true);
define('MOD_ARTICLE_TITLE', 'Article Mojavi Module');
define('MOD_ARTICLE_VERSION', 1.0);
define('MOD_ARTICLE_NAME', 'Article');
define('MOD_ARTICLE_AUTHOR', 'fly');
define('MOD_ARTICLE_HOMEPAGE', null);
define('MOD_ARTICLE_UPDATE_URL', null);
define('MOD_ARTICLE_DESCRIPTION', 'Article Mojavi Module');
?>