<?php
// auth-generated by ModuleConfigHandler
// date: 01/10/2019 17:28:10
define('MOD_INDEX_ENABLED', true);
define('MOD_INDEX_TITLE', 'index Mojavi Module');
define('MOD_INDEX_VERSION', 1.0);
define('MOD_INDEX_NAME', 'index');
define('MOD_INDEX_AUTHOR', 'fly');
define('MOD_INDEX_HOMEPAGE', null);
define('MOD_INDEX_UPDATE_URL', null);
define('MOD_INDEX_DESCRIPTION', 'Top Mojavi Module');
?>