<?php
// auth-generated by ModuleConfigHandler
// date: 01/11/2019 09:14:52
define('MOD_MEMBER_ENABLED', true);
define('MOD_MEMBER_TITLE', 'member Mojavi Module');
define('MOD_MEMBER_VERSION', 1.0);
define('MOD_MEMBER_NAME', 'member');
define('MOD_MEMBER_AUTHOR', 'fly');
define('MOD_MEMBER_HOMEPAGE', null);
define('MOD_MEMBER_UPDATE_URL', null);
define('MOD_MEMBER_DESCRIPTION', 'member Mojavi Module');
?>