<?php
// auth-generated by ModuleConfigHandler
// date: 01/11/2019 09:15:08
define('MOD_ROLE_ENABLED', true);
define('MOD_ROLE_TITLE', 'role Mojavi Module');
define('MOD_ROLE_VERSION', 1.0);
define('MOD_ROLE_NAME', 'role');
define('MOD_ROLE_AUTHOR', 'fly');
define('MOD_ROLE_HOMEPAGE', null);
define('MOD_ROLE_UPDATE_URL', null);
define('MOD_ROLE_DESCRIPTION', 'role Mojavi Module');
?>