<?php
// auth-generated by ModuleConfigHandler
// date: 01/11/2019 09:04:15
define('MOD_SOFTWARE_ENABLED', true);
define('MOD_SOFTWARE_TITLE', 'software Mojavi Module');
define('MOD_SOFTWARE_VERSION', 1.0);
define('MOD_SOFTWARE_NAME', 'software');
define('MOD_SOFTWARE_AUTHOR', 'dhb');
define('MOD_SOFTWARE_HOMEPAGE', null);
define('MOD_SOFTWARE_UPDATE_URL', null);
define('MOD_SOFTWARE_DESCRIPTION', 'software Mojavi Module');
?>