<?php
// auth-generated by ModuleConfigHandler
// date: 01/22/2019 11:13:05
define('MOD_SCORE_ENABLED', true);
define('MOD_SCORE_TITLE', 'score Mojavi Module');
define('MOD_SCORE_VERSION', 1.0);
define('MOD_SCORE_NAME', 'score');
define('MOD_SCORE_AUTHOR', 'dhb');
define('MOD_SCORE_HOMEPAGE', null);
define('MOD_SCORE_UPDATE_URL', null);
define('MOD_SCORE_DESCRIPTION', 'score Mojavi Module');
?>