<?php
// auth-generated by ModuleConfigHandler
// date: 01/10/2019 17:50:51
define('MOD_PRODUCT_ENABLED', true);
define('MOD_PRODUCT_TITLE', 'product Mojavi Module');
define('MOD_PRODUCT_VERSION', 1.0);
define('MOD_PRODUCT_NAME', 'product');
define('MOD_PRODUCT_AUTHOR', 'fly');
define('MOD_PRODUCT_HOMEPAGE', null);
define('MOD_PRODUCT_UPDATE_URL', null);
define('MOD_PRODUCT_DESCRIPTION', 'product Mojavi Module');
?>