<?php
// auth-generated by ModuleConfigHandler
// date: 01/10/2019 17:50:52
define('MOD_PRODUCT_CLASS_ENABLED', true);
define('MOD_PRODUCT_CLASS_TITLE', 'product_class Mojavi Module');
define('MOD_PRODUCT_CLASS_VERSION', 1.0);
define('MOD_PRODUCT_CLASS_NAME', 'product_class');
define('MOD_PRODUCT_CLASS_AUTHOR', 'fly');
define('MOD_PRODUCT_CLASS_HOMEPAGE', null);
define('MOD_PRODUCT_CLASS_UPDATE_URL', null);
define('MOD_PRODUCT_CLASS_DESCRIPTION', 'product_class Mojavi Module');
?>