<?php
// auth-generated by ModuleConfigHandler
// date: 01/11/2019 09:15:07
define('MOD_MENU_ENABLED', true);
define('MOD_MENU_TITLE', 'menu Mojavi Module');
define('MOD_MENU_VERSION', 1.0);
define('MOD_MENU_NAME', 'menu');
define('MOD_MENU_AUTHOR', 'dhb');
define('MOD_MENU_HOMEPAGE', null);
define('MOD_MENU_UPDATE_URL', null);
define('MOD_MENU_DESCRIPTION', 'menu Mojavi Module');
?>