<?php

use Illuminate\Database\Seeder;

class BaseClientRouteTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('base_client_route')->delete();
        
        \DB::table('base_client_route')->insert(array (
            0 => 
            array (
                'id' => 437,
                'client_id' => 21799,
                'route_name' => '风格化',
                'end_city' => NULL,
                'end_address' => '聚聚虹网咖',
                'end_longitude' => '114.2813550',
                'end_latitude' => '22.7616800',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            1 => 
            array (
                'id' => 438,
                'client_id' => 21799,
                'route_name' => '呗拜拜',
                'end_city' => NULL,
                'end_address' => '深圳市房地产权登记中心龙岗登记科',
                'end_longitude' => '114.2387020',
                'end_latitude' => '22.7278960',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            2 => 
            array (
                'id' => 439,
                'client_id' => 21799,
                'route_name' => '吧',
                'end_city' => NULL,
            'end_address' => '泥岗村1(公交站)',
                'end_longitude' => '114.1003420',
                'end_latitude' => '22.5655560',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            3 => 
            array (
                'id' => 440,
                'client_id' => 21799,
                'route_name' => '你才笨',
                'end_city' => NULL,
                'end_address' => '看看澄蓝',
                'end_longitude' => '114.0837980',
                'end_latitude' => '22.5580980',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            4 => 
            array (
                'id' => 441,
                'client_id' => 21799,
                'route_name' => '滚滚滚',
                'end_city' => NULL,
                'end_address' => '开屏花园',
                'end_longitude' => '113.8833450',
                'end_latitude' => '22.5702540',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            5 => 
            array (
                'id' => 444,
                'client_id' => 21798,
                'route_name' => '哦',
                'end_city' => NULL,
            'end_address' => '我家酒店(深圳坂田华为基地店)',
                'end_longitude' => '114.0673320',
                'end_latitude' => '22.6582910',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            6 => 
            array (
                'id' => 445,
                'client_id' => 21803,
                'route_name' => '海岸城购物中心',
                'end_city' => NULL,
                'end_address' => '海岸城购物中心',
                'end_longitude' => '113.9356430',
                'end_latitude' => '22.5169560',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            7 => 
            array (
                'id' => 446,
                'client_id' => 21803,
                'route_name' => '南山区',
                'end_city' => NULL,
                'end_address' => '南山区',
                'end_longitude' => '113.9304760',
                'end_latitude' => '22.5330130',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            8 => 
            array (
                'id' => 447,
                'client_id' => 21805,
                'route_name' => '深圳少年宫',
                'end_city' => NULL,
            'end_address' => '少年宫(地铁站)',
                'end_longitude' => '114.0601700',
                'end_latitude' => '22.5486270',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            9 => 
            array (
                'id' => 448,
                'client_id' => 21805,
                'route_name' => '深圳宝安',
                'end_city' => NULL,
            'end_address' => '广州南洋电缆(森达康直销)',
                'end_longitude' => '113.8905030',
                'end_latitude' => '22.5646660',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            10 => 
            array (
                'id' => 449,
                'client_id' => 21817,
                'route_name' => '南山',
                'end_city' => NULL,
                'end_address' => '欢乐海岸购物中心',
                'end_longitude' => '113.9893160',
                'end_latitude' => '22.5255390',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            11 => 
            array (
                'id' => 450,
                'client_id' => 21807,
                'route_name' => '深圳市后海地铁站',
                'end_city' => NULL,
            'end_address' => '白石洲(地铁站)',
                'end_longitude' => '113.9670480',
                'end_latitude' => '22.5396040',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            12 => 
            array (
                'id' => 455,
                'client_id' => 21823,
                'route_name' => '车公庙',
                'end_city' => NULL,
            'end_address' => '车公庙(地铁站)',
                'end_longitude' => '114.0258300',
                'end_latitude' => '22.5362470',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            13 => 
            array (
                'id' => 456,
                'client_id' => 21823,
                'route_name' => '广州南',
                'end_city' => NULL,
            'end_address' => '广州南站(公交站)',
                'end_longitude' => '113.2713220',
                'end_latitude' => '22.9909640',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            14 => 
            array (
                'id' => 459,
                'client_id' => 21800,
                'route_name' => '他',
                'end_city' => NULL,
                'end_address' => '广东省深圳市龙岗区鹅公岭社区',
                'end_longitude' => '114.1526700',
                'end_latitude' => '22.6769580',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            15 => 
            array (
                'id' => 460,
                'client_id' => 21823,
                'route_name' => '体育',
                'end_city' => NULL,
            'end_address' => '广东省深圳市福田区体育馆东(公交站)',
                'end_longitude' => '114.0945820',
                'end_latitude' => '22.5585840',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            16 => 
            array (
                'id' => 461,
                'client_id' => 21823,
            'route_name' => '٩(๑^o^๑)۶',
                'end_city' => NULL,
            'end_address' => '广东省深圳市福田区体育馆东(公交站)',
                'end_longitude' => '114.0945820',
                'end_latitude' => '22.5585840',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            17 => 
            array (
                'id' => 462,
                'client_id' => 21823,
                'route_name' => '车公庙',
                'end_city' => NULL,
            'end_address' => '广东省深圳市福田区车公庙(地铁站)',
                'end_longitude' => '114.0258300',
                'end_latitude' => '22.5362470',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            18 => 
            array (
                'id' => 466,
                'client_id' => 21810,
                'route_name' => 'test',
                'end_city' => NULL,
                'end_address' => '蔬菜批发部',
                'end_longitude' => '114.0983250',
                'end_latitude' => '22.7173170',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            19 => 
            array (
                'id' => 467,
                'client_id' => 21815,
                'route_name' => '请输入收货地址',
                'end_city' => NULL,
                'end_address' => '收货区',
                'end_longitude' => '114.0623140',
                'end_latitude' => '22.6607690',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            20 => 
            array (
                'id' => 495,
                'client_id' => 21818,
                'route_name' => '公司',
                'end_city' => NULL,
                'end_address' => '海岸城购物中心',
                'end_longitude' => '113.9356430',
                'end_latitude' => '22.5169560',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            21 => 
            array (
                'id' => 496,
                'client_id' => 21818,
                'route_name' => '地址',
                'end_city' => NULL,
            'end_address' => '车公庙(地铁站)',
                'end_longitude' => '114.0258300',
                'end_latitude' => '22.5362470',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            22 => 
            array (
                'id' => 500,
                'client_id' => 21800,
                'route_name' => '这烦人的地方反复个',
                'end_city' => NULL,
                'end_address' => '深圳茵特拉根房车酒店',
                'end_longitude' => '114.2871460',
                'end_latitude' => '22.6341880',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            23 => 
            array (
                'id' => 507,
                'client_id' => 21810,
                'route_name' => '我的',
                'end_city' => NULL,
            'end_address' => 'FANCL(茂业百货华强北店)',
                'end_longitude' => '114.0861510',
                'end_latitude' => '22.5458340',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            24 => 
            array (
                'id' => 512,
                'client_id' => 21810,
                'route_name' => '曾老师',
                'end_city' => NULL,
                'end_address' => 'GH浪腾公司',
                'end_longitude' => '114.1069640',
                'end_latitude' => '22.5551320',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            25 => 
            array (
                'id' => 522,
                'client_id' => 21810,
                'route_name' => '我',
                'end_city' => NULL,
                'end_address' => '永发油漆行',
                'end_longitude' => '114.1167600',
                'end_latitude' => '22.5979400',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            26 => 
            array (
                'id' => 523,
                'client_id' => 21810,
                'route_name' => '我们自己',
                'end_city' => NULL,
                'end_address' => '永发油漆行',
                'end_longitude' => '114.1167600',
                'end_latitude' => '22.5979400',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            27 => 
            array (
                'id' => 524,
                'client_id' => 21810,
                'route_name' => '我',
                'end_city' => NULL,
                'end_address' => '一道科技有限公司',
                'end_longitude' => '113.9779890',
                'end_latitude' => '22.6175480',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            28 => 
            array (
                'id' => 526,
                'client_id' => 21818,
                'route_name' => '小路',
                'end_city' => NULL,
                'end_address' => '中洲控股中心A座',
                'end_longitude' => '113.9333630',
                'end_latitude' => '22.5174410',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            29 => 
            array (
                'id' => 527,
                'client_id' => 21810,
                'route_name' => '我',
                'end_city' => NULL,
                'end_address' => '玖州国际货运有限公司',
                'end_longitude' => '114.0656200',
                'end_latitude' => '22.6317630',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            30 => 
            array (
                'id' => 529,
                'client_id' => 21823,
                'route_name' => '^_^',
                'end_city' => NULL,
            'end_address' => '车公庙(地铁站)',
                'end_longitude' => '114.0258330',
                'end_latitude' => '22.5362470',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            31 => 
            array (
                'id' => 531,
                'client_id' => 21823,
                'route_name' => '查尔顿',
                'end_city' => NULL,
                'end_address' => 'Cooki Face',
                'end_longitude' => '114.0831560',
                'end_latitude' => '22.5473290',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            32 => 
            array (
                'id' => 534,
                'client_id' => 21818,
                'route_name' => 'f',
                'end_city' => NULL,
                'end_address' => 'NULY MOLY',
                'end_longitude' => '114.2680970',
                'end_latitude' => '22.7225610',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            33 => 
            array (
                'id' => 535,
                'client_id' => 21823,
                'route_name' => '深圳',
                'end_city' => NULL,
            'end_address' => '车公庙(地铁站)',
                'end_longitude' => '114.0258300',
                'end_latitude' => '22.5362470',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            34 => 
            array (
                'id' => 536,
                'client_id' => 21823,
                'route_name' => '深圳',
                'end_city' => NULL,
            'end_address' => '车公庙(地铁站)',
                'end_longitude' => '114.0258330',
                'end_latitude' => '22.5362470',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            35 => 
            array (
                'id' => 537,
                'client_id' => 21823,
                'route_name' => '广州',
                'end_city' => NULL,
                'end_address' => '广州站',
                'end_longitude' => '113.2572910',
                'end_latitude' => '23.1494150',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            36 => 
            array (
                'id' => 538,
                'client_id' => 21823,
                'route_name' => '广州北',
                'end_city' => NULL,
                'end_address' => '广州东站',
                'end_longitude' => '113.3249000',
                'end_latitude' => '23.1505660',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            37 => 
            array (
                'id' => 539,
                'client_id' => 21825,
                'route_name' => '耀',
                'end_city' => NULL,
                'end_address' => '广东省深圳市福田区邀月楼茶艺馆',
                'end_longitude' => '114.0478920',
                'end_latitude' => '22.5670920',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            38 => 
            array (
                'id' => 540,
                'client_id' => 21804,
                'route_name' => ':o',
                'end_city' => NULL,
            'end_address' => '广东省深圳市南山区白石洲(地铁站)',
                'end_longitude' => '113.9670480',
                'end_latitude' => '22.5396040',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            39 => 
            array (
                'id' => 541,
                'client_id' => 21804,
                'route_name' => '6',
                'end_city' => NULL,
                'end_address' => '广东省深圳市福田区vivo',
                'end_longitude' => '114.0607800',
                'end_latitude' => '22.5677540',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            40 => 
            array (
                'id' => 542,
                'client_id' => 21804,
                'route_name' => '继续',
                'end_city' => '深圳市',
            'end_address' => '广东省深圳市福田区劳动就业大厦(八卦二路)',
                'end_longitude' => '114.0976460',
                'end_latitude' => '22.5583780',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            41 => 
            array (
                'id' => 543,
                'client_id' => 21804,
                'route_name' => '继续',
                'end_city' => '深圳市',
            'end_address' => '广东省深圳市福田区劳动就业大厦(八卦二路)',
                'end_longitude' => '114.0976460',
                'end_latitude' => '22.5583780',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            42 => 
            array (
                'id' => 544,
                'client_id' => 21804,
                'route_name' => '继续',
                'end_city' => '深圳市',
            'end_address' => '广东省深圳市福田区劳动就业大厦(八卦二路)',
                'end_longitude' => '114.0976460',
                'end_latitude' => '22.5583780',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            43 => 
            array (
                'id' => 545,
                'client_id' => 21804,
                'route_name' => '继续',
                'end_city' => '深圳市',
            'end_address' => '广东省深圳市福田区劳动就业大厦(八卦二路)',
                'end_longitude' => '114.0976460',
                'end_latitude' => '22.5583780',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            44 => 
            array (
                'id' => 554,
                'client_id' => 21800,
                'route_name' => 'ufhfj',
                'end_city' => '深圳市',
                'end_address' => '广东省深圳市福田区DJ娱乐无限',
                'end_longitude' => '114.0900830',
                'end_latitude' => '22.5459420',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            45 => 
            array (
                'id' => 555,
                'client_id' => 21800,
                'route_name' => 'jf',
                'end_city' => '深圳市',
                'end_address' => '广东省深圳市福田区Bclly vcagh',
                'end_longitude' => '114.0864540',
                'end_latitude' => '22.5454670',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            46 => 
            array (
                'id' => 559,
                'client_id' => 21800,
                'route_name' => '广州',
                'end_city' => '广州市',
            'end_address' => 'JimuCafe积木咖啡(中华广场店)',
                'end_longitude' => '113.2823700',
                'end_latitude' => '23.1258250',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            47 => 
            array (
                'id' => 560,
                'client_id' => 21800,
                'route_name' => '丶C',
                'end_city' => '深圳市',
                'end_address' => '广东省深圳市龙岗区鹅公岭社区',
                'end_longitude' => '114.1526700',
                'end_latitude' => '22.6769580',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            48 => 
            array (
                'id' => 565,
                'client_id' => 21800,
                'route_name' => '习',
                'end_city' => '深圳市',
            'end_address' => '广东省深圳市福田区OPPO(万商体验店)',
                'end_longitude' => '114.0868540',
                'end_latitude' => '22.5467430',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            49 => 
            array (
                'id' => 580,
                'client_id' => 21838,
                'route_name' => '中山',
                'end_city' => '中山市',
                'end_address' => '广东省中山市中山公园',
                'end_longitude' => '113.3701390',
                'end_latitude' => '22.5235320',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            50 => 
            array (
                'id' => 581,
                'client_id' => 21838,
                'route_name' => '中山',
                'end_city' => '中山市',
                'end_address' => '广东省中山市中山公园',
                'end_longitude' => '113.3701390',
                'end_latitude' => '22.5235320',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            51 => 
            array (
                'id' => 582,
                'client_id' => 21838,
                'route_name' => '中山@中山',
                'end_city' => '中山市',
                'end_address' => '广东省中山市中山公园',
                'end_longitude' => '113.3701390',
                'end_latitude' => '22.5235320',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            52 => 
            array (
                'id' => 583,
                'client_id' => 21838,
                'route_name' => '购物公园',
                'end_city' => '深圳市',
            'end_address' => '购物公园(地铁站)',
                'end_longitude' => '114.0545810',
                'end_latitude' => '22.5346550',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            53 => 
            array (
                'id' => 584,
                'client_id' => 21810,
                'route_name' => '责备g',
                'end_city' => '深圳市',
                'end_address' => '莲花山公园',
                'end_longitude' => '114.0585720',
                'end_latitude' => '22.5535230',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            54 => 
            array (
                'id' => 585,
                'client_id' => 21816,
                'route_name' => '須',
                'end_city' => '深圳市',
                'end_address' => '九号大院',
                'end_longitude' => '114.0224230',
                'end_latitude' => '22.5517880',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            55 => 
            array (
                'id' => 586,
                'client_id' => 21839,
                'route_name' => '园',
                'end_city' => '深圳市',
                'end_address' => '广东省龙岗区大康社区园山风景区卡丁车赛场',
                'end_longitude' => '114.2460270',
                'end_latitude' => '22.6397610',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            56 => 
            array (
                'id' => 587,
                'client_id' => 21838,
                'route_name' => '那就难上加难时间就是坎坎坷坷可是看到开口说拉克萨马纳看看书看看看就觉得姐姐今生今世',
                'end_city' => '深圳市',
                'end_address' => '深圳市昌宏瑞科技有限公司',
                'end_longitude' => '114.0875820',
                'end_latitude' => '22.5420170',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            57 => 
            array (
                'id' => 588,
                'client_id' => 21855,
                'route_name' => '中洲控股',
                'end_city' => '深圳市',
                'end_address' => '广东省龙岗区布吉中海怡翠山庄二十栋阳光丽人购物广场',
                'end_longitude' => '114.1095440',
                'end_latitude' => '22.6237490',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
            58 => 
            array (
                'id' => 589,
                'client_id' => 21894,
                'route_name' => '中洲控股',
                'end_city' => '深圳市',
                'end_address' => '广东省宝安区沙井崇光路与新沙路交叉口西南100米亿康广场',
                'end_longitude' => '113.8215320',
                'end_latitude' => '22.7280810',
                'create_time' => NULL,
                'modify_time' => NULL,
            ),
        ));
        
        
    }
}