<?php

use Illuminate\Database\Seeder;

class BaseClientInfoCensusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('base_client_info_census')->delete();
        
        \DB::table('base_client_info_census')->insert(array (
            0 => 
            array (
                'id' => 15732,
                'client_id' => 21798,
                'wait_assign' => 24,
                'hand_order' => 1,
                'cancel_order' => 16,
                'operations_cancel' => 8,
                'wait_pay_order' => -5,
                'finish_order' => 109,
                'convert_driver' => 9,
                'create_time' => '2017-03-29 13:53:44',
                'modify_time' => '2018-09-17 11:35:45',
            ),
            1 => 
            array (
                'id' => 15733,
                'client_id' => 21799,
                'wait_assign' => 1,
                'hand_order' => 4,
                'cancel_order' => 4,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 5,
                'convert_driver' => 0,
                'create_time' => '2017-03-29 14:06:48',
                'modify_time' => '2018-01-03 09:26:16',
            ),
            2 => 
            array (
                'id' => 15734,
                'client_id' => 21800,
                'wait_assign' => 128,
                'hand_order' => -1,
                'cancel_order' => 140,
                'operations_cancel' => 74,
                'wait_pay_order' => -27,
                'finish_order' => 322,
                'convert_driver' => 3,
                'create_time' => '2017-03-29 15:12:26',
                'modify_time' => '2018-09-26 11:41:42',
            ),
            3 => 
            array (
                'id' => 15735,
                'client_id' => 21801,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-03-29 16:53:34',
                'modify_time' => '2017-03-29 16:54:54',
            ),
            4 => 
            array (
                'id' => 15736,
                'client_id' => 21802,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 2,
                'convert_driver' => 0,
                'create_time' => '2017-05-06 12:01:02',
                'modify_time' => '2017-07-27 11:51:50',
            ),
            5 => 
            array (
                'id' => 15737,
                'client_id' => 21803,
                'wait_assign' => 9,
                'hand_order' => 0,
                'cancel_order' => 38,
                'operations_cancel' => 3,
                'wait_pay_order' => -5,
                'finish_order' => 28,
                'convert_driver' => 1,
                'create_time' => '2017-05-08 10:50:16',
                'modify_time' => '2017-05-15 16:47:41',
            ),
            6 => 
            array (
                'id' => 15738,
                'client_id' => 21804,
                'wait_assign' => 47,
                'hand_order' => -7,
                'cancel_order' => 54,
                'operations_cancel' => 10,
                'wait_pay_order' => -5,
                'finish_order' => 124,
                'convert_driver' => 6,
                'create_time' => '2017-05-08 16:45:23',
                'modify_time' => '2018-09-17 11:26:16',
            ),
            7 => 
            array (
                'id' => 15739,
                'client_id' => 21805,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 4,
                'operations_cancel' => 0,
                'wait_pay_order' => -1,
                'finish_order' => 4,
                'convert_driver' => 1,
                'create_time' => '2017-05-09 10:27:05',
                'modify_time' => '2017-05-10 12:11:52',
            ),
            8 => 
            array (
                'id' => 15740,
                'client_id' => 21806,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 3,
                'operations_cancel' => 6,
                'wait_pay_order' => -1,
                'finish_order' => 7,
                'convert_driver' => 1,
                'create_time' => '2017-05-09 10:46:33',
                'modify_time' => '2017-07-11 09:54:51',
            ),
            9 => 
            array (
                'id' => 15741,
                'client_id' => 21807,
                'wait_assign' => 13,
                'hand_order' => 1,
                'cancel_order' => 56,
                'operations_cancel' => 0,
                'wait_pay_order' => -2,
                'finish_order' => 66,
                'convert_driver' => 1,
                'create_time' => '2017-05-09 10:57:54',
                'modify_time' => '2018-09-15 11:15:22',
            ),
            10 => 
            array (
                'id' => 15742,
                'client_id' => 21808,
                'wait_assign' => 15,
                'hand_order' => 0,
                'cancel_order' => 5,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 36,
                'convert_driver' => 1,
                'create_time' => '2017-05-10 10:22:05',
                'modify_time' => '2018-09-07 15:15:16',
            ),
            11 => 
            array (
                'id' => 15743,
                'client_id' => 21809,
                'wait_assign' => 3,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 2,
                'finish_order' => 3,
                'convert_driver' => 0,
                'create_time' => '2017-05-10 10:26:00',
                'modify_time' => '2018-05-12 11:13:04',
            ),
            12 => 
            array (
                'id' => 15744,
                'client_id' => 21810,
                'wait_assign' => 92,
                'hand_order' => 0,
                'cancel_order' => 75,
                'operations_cancel' => 5,
                'wait_pay_order' => -7,
                'finish_order' => 117,
                'convert_driver' => 3,
                'create_time' => '2017-05-10 14:14:05',
                'modify_time' => '2018-01-23 15:59:27',
            ),
            13 => 
            array (
                'id' => 15745,
                'client_id' => 21811,
                'wait_assign' => 13,
                'hand_order' => 1,
                'cancel_order' => 14,
                'operations_cancel' => 1,
                'wait_pay_order' => -1,
                'finish_order' => 9,
                'convert_driver' => 0,
                'create_time' => '2017-05-10 15:51:58',
                'modify_time' => '2017-05-17 10:16:37',
            ),
            14 => 
            array (
                'id' => 15746,
                'client_id' => 21812,
                'wait_assign' => 73,
                'hand_order' => -2,
                'cancel_order' => 69,
                'operations_cancel' => 2,
                'wait_pay_order' => -35,
                'finish_order' => 109,
                'convert_driver' => 1,
                'create_time' => '2017-05-11 14:33:35',
                'modify_time' => '2018-05-15 12:16:13',
            ),
            15 => 
            array (
                'id' => 15747,
                'client_id' => 21813,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-05-12 10:23:18',
                'modify_time' => '2017-05-12 10:23:18',
            ),
            16 => 
            array (
                'id' => 15748,
                'client_id' => 21814,
                'wait_assign' => 3,
                'hand_order' => 0,
                'cancel_order' => 11,
                'operations_cancel' => 1,
                'wait_pay_order' => -1,
                'finish_order' => 22,
                'convert_driver' => 1,
                'create_time' => '2017-05-12 10:46:28',
                'modify_time' => '2018-04-19 14:45:39',
            ),
            17 => 
            array (
                'id' => 15749,
                'client_id' => 21815,
                'wait_assign' => 3,
                'hand_order' => 0,
                'cancel_order' => 34,
                'operations_cancel' => 1,
                'wait_pay_order' => -3,
                'finish_order' => 10,
                'convert_driver' => 0,
                'create_time' => '2017-05-13 15:39:10',
                'modify_time' => '2018-01-02 12:16:42',
            ),
            18 => 
            array (
                'id' => 15750,
                'client_id' => 21816,
                'wait_assign' => 53,
                'hand_order' => 1,
                'cancel_order' => 117,
                'operations_cancel' => 11,
                'wait_pay_order' => -18,
                'finish_order' => 213,
                'convert_driver' => 1,
                'create_time' => '2017-05-15 09:55:50',
                'modify_time' => '2018-09-17 11:45:32',
            ),
            19 => 
            array (
                'id' => 15751,
                'client_id' => 21817,
                'wait_assign' => 57,
                'hand_order' => 0,
                'cancel_order' => 181,
                'operations_cancel' => 18,
                'wait_pay_order' => -19,
                'finish_order' => 143,
                'convert_driver' => 4,
                'create_time' => '2017-05-15 11:44:32',
                'modify_time' => '2018-09-17 14:33:04',
            ),
            20 => 
            array (
                'id' => 15752,
                'client_id' => 21818,
                'wait_assign' => 36,
                'hand_order' => 0,
                'cancel_order' => 134,
                'operations_cancel' => 18,
                'wait_pay_order' => -13,
                'finish_order' => 170,
                'convert_driver' => 6,
                'create_time' => '2017-05-15 16:51:01',
                'modify_time' => '2017-07-27 12:23:04',
            ),
            21 => 
            array (
                'id' => 15753,
                'client_id' => 21819,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-05-16 16:49:52',
                'modify_time' => '2017-05-16 17:44:44',
            ),
            22 => 
            array (
                'id' => 15754,
                'client_id' => 21820,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 7,
                'operations_cancel' => 0,
                'wait_pay_order' => -1,
                'finish_order' => 9,
                'convert_driver' => 1,
                'create_time' => '2017-05-16 17:44:20',
                'modify_time' => '2018-05-10 20:32:16',
            ),
            23 => 
            array (
                'id' => 15755,
                'client_id' => 21821,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 2,
                'convert_driver' => 0,
                'create_time' => '2017-05-18 09:21:15',
                'modify_time' => '2018-01-06 11:19:39',
            ),
            24 => 
            array (
                'id' => 15756,
                'client_id' => 21822,
                'wait_assign' => 4,
                'hand_order' => 0,
                'cancel_order' => 10,
                'operations_cancel' => 0,
                'wait_pay_order' => -1,
                'finish_order' => 26,
                'convert_driver' => 4,
                'create_time' => '2017-05-18 14:17:46',
                'modify_time' => '2018-05-16 18:59:25',
            ),
            25 => 
            array (
                'id' => 15757,
                'client_id' => 21823,
                'wait_assign' => 16,
                'hand_order' => 0,
                'cancel_order' => 49,
                'operations_cancel' => 6,
                'wait_pay_order' => -8,
                'finish_order' => 63,
                'convert_driver' => 2,
                'create_time' => '2017-05-18 14:28:58',
                'modify_time' => '2017-07-27 10:20:45',
            ),
            26 => 
            array (
                'id' => 15758,
                'client_id' => 21824,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 2,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-06-08 11:01:24',
                'modify_time' => '2018-09-12 15:27:49',
            ),
            27 => 
            array (
                'id' => 15759,
                'client_id' => 21825,
                'wait_assign' => 1,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 1,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-06-14 10:13:23',
                'modify_time' => '2017-07-07 09:24:34',
            ),
            28 => 
            array (
                'id' => 15760,
                'client_id' => 21826,
                'wait_assign' => 2,
                'hand_order' => 0,
                'cancel_order' => 13,
                'operations_cancel' => 0,
                'wait_pay_order' => -2,
                'finish_order' => 11,
                'convert_driver' => 2,
                'create_time' => '2017-06-14 15:33:56',
                'modify_time' => '2018-05-25 15:09:24',
            ),
            29 => 
            array (
                'id' => 15761,
                'client_id' => 21827,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-06-20 16:55:16',
                'modify_time' => '2017-06-20 16:55:16',
            ),
            30 => 
            array (
                'id' => 15762,
                'client_id' => 21828,
                'wait_assign' => 3,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-06 15:34:21',
                'modify_time' => '2017-07-07 11:19:23',
            ),
            31 => 
            array (
                'id' => 15763,
                'client_id' => 21829,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-07 11:13:44',
                'modify_time' => '2017-07-11 09:33:40',
            ),
            32 => 
            array (
                'id' => 15764,
                'client_id' => 21830,
                'wait_assign' => 1,
                'hand_order' => 0,
                'cancel_order' => 2,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-10 15:53:48',
                'modify_time' => '2017-12-07 10:25:53',
            ),
            33 => 
            array (
                'id' => 15765,
                'client_id' => 21831,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-10 16:07:51',
                'modify_time' => '2017-07-10 16:07:51',
            ),
            34 => 
            array (
                'id' => 15766,
                'client_id' => 21832,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-11 15:49:28',
                'modify_time' => '2017-07-27 10:02:37',
            ),
            35 => 
            array (
                'id' => 15767,
                'client_id' => 21833,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 1,
                'convert_driver' => 0,
                'create_time' => '2017-07-11 18:00:08',
                'modify_time' => '2017-07-11 18:06:50',
            ),
            36 => 
            array (
                'id' => 15768,
                'client_id' => 21834,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-11 18:06:11',
                'modify_time' => '2017-07-11 18:06:11',
            ),
            37 => 
            array (
                'id' => 15769,
                'client_id' => 21835,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-12 16:04:52',
                'modify_time' => '2017-07-12 16:04:52',
            ),
            38 => 
            array (
                'id' => 15770,
                'client_id' => 21836,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-07-12 16:52:02',
                'modify_time' => '2017-07-12 16:52:02',
            ),
            39 => 
            array (
                'id' => 15771,
                'client_id' => 21837,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-08-02 11:42:01',
                'modify_time' => '2017-08-02 12:15:30',
            ),
            40 => 
            array (
                'id' => 15772,
                'client_id' => 21838,
                'wait_assign' => 17,
                'hand_order' => 0,
                'cancel_order' => 148,
                'operations_cancel' => 59,
                'wait_pay_order' => -29,
                'finish_order' => 251,
                'convert_driver' => 0,
                'create_time' => '2017-08-02 13:52:59',
                'modify_time' => '2018-04-02 17:19:41',
            ),
            41 => 
            array (
                'id' => 15773,
                'client_id' => 21839,
                'wait_assign' => 2,
                'hand_order' => 0,
                'cancel_order' => 27,
                'operations_cancel' => 7,
                'wait_pay_order' => -5,
                'finish_order' => 37,
                'convert_driver' => 1,
                'create_time' => '2017-08-10 09:30:31',
                'modify_time' => '2017-12-26 15:35:06',
            ),
            42 => 
            array (
                'id' => 15774,
                'client_id' => 21840,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-08-14 11:52:18',
                'modify_time' => '2017-08-14 11:52:18',
            ),
            43 => 
            array (
                'id' => 15775,
                'client_id' => 21841,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 1,
                'wait_pay_order' => 0,
                'finish_order' => 3,
                'convert_driver' => 0,
                'create_time' => '2017-08-22 14:55:42',
                'modify_time' => '2017-08-23 10:38:39',
            ),
            44 => 
            array (
                'id' => 15776,
                'client_id' => 21842,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 2,
                'wait_pay_order' => 0,
                'finish_order' => 7,
                'convert_driver' => 0,
                'create_time' => '2017-08-22 15:00:23',
                'modify_time' => '2018-09-26 14:23:26',
            ),
            45 => 
            array (
                'id' => 15777,
                'client_id' => 21843,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-10-23 12:04:05',
                'modify_time' => '2017-10-23 12:04:05',
            ),
            46 => 
            array (
                'id' => 15778,
                'client_id' => 21844,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 1,
                'wait_pay_order' => 0,
                'finish_order' => 3,
                'convert_driver' => 0,
                'create_time' => '2017-10-30 10:47:53',
                'modify_time' => '2017-10-30 11:54:11',
            ),
            47 => 
            array (
                'id' => 15779,
                'client_id' => 21845,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 1,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-10-30 10:58:50',
                'modify_time' => '2017-12-07 12:22:21',
            ),
            48 => 
            array (
                'id' => 15780,
                'client_id' => 21846,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 2,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-10-30 12:07:03',
                'modify_time' => '2017-12-06 09:52:23',
            ),
            49 => 
            array (
                'id' => 15781,
                'client_id' => 21847,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-10-30 17:31:56',
                'modify_time' => '2017-10-30 17:33:14',
            ),
            50 => 
            array (
                'id' => 15782,
                'client_id' => 21848,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 2,
                'operations_cancel' => 1,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 14:37:28',
                'modify_time' => '2017-11-06 14:41:50',
            ),
            51 => 
            array (
                'id' => 15783,
                'client_id' => 21849,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 14:52:31',
                'modify_time' => '2017-11-06 14:52:31',
            ),
            52 => 
            array (
                'id' => 15784,
                'client_id' => 21850,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 14:56:32',
                'modify_time' => '2017-11-06 14:57:14',
            ),
            53 => 
            array (
                'id' => 15785,
                'client_id' => 21851,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 14:58:30',
                'modify_time' => '2017-11-06 14:58:30',
            ),
            54 => 
            array (
                'id' => 15786,
                'client_id' => 21852,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 14:59:36',
                'modify_time' => '2017-11-06 14:59:36',
            ),
            55 => 
            array (
                'id' => 15787,
                'client_id' => 21853,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 15:00:27',
                'modify_time' => '2017-11-06 15:00:27',
            ),
            56 => 
            array (
                'id' => 15788,
                'client_id' => 21854,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 15:01:32',
                'modify_time' => '2017-11-06 15:01:32',
            ),
            57 => 
            array (
                'id' => 15789,
                'client_id' => 21855,
                'wait_assign' => 5,
                'hand_order' => 0,
                'cancel_order' => 29,
                'operations_cancel' => 1,
                'wait_pay_order' => -6,
                'finish_order' => 52,
                'convert_driver' => 1,
                'create_time' => '2017-11-06 15:02:48',
                'modify_time' => '2018-09-14 10:26:49',
            ),
            58 => 
            array (
                'id' => 15790,
                'client_id' => 21856,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 15:08:24',
                'modify_time' => '2017-11-06 15:08:24',
            ),
            59 => 
            array (
                'id' => 15791,
                'client_id' => 21857,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 15:09:33',
                'modify_time' => '2017-11-06 15:09:33',
            ),
            60 => 
            array (
                'id' => 15792,
                'client_id' => 21858,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 2,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 1,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 15:10:54',
                'modify_time' => '2017-12-05 16:00:35',
            ),
            61 => 
            array (
                'id' => 15793,
                'client_id' => 21859,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-06 15:31:03',
                'modify_time' => '2017-11-06 15:31:03',
            ),
            62 => 
            array (
                'id' => 15794,
                'client_id' => 21860,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-07 13:41:45',
                'modify_time' => '2017-11-07 13:41:45',
            ),
            63 => 
            array (
                'id' => 15795,
                'client_id' => 21861,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-11-07 13:53:34',
                'modify_time' => '2017-11-07 13:53:34',
            ),
            64 => 
            array (
                'id' => 15796,
                'client_id' => 21862,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-01 15:30:59',
                'modify_time' => '2017-12-01 15:30:59',
            ),
            65 => 
            array (
                'id' => 15797,
                'client_id' => 21863,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-01 17:24:28',
                'modify_time' => '2017-12-01 17:24:28',
            ),
            66 => 
            array (
                'id' => 15798,
                'client_id' => 21864,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-04 15:15:33',
                'modify_time' => '2017-12-04 15:15:33',
            ),
            67 => 
            array (
                'id' => 15799,
                'client_id' => 21865,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-04 15:17:23',
                'modify_time' => '2017-12-04 15:17:23',
            ),
            68 => 
            array (
                'id' => 15800,
                'client_id' => 21866,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-04 15:19:03',
                'modify_time' => '2017-12-04 15:19:03',
            ),
            69 => 
            array (
                'id' => 15801,
                'client_id' => 21867,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-05 12:05:48',
                'modify_time' => '2017-12-05 12:05:48',
            ),
            70 => 
            array (
                'id' => 15802,
                'client_id' => 21868,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-05 12:08:29',
                'modify_time' => '2017-12-08 14:35:59',
            ),
            71 => 
            array (
                'id' => 15803,
                'client_id' => 21869,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-05 12:20:42',
                'modify_time' => '2017-12-05 12:20:42',
            ),
            72 => 
            array (
                'id' => 15804,
                'client_id' => 21870,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-05 14:53:13',
                'modify_time' => '2017-12-05 14:53:13',
            ),
            73 => 
            array (
                'id' => 15805,
                'client_id' => 21871,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-05 15:10:04',
                'modify_time' => '2017-12-05 15:10:04',
            ),
            74 => 
            array (
                'id' => 15806,
                'client_id' => 21872,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 2,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-07 11:09:04',
                'modify_time' => '2018-01-12 16:34:04',
            ),
            75 => 
            array (
                'id' => 15807,
                'client_id' => 21873,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 4,
                'convert_driver' => 0,
                'create_time' => '2017-12-07 14:41:07',
                'modify_time' => '2017-12-07 15:23:36',
            ),
            76 => 
            array (
                'id' => 15808,
                'client_id' => 21874,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 1,
                'convert_driver' => 0,
                'create_time' => '2017-12-11 11:59:21',
                'modify_time' => '2018-01-02 11:51:18',
            ),
            77 => 
            array (
                'id' => 15809,
                'client_id' => 21875,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-14 11:17:19',
                'modify_time' => '2017-12-14 11:17:19',
            ),
            78 => 
            array (
                'id' => 15810,
                'client_id' => 21876,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-20 15:07:37',
                'modify_time' => '2017-12-20 15:07:37',
            ),
            79 => 
            array (
                'id' => 15811,
                'client_id' => 21877,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-22 17:16:27',
                'modify_time' => '2017-12-22 17:16:27',
            ),
            80 => 
            array (
                'id' => 15812,
                'client_id' => 21878,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-22 17:20:58',
                'modify_time' => '2017-12-22 17:20:58',
            ),
            81 => 
            array (
                'id' => 15813,
                'client_id' => 21879,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-22 17:30:44',
                'modify_time' => '2017-12-22 17:30:44',
            ),
            82 => 
            array (
                'id' => 15814,
                'client_id' => 21880,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-25 17:15:29',
                'modify_time' => '2017-12-26 11:38:33',
            ),
            83 => 
            array (
                'id' => 15815,
                'client_id' => 21881,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-25 17:18:48',
                'modify_time' => '2017-12-25 17:18:48',
            ),
            84 => 
            array (
                'id' => 15816,
                'client_id' => 21882,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 19,
                'operations_cancel' => 7,
                'wait_pay_order' => 4,
                'finish_order' => 1,
                'convert_driver' => 0,
                'create_time' => '2017-12-25 17:21:31',
                'modify_time' => '2017-12-27 14:25:39',
            ),
            85 => 
            array (
                'id' => 15817,
                'client_id' => 21883,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 2,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 4,
                'convert_driver' => 0,
                'create_time' => '2017-12-27 14:01:18',
                'modify_time' => '2017-12-29 09:42:38',
            ),
            86 => 
            array (
                'id' => 15818,
                'client_id' => 21884,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 2,
                'convert_driver' => 0,
                'create_time' => '2017-12-28 14:12:43',
                'modify_time' => '2017-12-28 17:57:46',
            ),
            87 => 
            array (
                'id' => 15819,
                'client_id' => 21885,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2017-12-28 14:13:28',
                'modify_time' => '2018-01-04 10:01:25',
            ),
            88 => 
            array (
                'id' => 15820,
                'client_id' => 21886,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-01-08 09:56:59',
                'modify_time' => '2018-01-09 11:14:29',
            ),
            89 => 
            array (
                'id' => 15821,
                'client_id' => 21887,
                'wait_assign' => 1,
                'hand_order' => 0,
                'cancel_order' => 14,
                'operations_cancel' => 0,
                'wait_pay_order' => -5,
                'finish_order' => 12,
                'convert_driver' => 1,
                'create_time' => '2018-01-08 14:41:22',
                'modify_time' => '2018-02-01 16:26:05',
            ),
            90 => 
            array (
                'id' => 15822,
                'client_id' => 21888,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-01-31 14:35:26',
                'modify_time' => '2018-01-31 14:35:26',
            ),
            91 => 
            array (
                'id' => 15823,
                'client_id' => 21889,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-02 17:08:37',
                'modify_time' => '2018-04-02 17:08:37',
            ),
            92 => 
            array (
                'id' => 15824,
                'client_id' => 21890,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-02 17:10:28',
                'modify_time' => '2018-04-02 17:10:28',
            ),
            93 => 
            array (
                'id' => 15825,
                'client_id' => 21891,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-02 17:12:05',
                'modify_time' => '2018-04-02 17:12:05',
            ),
            94 => 
            array (
                'id' => 15826,
                'client_id' => 21892,
                'wait_assign' => 2,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-02 17:13:11',
                'modify_time' => '2018-04-02 17:19:58',
            ),
            95 => 
            array (
                'id' => 15827,
                'client_id' => 21893,
                'wait_assign' => 35,
                'hand_order' => 0,
                'cancel_order' => 24,
                'operations_cancel' => 6,
                'wait_pay_order' => 0,
                'finish_order' => 86,
                'convert_driver' => 2,
                'create_time' => '2018-04-18 14:27:20',
                'modify_time' => '2018-07-06 13:42:15',
            ),
            96 => 
            array (
                'id' => 15828,
                'client_id' => 21894,
                'wait_assign' => 44,
                'hand_order' => -11,
                'cancel_order' => 27,
                'operations_cancel' => 4,
                'wait_pay_order' => 11,
                'finish_order' => 78,
                'convert_driver' => 10,
                'create_time' => '2018-04-18 15:48:37',
                'modify_time' => '2018-08-31 16:54:26',
            ),
            97 => 
            array (
                'id' => 15829,
                'client_id' => 21895,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-18 20:45:09',
                'modify_time' => '2018-04-18 20:45:09',
            ),
            98 => 
            array (
                'id' => 15830,
                'client_id' => 21896,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-19 17:27:39',
                'modify_time' => '2018-05-07 16:22:29',
            ),
            99 => 
            array (
                'id' => 15831,
                'client_id' => 21897,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 2,
                'operations_cancel' => 4,
                'wait_pay_order' => 1,
                'finish_order' => 2,
                'convert_driver' => 2,
                'create_time' => '2018-04-20 10:23:00',
                'modify_time' => '2018-05-14 15:21:20',
            ),
            100 => 
            array (
                'id' => 15832,
                'client_id' => 21898,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-20 15:13:31',
                'modify_time' => '2018-04-20 15:13:31',
            ),
            101 => 
            array (
                'id' => 15833,
                'client_id' => 21899,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 2,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-22 08:00:46',
                'modify_time' => '2018-04-22 08:07:52',
            ),
            102 => 
            array (
                'id' => 15834,
                'client_id' => 21900,
                'wait_assign' => 11,
                'hand_order' => 0,
                'cancel_order' => 11,
                'operations_cancel' => 3,
                'wait_pay_order' => -1,
                'finish_order' => 55,
                'convert_driver' => 0,
                'create_time' => '2018-04-24 11:15:50',
                'modify_time' => '2018-09-29 09:40:42',
            ),
            103 => 
            array (
                'id' => 15835,
                'client_id' => 21901,
                'wait_assign' => 1,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-04-24 16:12:33',
                'modify_time' => '2018-06-07 14:58:47',
            ),
            104 => 
            array (
                'id' => 15836,
                'client_id' => 21902,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-05-10 15:04:23',
                'modify_time' => '2018-05-10 15:04:23',
            ),
            105 => 
            array (
                'id' => 15837,
                'client_id' => 21903,
                'wait_assign' => 1,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-05-15 10:44:49',
                'modify_time' => '2018-05-15 16:13:30',
            ),
            106 => 
            array (
                'id' => 15838,
                'client_id' => 21904,
                'wait_assign' => 4,
                'hand_order' => 2,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 1,
                'finish_order' => 11,
                'convert_driver' => 1,
                'create_time' => '2018-05-16 12:19:44',
                'modify_time' => '2018-09-06 14:23:03',
            ),
            107 => 
            array (
                'id' => 15839,
                'client_id' => 21905,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => -1,
                'finish_order' => 1,
                'convert_driver' => 0,
                'create_time' => '2018-05-21 16:41:56',
                'modify_time' => '2018-05-21 16:56:53',
            ),
            108 => 
            array (
                'id' => 15840,
                'client_id' => 21906,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-05-29 10:56:30',
                'modify_time' => '2018-05-29 10:56:30',
            ),
            109 => 
            array (
                'id' => 15841,
                'client_id' => 21907,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 17,
                'operations_cancel' => 2,
                'wait_pay_order' => 0,
                'finish_order' => 14,
                'convert_driver' => 1,
                'create_time' => '2018-05-30 11:20:47',
                'modify_time' => '2018-09-17 11:40:30',
            ),
            110 => 
            array (
                'id' => 15842,
                'client_id' => 21908,
                'wait_assign' => 1,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-06-25 09:05:01',
                'modify_time' => '2018-06-25 09:05:16',
            ),
            111 => 
            array (
                'id' => 15843,
                'client_id' => 21909,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 1,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-06-30 13:57:36',
                'modify_time' => '2018-06-30 14:03:06',
            ),
            112 => 
            array (
                'id' => 15844,
                'client_id' => 21910,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-01 13:27:20',
                'modify_time' => '2018-07-01 13:27:20',
            ),
            113 => 
            array (
                'id' => 15845,
                'client_id' => 21911,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-04 11:32:00',
                'modify_time' => '2018-07-04 11:32:00',
            ),
            114 => 
            array (
                'id' => 15846,
                'client_id' => 21912,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-04 11:38:59',
                'modify_time' => '2018-07-04 11:38:59',
            ),
            115 => 
            array (
                'id' => 15847,
                'client_id' => 21913,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-12 16:32:19',
                'modify_time' => '2018-07-12 16:32:19',
            ),
            116 => 
            array (
                'id' => 15848,
                'client_id' => 21914,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-12 16:56:03',
                'modify_time' => '2018-07-12 16:56:03',
            ),
            117 => 
            array (
                'id' => 15849,
                'client_id' => 21915,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-12 18:11:39',
                'modify_time' => '2018-07-12 18:11:39',
            ),
            118 => 
            array (
                'id' => 15850,
                'client_id' => 21916,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-13 16:58:26',
                'modify_time' => '2018-07-13 16:58:26',
            ),
            119 => 
            array (
                'id' => 15851,
                'client_id' => 21917,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-13 17:00:21',
                'modify_time' => '2018-07-13 17:00:21',
            ),
            120 => 
            array (
                'id' => 15852,
                'client_id' => 21918,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 09:31:37',
                'modify_time' => '2018-07-14 09:31:37',
            ),
            121 => 
            array (
                'id' => 15853,
                'client_id' => 21919,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 11:13:43',
                'modify_time' => '2018-07-14 11:13:43',
            ),
            122 => 
            array (
                'id' => 15854,
                'client_id' => 21920,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 11:19:08',
                'modify_time' => '2018-07-14 11:19:08',
            ),
            123 => 
            array (
                'id' => 15855,
                'client_id' => 21921,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 11:26:36',
                'modify_time' => '2018-07-14 11:26:36',
            ),
            124 => 
            array (
                'id' => 15856,
                'client_id' => 21922,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 11:35:47',
                'modify_time' => '2018-07-14 11:35:47',
            ),
            125 => 
            array (
                'id' => 15857,
                'client_id' => 21923,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 12:30:17',
                'modify_time' => '2018-07-14 12:30:17',
            ),
            126 => 
            array (
                'id' => 15858,
                'client_id' => 21924,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 14:58:57',
                'modify_time' => '2018-07-14 14:58:57',
            ),
            127 => 
            array (
                'id' => 15859,
                'client_id' => 21925,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:00:12',
                'modify_time' => '2018-07-14 15:00:12',
            ),
            128 => 
            array (
                'id' => 15860,
                'client_id' => 21926,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:01:53',
                'modify_time' => '2018-07-14 15:01:53',
            ),
            129 => 
            array (
                'id' => 15861,
                'client_id' => 21927,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:03:09',
                'modify_time' => '2018-07-14 15:03:09',
            ),
            130 => 
            array (
                'id' => 15862,
                'client_id' => 21928,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:03:40',
                'modify_time' => '2018-07-14 15:03:40',
            ),
            131 => 
            array (
                'id' => 15863,
                'client_id' => 21929,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:04:06',
                'modify_time' => '2018-07-14 15:04:06',
            ),
            132 => 
            array (
                'id' => 15864,
                'client_id' => 21930,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:04:34',
                'modify_time' => '2018-07-14 15:04:34',
            ),
            133 => 
            array (
                'id' => 15865,
                'client_id' => 21931,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:04:55',
                'modify_time' => '2018-07-14 15:04:55',
            ),
            134 => 
            array (
                'id' => 15866,
                'client_id' => 21932,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:05:26',
                'modify_time' => '2018-07-14 15:05:26',
            ),
            135 => 
            array (
                'id' => 15867,
                'client_id' => 21933,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:06:32',
                'modify_time' => '2018-07-14 15:06:32',
            ),
            136 => 
            array (
                'id' => 15868,
                'client_id' => 21934,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:07:16',
                'modify_time' => '2018-07-14 15:07:16',
            ),
            137 => 
            array (
                'id' => 15869,
                'client_id' => 21935,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:07:46',
                'modify_time' => '2018-07-14 15:07:46',
            ),
            138 => 
            array (
                'id' => 15870,
                'client_id' => 21936,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:08:32',
                'modify_time' => '2018-07-14 15:08:32',
            ),
            139 => 
            array (
                'id' => 15871,
                'client_id' => 21937,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:09:18',
                'modify_time' => '2018-07-14 15:09:18',
            ),
            140 => 
            array (
                'id' => 15872,
                'client_id' => 21938,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:09:58',
                'modify_time' => '2018-07-14 15:09:58',
            ),
            141 => 
            array (
                'id' => 15873,
                'client_id' => 21939,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:11:07',
                'modify_time' => '2018-07-14 15:11:07',
            ),
            142 => 
            array (
                'id' => 15874,
                'client_id' => 21940,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:14:59',
                'modify_time' => '2018-07-14 15:14:59',
            ),
            143 => 
            array (
                'id' => 15875,
                'client_id' => 21941,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:15:33',
                'modify_time' => '2018-07-14 15:15:33',
            ),
            144 => 
            array (
                'id' => 15876,
                'client_id' => 21942,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:16:01',
                'modify_time' => '2018-07-14 15:16:01',
            ),
            145 => 
            array (
                'id' => 15877,
                'client_id' => 21943,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:16:35',
                'modify_time' => '2018-07-14 15:16:35',
            ),
            146 => 
            array (
                'id' => 15878,
                'client_id' => 21944,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-14 15:17:12',
                'modify_time' => '2018-07-14 15:17:12',
            ),
            147 => 
            array (
                'id' => 15879,
                'client_id' => 21945,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 14:18:03',
                'modify_time' => '2018-07-16 14:18:03',
            ),
            148 => 
            array (
                'id' => 15880,
                'client_id' => 21946,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 14:20:32',
                'modify_time' => '2018-07-16 14:20:32',
            ),
            149 => 
            array (
                'id' => 15881,
                'client_id' => 21947,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 15:22:49',
                'modify_time' => '2018-07-16 15:22:49',
            ),
            150 => 
            array (
                'id' => 15882,
                'client_id' => 21948,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 15:24:51',
                'modify_time' => '2018-07-16 15:24:51',
            ),
            151 => 
            array (
                'id' => 15883,
                'client_id' => 21949,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 15:41:05',
                'modify_time' => '2018-07-16 15:41:05',
            ),
            152 => 
            array (
                'id' => 15884,
                'client_id' => 21950,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 15:41:56',
                'modify_time' => '2018-07-16 15:41:56',
            ),
            153 => 
            array (
                'id' => 15885,
                'client_id' => 21951,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 15:46:27',
                'modify_time' => '2018-07-16 15:46:27',
            ),
            154 => 
            array (
                'id' => 15886,
                'client_id' => 21952,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 15:49:49',
                'modify_time' => '2018-07-16 15:49:49',
            ),
            155 => 
            array (
                'id' => 15887,
                'client_id' => 21953,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 15:51:09',
                'modify_time' => '2018-07-16 15:51:09',
            ),
            156 => 
            array (
                'id' => 15888,
                'client_id' => 21954,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 16:06:22',
                'modify_time' => '2018-07-16 16:06:22',
            ),
            157 => 
            array (
                'id' => 15889,
                'client_id' => 21955,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 16:10:54',
                'modify_time' => '2018-07-16 16:10:54',
            ),
            158 => 
            array (
                'id' => 15890,
                'client_id' => 21956,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 16:16:42',
                'modify_time' => '2018-07-16 16:16:42',
            ),
            159 => 
            array (
                'id' => 15891,
                'client_id' => 21957,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 16:18:05',
                'modify_time' => '2018-07-16 16:18:05',
            ),
            160 => 
            array (
                'id' => 15892,
                'client_id' => 21958,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 16:26:55',
                'modify_time' => '2018-07-16 16:26:55',
            ),
            161 => 
            array (
                'id' => 15893,
                'client_id' => 21959,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 16:44:14',
                'modify_time' => '2018-07-16 16:44:14',
            ),
            162 => 
            array (
                'id' => 15894,
                'client_id' => 21960,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-16 16:54:14',
                'modify_time' => '2018-07-16 16:54:14',
            ),
            163 => 
            array (
                'id' => 15895,
                'client_id' => 21961,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 0,
                'convert_driver' => 0,
                'create_time' => '2018-07-17 09:06:45',
                'modify_time' => '2018-07-17 09:06:45',
            ),
            164 => 
            array (
                'id' => 15896,
                'client_id' => 21962,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 1,
                'convert_driver' => 0,
                'create_time' => '2018-07-20 15:40:49',
                'modify_time' => '2018-07-20 15:58:15',
            ),
            165 => 
            array (
                'id' => 15897,
                'client_id' => 21963,
                'wait_assign' => 3,
                'hand_order' => 0,
                'cancel_order' => 3,
                'operations_cancel' => 2,
                'wait_pay_order' => 1,
                'finish_order' => 36,
                'convert_driver' => 1,
                'create_time' => '2018-08-03 12:24:14',
                'modify_time' => '2018-09-15 10:54:21',
            ),
            166 => 
            array (
                'id' => 15898,
                'client_id' => 21964,
                'wait_assign' => 0,
                'hand_order' => 0,
                'cancel_order' => 0,
                'operations_cancel' => 0,
                'wait_pay_order' => 0,
                'finish_order' => 1,
                'convert_driver' => 1,
                'create_time' => '2018-09-05 09:39:54',
                'modify_time' => '2018-09-12 14:26:55',
            ),
        ));
        
        
    }
}