<?php

use Illuminate\Database\Seeder;

class MallOrderDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mall_order_details')->delete();
        
        \DB::table('mall_order_details')->insert(array (
            0 => 
            array (
                'id' => 35,
                'client_id' => 21963,
                'product_id' => 13,
                'product_type' => 0,
                'name' => '娃娃',
                'count' => 1,
                'carbon_coin' => 30,
                'receipt_name' => '测试',
                'receipt_phone' => '17620496365',
                'receipt_address' => '中州大厦',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-28 15:52:37',
                'modify_time' => NULL,
            ),
            1 => 
            array (
                'id' => 36,
                'client_id' => 21963,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 5,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 11:51:12',
                'modify_time' => NULL,
            ),
            2 => 
            array (
                'id' => 37,
                'client_id' => 21963,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 1,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 11:52:11',
                'modify_time' => NULL,
            ),
            3 => 
            array (
                'id' => 38,
                'client_id' => 21963,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 11:52:14',
                'modify_time' => NULL,
            ),
            4 => 
            array (
                'id' => 39,
                'client_id' => 21963,
                'product_id' => 13,
                'product_type' => 0,
                'name' => '娃娃',
                'count' => 3,
                'carbon_coin' => 30,
                'receipt_name' => '测试',
                'receipt_phone' => '17620496365',
                'receipt_address' => '中州大厦',
                'receipt_time' => '2018-09-07 17:40:44',
                'status' => 2,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 11:52:20',
                'modify_time' => '2018-09-07 17:40:44',
            ),
            5 => 
            array (
                'id' => 40,
                'client_id' => 21963,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 11:52:23',
                'modify_time' => NULL,
            ),
            6 => 
            array (
                'id' => 41,
                'client_id' => 21900,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 3,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 15:21:01',
                'modify_time' => NULL,
            ),
            7 => 
            array (
                'id' => 42,
                'client_id' => 21900,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 2,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 15:24:41',
                'modify_time' => NULL,
            ),
            8 => 
            array (
                'id' => 43,
                'client_id' => 21900,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 15:49:40',
                'modify_time' => NULL,
            ),
            9 => 
            array (
                'id' => 44,
                'client_id' => 21900,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 16:00:59',
                'modify_time' => NULL,
            ),
            10 => 
            array (
                'id' => 45,
                'client_id' => 21900,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 2,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 16:11:20',
                'modify_time' => NULL,
            ),
            11 => 
            array (
                'id' => 46,
                'client_id' => 21900,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 2,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 16:11:25',
                'modify_time' => NULL,
            ),
            12 => 
            array (
                'id' => 47,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 16:57:50',
                'modify_time' => NULL,
            ),
            13 => 
            array (
                'id' => 48,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-29 16:58:08',
                'modify_time' => NULL,
            ),
            14 => 
            array (
                'id' => 49,
                'client_id' => 21963,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 09:25:14',
                'modify_time' => NULL,
            ),
            15 => 
            array (
                'id' => 50,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 09:42:02',
                'modify_time' => NULL,
            ),
            16 => 
            array (
                'id' => 51,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:21:35',
                'modify_time' => NULL,
            ),
            17 => 
            array (
                'id' => 52,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:21:58',
                'modify_time' => NULL,
            ),
            18 => 
            array (
                'id' => 53,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:22:43',
                'modify_time' => NULL,
            ),
            19 => 
            array (
                'id' => 54,
                'client_id' => 21963,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:42:55',
                'modify_time' => NULL,
            ),
            20 => 
            array (
                'id' => 55,
                'client_id' => 21963,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:43:01',
                'modify_time' => NULL,
            ),
            21 => 
            array (
                'id' => 56,
                'client_id' => 21963,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 2,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:48:07',
                'modify_time' => NULL,
            ),
            22 => 
            array (
                'id' => 57,
                'client_id' => 21963,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 2,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:49:11',
                'modify_time' => NULL,
            ),
            23 => 
            array (
                'id' => 58,
                'client_id' => 21963,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 2,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:51:54',
                'modify_time' => NULL,
            ),
            24 => 
            array (
                'id' => 59,
                'client_id' => 21963,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 2,
                'carbon_coin' => 200,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 11:58:43',
                'modify_time' => NULL,
            ),
            25 => 
            array (
                'id' => 60,
                'client_id' => 21963,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 2,
                'carbon_coin' => 200,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 12:03:36',
                'modify_time' => NULL,
            ),
            26 => 
            array (
                'id' => 61,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 12:04:09',
                'modify_time' => NULL,
            ),
            27 => 
            array (
                'id' => 62,
                'client_id' => 21900,
                'product_id' => 19,
                'product_type' => 0,
                'name' => '买买买',
                'count' => 1,
                'carbon_coin' => 10,
                'receipt_name' => '我',
                'receipt_phone' => '11111111111',
                'receipt_address' => '我的人都有',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => '{"id":"","name":"\\u6309\\u65f6\\u6492\\u591a\\u6240","number":"","type":"2"}',
                'create_time' => '2018-08-30 15:18:07',
                'modify_time' => '2018-08-30 15:56:08',
            ),
            28 => 
            array (
                'id' => 63,
                'client_id' => 21800,
                'product_id' => 13,
                'product_type' => 0,
                'name' => '娃娃',
                'count' => 1,
                'carbon_coin' => 30,
                'receipt_name' => '测试',
                'receipt_phone' => '13410425217',
                'receipt_address' => '就瞬间觉得简单哈哈哈哈',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-30 15:44:43',
                'modify_time' => NULL,
            ),
            29 => 
            array (
                'id' => 64,
                'client_id' => 21894,
                'product_id' => 19,
                'product_type' => 2,
                'name' => '买买买',
                'count' => 1,
                'carbon_coin' => 10,
                'receipt_name' => '我',
                'receipt_phone' => '12457545454',
                'receipt_address' => '你的',
                'receipt_time' => '2018-08-30 16:23:03',
                'status' => 2,
                'deliveryer' => '{"id":"","name":"\\u554a","number":"","type":"2"}',
                'create_time' => '2018-08-30 16:17:06',
                'modify_time' => '2018-08-30 16:23:03',
            ),
            30 => 
            array (
                'id' => 65,
                'client_id' => 21900,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 2,
                'carbon_coin' => 2,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-31 09:20:08',
                'modify_time' => NULL,
            ),
            31 => 
            array (
                'id' => 66,
                'client_id' => 21894,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-31 15:02:03',
                'modify_time' => NULL,
            ),
            32 => 
            array (
                'id' => 67,
                'client_id' => 21894,
                'product_id' => 20,
                'product_type' => 0,
                'name' => '50大洋',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-31 15:07:34',
                'modify_time' => NULL,
            ),
            33 => 
            array (
                'id' => 68,
                'client_id' => 21800,
                'product_id' => 21,
                'product_type' => 0,
                'name' => '广东省兑换券商品',
                'count' => 1,
                'carbon_coin' => 60,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-31 15:23:54',
                'modify_time' => NULL,
            ),
            34 => 
            array (
                'id' => 69,
                'client_id' => 21800,
                'product_id' => 21,
                'product_type' => 0,
                'name' => '广东省兑换券商品',
                'count' => 3,
                'carbon_coin' => 540,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-31 15:24:05',
                'modify_time' => NULL,
            ),
            35 => 
            array (
                'id' => 70,
                'client_id' => 21894,
                'product_id' => 20,
                'product_type' => 0,
                'name' => '50大洋',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-31 15:34:57',
                'modify_time' => NULL,
            ),
            36 => 
            array (
                'id' => 71,
                'client_id' => 21804,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 3,
                'carbon_coin' => 300,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-08-31 15:41:30',
                'modify_time' => NULL,
            ),
            37 => 
            array (
                'id' => 72,
                'client_id' => 21904,
                'product_id' => 22,
                'product_type' => 0,
                'name' => '测试',
                'count' => 1,
                'carbon_coin' => 111,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-04 15:23:34',
                'modify_time' => NULL,
            ),
            38 => 
            array (
                'id' => 73,
                'client_id' => 21904,
                'product_id' => 20,
                'product_type' => 0,
                'name' => '50大洋',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-04 15:24:00',
                'modify_time' => NULL,
            ),
            39 => 
            array (
                'id' => 74,
                'client_id' => 21904,
                'product_id' => 20,
                'product_type' => 0,
                'name' => '50大洋',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-04 16:00:54',
                'modify_time' => NULL,
            ),
            40 => 
            array (
                'id' => 75,
                'client_id' => 21904,
                'product_id' => 20,
                'product_type' => 0,
                'name' => '50大洋',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-04 16:01:00',
                'modify_time' => NULL,
            ),
            41 => 
            array (
                'id' => 76,
                'client_id' => 21800,
                'product_id' => 19,
                'product_type' => 2,
                'name' => '买买买',
                'count' => 1,
                'carbon_coin' => 10,
                'receipt_name' => '测试',
                'receipt_phone' => '13410425217',
                'receipt_address' => '就瞬间觉得简单哈哈哈哈',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-05 10:21:25',
                'modify_time' => NULL,
            ),
            42 => 
            array (
                'id' => 77,
                'client_id' => 21804,
                'product_id' => 16,
                'product_type' => 2,
                'name' => '哟哟哟哟',
                'count' => 1,
                'carbon_coin' => 30,
                'receipt_name' => '何世强',
                'receipt_phone' => '15327276711',
                'receipt_address' => '广东省中医院',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-05 11:17:09',
                'modify_time' => NULL,
            ),
            43 => 
            array (
                'id' => 78,
                'client_id' => 21804,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 1,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-05 17:49:25',
                'modify_time' => NULL,
            ),
            44 => 
            array (
                'id' => 79,
                'client_id' => 21804,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-05 17:53:52',
                'modify_time' => NULL,
            ),
            45 => 
            array (
                'id' => 80,
                'client_id' => 21907,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-05 17:57:02',
                'modify_time' => NULL,
            ),
            46 => 
            array (
                'id' => 81,
                'client_id' => 21804,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 1,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-06 11:06:48',
                'modify_time' => NULL,
            ),
            47 => 
            array (
                'id' => 82,
                'client_id' => 21804,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 1,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-06 11:11:59',
                'modify_time' => NULL,
            ),
            48 => 
            array (
                'id' => 83,
                'client_id' => 21804,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-06 11:12:05',
                'modify_time' => NULL,
            ),
            49 => 
            array (
                'id' => 84,
                'client_id' => 21804,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => '2018-09-10 09:12:35',
                'status' => 2,
                'deliveryer' => '{"id":"15","name":"\\u987a\\u4e30","number":"465346","type":"1"}',
                'create_time' => '2018-09-06 11:13:18',
                'modify_time' => '2018-09-10 09:28:42',
            ),
            50 => 
            array (
                'id' => 85,
                'client_id' => 21804,
                'product_id' => 13,
                'product_type' => 2,
                'name' => '娃娃',
                'count' => 1,
                'carbon_coin' => 30,
                'receipt_name' => '何世强',
                'receipt_phone' => '15327276711',
                'receipt_address' => '广东省中医院',
                'receipt_time' => '2018-09-07 17:41:47',
                'status' => 2,
                'deliveryer' => '{"id":"14","name":"\\u4e2d\\u901a","number":"45646","type":"1"}',
                'create_time' => '2018-09-06 11:34:38',
                'modify_time' => '2018-09-10 09:28:01',
            ),
            51 => 
            array (
                'id' => 86,
                'client_id' => 21804,
                'product_id' => 13,
                'product_type' => 2,
                'name' => '娃娃',
                'count' => 1,
                'carbon_coin' => 30,
                'receipt_name' => '何世强',
                'receipt_phone' => '15327276711',
                'receipt_address' => '广东省中医院',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => '{"id":"14","name":"\\u4e2d\\u901a","number":"\\u94a2\\u7ed3\\u6784\\u5212\\u5206\\u75be\\u98ce\\u5251\\u8c6a","type":"1"}',
                'create_time' => '2018-09-06 14:04:51',
                'modify_time' => '2018-09-10 09:13:59',
            ),
            52 => 
            array (
                'id' => 87,
                'client_id' => 21807,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => '{"id":"","name":"\\u5510\\u96e8\\u67d4\\u4f53\\u80b2","number":"","type":"2"}',
                'create_time' => '2018-09-06 14:42:51',
                'modify_time' => '2018-09-10 09:14:11',
            ),
            53 => 
            array (
                'id' => 88,
                'client_id' => 21804,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 4,
                'carbon_coin' => 80,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-07 17:26:23',
                'modify_time' => NULL,
            ),
            54 => 
            array (
                'id' => 89,
                'client_id' => 21804,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-07 17:27:07',
                'modify_time' => NULL,
            ),
            55 => 
            array (
                'id' => 90,
                'client_id' => 21804,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-07 17:27:13',
                'modify_time' => NULL,
            ),
            56 => 
            array (
                'id' => 91,
                'client_id' => 21804,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-07 17:27:35',
                'modify_time' => NULL,
            ),
            57 => 
            array (
                'id' => 92,
                'client_id' => 21804,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-07 17:27:42',
                'modify_time' => NULL,
            ),
            58 => 
            array (
                'id' => 93,
                'client_id' => 21804,
                'product_id' => 12,
                'product_type' => 0,
                'name' => '8折优惠券',
                'count' => 2,
                'carbon_coin' => 40,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-07 17:28:43',
                'modify_time' => NULL,
            ),
            59 => 
            array (
                'id' => 94,
                'client_id' => 21907,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 1,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-11 11:17:13',
                'modify_time' => NULL,
            ),
            60 => 
            array (
                'id' => 95,
                'client_id' => 21964,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-12 14:32:14',
                'modify_time' => NULL,
            ),
            61 => 
            array (
                'id' => 96,
                'client_id' => 21964,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-12 14:32:29',
                'modify_time' => NULL,
            ),
            62 => 
            array (
                'id' => 97,
                'client_id' => 21964,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-12 14:32:42',
                'modify_time' => NULL,
            ),
            63 => 
            array (
                'id' => 98,
                'client_id' => 21817,
                'product_id' => 18,
                'product_type' => 0,
                'name' => '2',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => '2018-09-12 15:57:20',
                'status' => 2,
                'deliveryer' => '{"id":"15","name":"\\u987a\\u4e30","number":"65231","type":"1"}',
                'create_time' => '2018-09-12 15:52:53',
                'modify_time' => '2018-09-12 15:57:20',
            ),
            64 => 
            array (
                'id' => 99,
                'client_id' => 21817,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-12 15:53:54',
                'modify_time' => NULL,
            ),
            65 => 
            array (
                'id' => 100,
                'client_id' => 21817,
                'product_id' => 23,
                'product_type' => 2,
                'name' => '测试商品',
                'count' => 1,
                'carbon_coin' => 50,
                'receipt_name' => '测试',
                'receipt_phone' => '13510525935',
                'receipt_address' => '测试',
                'receipt_time' => '2018-09-12 16:06:11',
                'status' => 2,
                'deliveryer' => '{"id":"15","name":"\\u987a\\u4e30","number":"22222222222222","type":"1"}',
                'create_time' => '2018-09-12 16:04:44',
                'modify_time' => '2018-09-12 16:06:11',
            ),
            66 => 
            array (
                'id' => 101,
                'client_id' => 21817,
                'product_id' => 24,
                'product_type' => 0,
                'name' => '测试优惠劵',
                'count' => 1,
                'carbon_coin' => 10,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-12 16:10:48',
                'modify_time' => NULL,
            ),
            67 => 
            array (
                'id' => 102,
                'client_id' => 21900,
                'product_id' => 23,
                'product_type' => 2,
                'name' => '测试商品',
                'count' => 1,
                'carbon_coin' => 50,
                'receipt_name' => '我',
                'receipt_phone' => '11111111111',
                'receipt_address' => '我的人都有',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-12 16:17:56',
                'modify_time' => NULL,
            ),
            68 => 
            array (
                'id' => 103,
                'client_id' => 21816,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-14 18:24:52',
                'modify_time' => NULL,
            ),
            69 => 
            array (
                'id' => 104,
                'client_id' => 21816,
                'product_id' => 26,
                'product_type' => 2,
                'name' => '测试20180914',
                'count' => 1,
                'carbon_coin' => 5,
                'receipt_name' => '我',
                'receipt_phone' => '13510525635',
                'receipt_address' => '11',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-14 18:53:52',
                'modify_time' => NULL,
            ),
            70 => 
            array (
                'id' => 105,
                'client_id' => 21816,
                'product_id' => 26,
                'product_type' => 2,
                'name' => '测试20180914',
                'count' => 1,
                'carbon_coin' => 5,
                'receipt_name' => '华为',
                'receipt_phone' => '13537580621',
                'receipt_address' => '11',
                'receipt_time' => '2018-09-15 10:04:24',
                'status' => 2,
                'deliveryer' => '{"id":"","name":"\\u738b\\u738b\\u4e94\\u914d\\u9001","number":"","type":"2"}',
                'create_time' => '2018-09-15 10:01:44',
                'modify_time' => '2018-09-15 10:04:24',
            ),
            71 => 
            array (
                'id' => 106,
                'client_id' => 21816,
                'product_id' => 15,
                'product_type' => 0,
                'name' => '不兑换就没了',
                'count' => 1,
                'carbon_coin' => 100,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-15 11:24:32',
                'modify_time' => NULL,
            ),
            72 => 
            array (
                'id' => 107,
                'client_id' => 21816,
                'product_id' => 27,
                'product_type' => 0,
                'name' => '95折优惠券',
                'count' => 3,
                'carbon_coin' => 30,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-15 12:09:22',
                'modify_time' => NULL,
            ),
            73 => 
            array (
                'id' => 108,
                'client_id' => 21817,
                'product_id' => 28,
                'product_type' => 0,
                'name' => '九折优惠劵',
                'count' => 1,
                'carbon_coin' => 99,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-15 15:36:19',
                'modify_time' => NULL,
            ),
            74 => 
            array (
                'id' => 109,
                'client_id' => 21817,
                'product_id' => 29,
                'product_type' => 2,
                'name' => '舟舟公仔',
                'count' => 1,
                'carbon_coin' => 990,
                'receipt_name' => '何',
                'receipt_phone' => '13510525935',
                'receipt_address' => '深圳市南山区白石洲东四坊800栋，京基百纳',
                'receipt_time' => '2018-09-15 16:18:39',
                'status' => 2,
                'deliveryer' => '{"id":"17","name":"\\u7533\\u901a","number":"11111111111111","type":"1"}',
                'create_time' => '2018-09-15 16:15:43',
                'modify_time' => '2018-09-15 16:18:39',
            ),
            75 => 
            array (
                'id' => 110,
                'client_id' => 21804,
                'product_id' => 25,
                'product_type' => 2,
                'name' => '测试商品',
                'count' => 1,
                'carbon_coin' => 5,
                'receipt_name' => '何世强',
                'receipt_phone' => '15327276711',
                'receipt_address' => '广东省中医院',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-17 10:33:03',
                'modify_time' => NULL,
            ),
            76 => 
            array (
                'id' => 111,
                'client_id' => 21816,
                'product_id' => 14,
                'product_type' => 0,
                'name' => '8折',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-17 11:55:45',
                'modify_time' => NULL,
            ),
            77 => 
            array (
                'id' => 112,
                'client_id' => 21900,
                'product_id' => 30,
                'product_type' => 2,
                'name' => '赶快看看光华科技',
                'count' => 1,
                'carbon_coin' => 34,
                'receipt_name' => '我',
                'receipt_phone' => '11111111111',
                'receipt_address' => '我的人都有',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-17 20:42:22',
                'modify_time' => NULL,
            ),
            78 => 
            array (
                'id' => 113,
                'client_id' => 21842,
                'product_id' => 27,
                'product_type' => 0,
                'name' => '95折优惠券',
                'count' => 1,
                'carbon_coin' => 10,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-18 09:28:34',
                'modify_time' => NULL,
            ),
            79 => 
            array (
                'id' => 114,
                'client_id' => 21900,
                'product_id' => 29,
                'product_type' => 2,
                'name' => '舟舟公仔',
                'count' => 2,
                'carbon_coin' => 3960,
                'receipt_name' => '我',
                'receipt_phone' => '11111111111',
                'receipt_address' => '我的人都有',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:07:17',
                'modify_time' => NULL,
            ),
            80 => 
            array (
                'id' => 115,
                'client_id' => 21800,
                'product_id' => 29,
                'product_type' => 2,
                'name' => '舟舟公仔',
                'count' => 2,
                'carbon_coin' => 1980,
                'receipt_name' => '测试',
                'receipt_phone' => '13410425217',
                'receipt_address' => '就瞬间觉得简单哈哈哈哈',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:08:03',
                'modify_time' => NULL,
            ),
            81 => 
            array (
                'id' => 116,
                'client_id' => 21894,
                'product_id' => 28,
                'product_type' => 0,
                'name' => '九折优惠劵',
                'count' => 2,
                'carbon_coin' => 396,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:10:56',
                'modify_time' => NULL,
            ),
            82 => 
            array (
                'id' => 117,
                'client_id' => 21894,
                'product_id' => 28,
                'product_type' => 0,
                'name' => '九折优惠劵',
                'count' => 2,
                'carbon_coin' => 396,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:13:04',
                'modify_time' => NULL,
            ),
            83 => 
            array (
                'id' => 118,
                'client_id' => 21804,
                'product_id' => 28,
                'product_type' => 0,
                'name' => '九折优惠劵',
                'count' => 2,
                'carbon_coin' => 198,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:34:43',
                'modify_time' => NULL,
            ),
            84 => 
            array (
                'id' => 119,
                'client_id' => 21800,
                'product_id' => 28,
                'product_type' => 0,
                'name' => '九折优惠劵',
                'count' => 2,
                'carbon_coin' => 198,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:35:10',
                'modify_time' => NULL,
            ),
            85 => 
            array (
                'id' => 120,
                'client_id' => 21900,
                'product_id' => 31,
                'product_type' => 0,
                'name' => 'sssss',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:45:14',
                'modify_time' => NULL,
            ),
            86 => 
            array (
                'id' => 121,
                'client_id' => 21900,
                'product_id' => 32,
                'product_type' => 2,
                'name' => 'xxxxx',
                'count' => 1,
                'carbon_coin' => 20,
                'receipt_name' => '我',
                'receipt_phone' => '11111111111',
                'receipt_address' => '我的人都有',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-21 17:45:39',
                'modify_time' => NULL,
            ),
            87 => 
            array (
                'id' => 122,
                'client_id' => 21800,
                'product_id' => 28,
                'product_type' => 0,
                'name' => '九折优惠劵',
                'count' => 2,
                'carbon_coin' => 198,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 11:49:08',
                'modify_time' => NULL,
            ),
            88 => 
            array (
                'id' => 123,
                'client_id' => 21842,
                'product_id' => 31,
                'product_type' => 0,
                'name' => 'sssss',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 12:06:40',
                'modify_time' => NULL,
            ),
            89 => 
            array (
                'id' => 124,
                'client_id' => 21842,
                'product_id' => 31,
                'product_type' => 0,
                'name' => 'sssss',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 12:08:03',
                'modify_time' => NULL,
            ),
            90 => 
            array (
                'id' => 125,
                'client_id' => 21842,
                'product_id' => 31,
                'product_type' => 0,
                'name' => 'sssss',
                'count' => 2,
                'carbon_coin' => 2,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 14:17:37',
                'modify_time' => NULL,
            ),
            91 => 
            array (
                'id' => 126,
                'client_id' => 21842,
                'product_id' => 31,
                'product_type' => 0,
                'name' => 'sssss',
                'count' => 1,
                'carbon_coin' => 1,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 14:18:31',
                'modify_time' => NULL,
            ),
            92 => 
            array (
                'id' => 127,
                'client_id' => 21842,
                'product_id' => 31,
                'product_type' => 0,
                'name' => 'sssss',
                'count' => 2,
                'carbon_coin' => 2,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 14:18:40',
                'modify_time' => NULL,
            ),
            93 => 
            array (
                'id' => 128,
                'client_id' => 21842,
                'product_id' => 31,
                'product_type' => 0,
                'name' => 'sssss',
                'count' => 2,
                'carbon_coin' => 2,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 14:19:23',
                'modify_time' => NULL,
            ),
            94 => 
            array (
                'id' => 129,
                'client_id' => 21842,
                'product_id' => 27,
                'product_type' => 0,
                'name' => '95折优惠券',
                'count' => 1,
                'carbon_coin' => 10,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 14:21:50',
                'modify_time' => NULL,
            ),
            95 => 
            array (
                'id' => 130,
                'client_id' => 21842,
                'product_id' => 27,
                'product_type' => 0,
                'name' => '95折优惠券',
                'count' => 3,
                'carbon_coin' => 30,
                'receipt_name' => NULL,
                'receipt_phone' => NULL,
                'receipt_address' => NULL,
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-26 14:22:10',
                'modify_time' => NULL,
            ),
            96 => 
            array (
                'id' => 131,
                'client_id' => 21900,
                'product_id' => 29,
                'product_type' => 2,
                'name' => '舟舟公仔',
                'count' => 1,
                'carbon_coin' => 990,
                'receipt_name' => '我',
                'receipt_phone' => '11111111111',
                'receipt_address' => '我的人都有',
                'receipt_time' => NULL,
                'status' => 1,
                'deliveryer' => NULL,
                'create_time' => '2018-09-29 09:38:01',
                'modify_time' => NULL,
            ),
        ));
        
        
    }
}