<?php

use Illuminate\Database\Seeder;

class SaleCouponsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sale_coupons')->delete();
        
        \DB::table('sale_coupons')->insert(array (
            0 => 
            array (
                'id' => 290,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'invite_friend_c',
                'name' => '兑换邀请码：货主',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2016-11-03 19:43:22',
                'modify_time' => '2016-11-03 19:43:22',
            ),
            1 => 
            array (
                'id' => 291,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'invite_friend_d',
                'name' => '兑换邀请码：司机',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2016-11-03 19:43:22',
                'modify_time' => '2016-11-03 19:43:22',
            ),
            2 => 
            array (
                'id' => 292,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'invite_friend_i',
                'name' => '兑换邀请码：地推',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2016-11-03 19:43:22',
                'modify_time' => '2016-11-03 19:43:22',
            ),
            3 => 
            array (
                'id' => 293,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => 'invite_friend_first_order',
                'name' => '兑换邀请好友首次用车',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2016-11-03 19:43:22',
                'modify_time' => '2016-11-03 19:43:22',
            ),
            4 => 
            array (
                'id' => 294,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '现金券',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2017-03-29 14:34:26',
                'modify_time' => '2017-03-29 14:34:26',
            ),
            5 => 
            array (
                'id' => 295,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '折扣券',
                'coupons_value' => '8.50',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2017-03-29 14:34:57',
                'modify_time' => '2017-03-29 14:36:01',
            ),
            6 => 
            array (
                'id' => 296,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => '',
                'name' => '套餐充值',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 2,
                'status' => 1,
                'create_time' => '2017-03-29 14:35:32',
                'modify_time' => '2017-03-29 14:35:32',
            ),
            7 => 
            array (
                'id' => 297,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 3,
                'call_code' => '方舟货的',
                'name' => '口令领取',
                'coupons_value' => '15.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-03-29 14:37:07',
                'modify_time' => '2017-03-29 14:37:07',
            ),
            8 => 
            array (
                'id' => 298,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 3,
                'call_code' => '方舟货的',
                'name' => '口令领取',
                'coupons_value' => '15.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-03-29 14:37:11',
                'modify_time' => '2017-03-29 14:37:11',
            ),
            9 => 
            array (
                'id' => 299,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'order_share_rebate_self',
                'name' => '单单返本人',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-03-29 16:38:51',
                'modify_time' => '2017-03-29 16:38:51',
            ),
            10 => 
            array (
                'id' => 300,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'order_share_rebate_new',
                'name' => '单单返新用户',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-03-29 16:39:29',
                'modify_time' => '2017-03-29 16:39:29',
            ),
            11 => 
            array (
                'id' => 301,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '大是大非',
                'coupons_value' => '9.60',
                'type' => 2,
                'max_fee' => '21.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2017-05-04 11:55:47',
                'modify_time' => '2017-05-04 11:55:47',
            ),
            12 => 
            array (
                'id' => 302,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '飞洒额度',
                'coupons_value' => '18.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2017-05-04 11:56:46',
                'modify_time' => '2017-05-04 11:56:46',
            ),
            13 => 
            array (
                'id' => 303,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '短发',
                'coupons_value' => '24.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 60,
                'status' => 1,
                'create_time' => '2017-05-04 14:51:01',
                'modify_time' => '2017-05-04 14:51:08',
            ),
            14 => 
            array (
                'id' => 304,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳8折优惠劵',
                'coupons_value' => '8.00',
                'type' => 2,
                'max_fee' => '25.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-11 10:56:58',
                'modify_time' => '2017-05-13 14:51:46',
            ),
            15 => 
            array (
                'id' => 305,
                'category_id' => 100182,
                'category_code' => '0102006',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '北京一天有效期8折劵',
                'coupons_value' => '8.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-13 10:13:55',
                'modify_time' => '2017-05-13 10:13:55',
            ),
            16 => 
            array (
                'id' => 306,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳1折劵',
                'coupons_value' => '1.00',
                'type' => 2,
                'max_fee' => '50.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-15 10:46:44',
                'modify_time' => '2017-05-15 10:46:44',
            ),
            17 => 
            array (
                'id' => 307,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => '',
                'name' => '深圳套餐8折劵',
                'coupons_value' => '8.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-15 10:47:34',
                'modify_time' => '2017-05-15 10:47:34',
            ),
            18 => 
            array (
                'id' => 308,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 3,
                'call_code' => 'FZHD001',
                'name' => '深圳口令10元现金劵',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-15 10:51:44',
                'modify_time' => '2017-05-15 10:51:44',
            ),
            19 => 
            array (
                'id' => 309,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳1折优惠劵',
                'coupons_value' => '1.00',
                'type' => 2,
                'max_fee' => '100.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-15 10:58:43',
                'modify_time' => '2017-05-15 10:58:43',
            ),
            20 => 
            array (
                'id' => 310,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '3299优惠券',
                'coupons_value' => '32.99',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2017-05-15 14:46:54',
                'modify_time' => '2017-05-15 14:46:54',
            ),
            21 => 
            array (
                'id' => 311,
                'category_id' => 100180,
                'category_code' => '0101005',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '广州6元现金劵',
                'coupons_value' => '6.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-18 11:06:57',
                'modify_time' => '2017-05-18 11:06:57',
            ),
            22 => 
            array (
                'id' => 312,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳10元现金劵',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-18 11:09:01',
                'modify_time' => '2017-07-27 10:05:51',
            ),
            23 => 
            array (
                'id' => 313,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳8元现金劵',
                'coupons_value' => '8.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-18 11:10:51',
                'modify_time' => '2017-07-27 10:05:38',
            ),
            24 => 
            array (
                'id' => 314,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'invite_friend_c',
                'name' => '10元邀请码好友赠送',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2017-05-23 14:46:10',
                'modify_time' => '2017-05-23 14:46:10',
            ),
            25 => 
            array (
                'id' => 315,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'invite_code_c',
                'name' => '10元邀请码好友赠送',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-05-23 14:47:49',
                'modify_time' => '2017-05-23 14:47:49',
            ),
            26 => 
            array (
                'id' => 316,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '6折劵',
                'coupons_value' => '6.00',
                'type' => 2,
                'max_fee' => '200.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-06-30 15:22:35',
                'modify_time' => '2017-06-30 15:22:35',
            ),
            27 => 
            array (
                'id' => 317,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '6折',
                'coupons_value' => '6.00',
                'type' => 2,
                'max_fee' => '100.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-06-30 15:27:26',
                'modify_time' => '2017-06-30 15:27:26',
            ),
            28 => 
            array (
                'id' => 318,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '6折抵扣30',
                'coupons_value' => '6.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-06-30 16:40:17',
                'modify_time' => '2017-06-30 16:40:17',
            ),
            29 => 
            array (
                'id' => 319,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '9折优惠劵',
                'coupons_value' => '9.00',
                'type' => 2,
                'max_fee' => '25.00',
                'valid_days' => 2,
                'status' => 1,
                'create_time' => '2017-07-31 17:33:11',
                'modify_time' => '2017-07-31 17:33:11',
            ),
            30 => 
            array (
                'id' => 320,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '75折优惠劵',
                'coupons_value' => '7.50',
                'type' => 2,
                'max_fee' => '25.00',
                'valid_days' => 3,
                'status' => 1,
                'create_time' => '2017-07-31 17:38:43',
                'modify_time' => '2017-07-31 17:38:43',
            ),
            31 => 
            array (
                'id' => 321,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '30优惠劵',
                'coupons_value' => '30.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 3,
                'status' => 1,
                'create_time' => '2017-08-03 09:54:29',
                'modify_time' => '2017-08-03 09:54:29',
            ),
            32 => 
            array (
                'id' => 322,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => '',
                'name' => '6折',
                'coupons_value' => '6.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2017-08-09 12:08:27',
                'modify_time' => '2017-08-09 12:08:27',
            ),
            33 => 
            array (
                'id' => 323,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => '',
                'name' => '85折扣券',
                'coupons_value' => '8.50',
                'type' => 2,
                'max_fee' => '20.00',
                'valid_days' => 365,
                'status' => 1,
                'create_time' => '2017-08-09 12:09:15',
                'modify_time' => '2017-08-09 12:09:15',
            ),
            34 => 
            array (
                'id' => 324,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => '',
                'name' => '9折优惠券',
                'coupons_value' => '9.00',
                'type' => 2,
                'max_fee' => '10.00',
                'valid_days' => 365,
                'status' => 1,
                'create_time' => '2017-08-09 12:09:47',
                'modify_time' => '2017-08-09 12:09:47',
            ),
            35 => 
            array (
                'id' => 325,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'day_first_order_end',
                'name' => '10元现金劵',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 3,
                'status' => 1,
                'create_time' => '2017-10-30 09:39:09',
                'modify_time' => '2017-10-31 10:44:13',
            ),
            36 => 
            array (
                'id' => 326,
                'category_id' => 100180,
                'category_code' => '0101005',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'day_first_order_end',
                'name' => '广州首单返优惠劵10块',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-10-30 11:06:09',
                'modify_time' => '2017-10-30 11:06:09',
            ),
            37 => 
            array (
                'id' => 327,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'day_first_order_end',
                'name' => '全国首单返优惠劵10块',
                'coupons_value' => '7.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 3,
                'status' => 1,
                'create_time' => '2017-10-30 15:09:07',
                'modify_time' => '2017-10-30 15:09:07',
            ),
            38 => 
            array (
                'id' => 328,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'client_register',
                'name' => '货主注册送劵5元',
                'coupons_value' => '5.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 2,
                'status' => 0,
                'create_time' => '2017-11-06 14:34:16',
                'modify_time' => '2017-12-04 15:18:28',
            ),
            39 => 
            array (
                'id' => 329,
                'category_id' => 100180,
                'category_code' => '0101005',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'client_register',
                'name' => '货主注册1折劵',
                'coupons_value' => '1.00',
                'type' => 2,
                'max_fee' => '5.00',
                'valid_days' => 1,
                'status' => 1,
                'create_time' => '2017-11-06 15:02:50',
                'modify_time' => '2017-11-06 15:02:50',
            ),
            40 => 
            array (
                'id' => 330,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'client_register',
                'name' => '货主注册送劵20元',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 7,
                'status' => 1,
                'create_time' => '2017-11-06 15:07:08',
                'modify_time' => '2017-12-04 15:18:19',
            ),
            41 => 
            array (
                'id' => 331,
                'category_id' => 100180,
                'category_code' => '0101005',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'client_register',
                'name' => '货主注册1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 7,
                'status' => 1,
                'create_time' => '2017-11-06 15:07:44',
                'modify_time' => '2017-11-06 15:07:44',
            ),
            42 => 
            array (
                'id' => 332,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'client_register',
                'name' => '注册送劵2元',
                'coupons_value' => '2.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-11-07 13:52:30',
                'modify_time' => '2017-11-07 13:52:30',
            ),
            43 => 
            array (
                'id' => 333,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳中型面包车1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-04 13:56:29',
                'modify_time' => '2017-12-13 11:02:11',
            ),
            44 => 
            array (
                'id' => 334,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 2,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳小型平板车1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-04 13:57:45',
                'modify_time' => '2017-12-13 11:02:05',
            ),
            45 => 
            array (
                'id' => 335,
                'category_id' => 100182,
                'category_code' => '0102006',
                'car_type_id' => 6,
                'call_type' => 0,
                'call_code' => '',
                'name' => '北京中型平板1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-04 13:58:32',
                'modify_time' => '2017-12-13 11:01:59',
            ),
            46 => 
            array (
                'id' => 336,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 7,
                'call_type' => 0,
                'call_code' => '',
                'name' => '江西小型箱货1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-04 13:59:24',
                'modify_time' => '2017-12-13 11:01:51',
            ),
            47 => 
            array (
                'id' => 337,
                'category_id' => 100180,
                'category_code' => '0101005',
                'car_type_id' => 8,
                'call_type' => 0,
                'call_code' => '',
                'name' => '广州大型箱货1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-04 14:00:23',
                'modify_time' => '2017-12-13 11:01:43',
            ),
            48 => 
            array (
                'id' => 338,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 10,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳冷链车1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-04 14:01:40',
                'modify_time' => '2017-12-13 11:01:32',
            ),
            49 => 
            array (
                'id' => 339,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 3,
                'call_code' => '007',
                'name' => '深圳通用车型1元劵',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-04 14:03:48',
                'modify_time' => '2017-12-08 18:04:39',
            ),
            50 => 
            array (
                'id' => 340,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 3,
                'call_code' => '001',
                'name' => '深圳中型面包车2元劵',
                'coupons_value' => '2.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 11,
                'status' => 1,
                'create_time' => '2017-12-04 14:22:57',
                'modify_time' => '2017-12-04 14:22:57',
            ),
            51 => 
            array (
                'id' => 341,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 2,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳市八五折优惠券',
                'coupons_value' => '8.50',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2017-12-11 16:19:53',
                'modify_time' => '2017-12-11 16:21:09',
            ),
            52 => 
            array (
                'id' => 342,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳测试车型优惠券',
                'coupons_value' => '8.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2017-12-21 10:42:30',
                'modify_time' => '2017-12-21 10:42:30',
            ),
            53 => 
            array (
                'id' => 343,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳市测试通用优惠券',
                'coupons_value' => '8.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2017-12-21 10:43:18',
                'modify_time' => '2017-12-21 10:43:18',
            ),
            54 => 
            array (
                'id' => 344,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 2,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳小型平板',
                'coupons_value' => '7.00',
                'type' => 2,
                'max_fee' => '20.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2017-12-26 09:55:11',
                'modify_time' => '2017-12-26 09:55:11',
            ),
            55 => 
            array (
                'id' => 345,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 3,
                'call_code' => '123123',
                'name' => '中型面板现金',
                'coupons_value' => '5.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 2,
                'status' => 1,
                'create_time' => '2017-12-26 09:57:37',
                'modify_time' => '2017-12-26 09:58:06',
            ),
            56 => 
            array (
                'id' => 346,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 6,
                'call_type' => 0,
                'call_code' => '',
                'name' => '6折优惠券',
                'coupons_value' => '6.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 7,
                'status' => 1,
                'create_time' => '2017-12-29 15:23:28',
                'modify_time' => '2017-12-29 15:23:28',
            ),
            57 => 
            array (
                'id' => 347,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '深圳5元优惠劵',
                'coupons_value' => '5.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2018-01-02 11:06:25',
                'modify_time' => '2018-01-02 11:06:25',
            ),
            58 => 
            array (
                'id' => 348,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 1,
                'call_type' => 0,
                'call_code' => '',
                'name' => '中国中型面包三折劵最高10元',
                'coupons_value' => '3.00',
                'type' => 2,
                'max_fee' => '10.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2018-01-02 11:07:13',
                'modify_time' => '2018-01-02 11:07:13',
            ),
            59 => 
            array (
                'id' => 349,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 1,
                'call_type' => 1,
                'call_code' => '',
                'name' => '套餐优惠劵1元',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2018-01-02 11:11:07',
                'modify_time' => '2018-01-02 11:11:07',
            ),
            60 => 
            array (
                'id' => 350,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 7,
                'call_type' => 1,
                'call_code' => '',
                'name' => '深圳套餐1折劵最高折扣10元',
                'coupons_value' => '1.00',
                'type' => 2,
                'max_fee' => '10.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2018-01-02 11:11:52',
                'modify_time' => '2018-01-02 11:11:52',
            ),
            61 => 
            array (
                'id' => 351,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 2,
                'call_type' => 1,
                'call_code' => '',
                'name' => '中改小',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 20,
                'status' => 1,
                'create_time' => '2018-01-02 16:16:00',
                'modify_time' => '2018-01-12 09:27:09',
            ),
            62 => 
            array (
                'id' => 352,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 7,
                'call_type' => 1,
                'call_code' => '',
                'name' => '通用改小箱货',
                'coupons_value' => '7.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 4,
                'status' => 1,
                'create_time' => '2018-01-03 11:40:13',
                'modify_time' => '2018-01-12 09:27:43',
            ),
            63 => 
            array (
                'id' => 353,
                'category_id' => 100180,
                'category_code' => '0101005',
                'car_type_id' => 1,
                'call_type' => 1,
                'call_code' => '',
                'name' => '广州券',
                'coupons_value' => '6.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 5,
                'status' => 1,
                'create_time' => '2018-01-03 11:41:17',
                'modify_time' => '2018-01-03 11:41:17',
            ),
            64 => 
            array (
                'id' => 354,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 0,
                'call_code' => '',
                'name' => '测试优惠券22',
                'coupons_value' => '5.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2018-01-09 14:37:19',
                'modify_time' => '2018-01-09 14:37:19',
            ),
            65 => 
            array (
                'id' => 355,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 2,
                'call_type' => 0,
                'call_code' => '',
                'name' => '小型平板1元',
                'coupons_value' => '1.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 7,
                'status' => 1,
                'create_time' => '2018-01-09 16:12:44',
                'modify_time' => '2018-01-09 16:12:44',
            ),
            66 => 
            array (
                'id' => 356,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 8,
                'call_type' => 1,
                'call_code' => '',
                'name' => '充值10',
                'coupons_value' => '4.00',
                'type' => 2,
                'max_fee' => '21.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-01-10 14:45:48',
                'modify_time' => '2018-01-10 14:45:48',
            ),
            67 => 
            array (
                'id' => 357,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 6,
                'call_type' => 1,
                'call_code' => '',
                'name' => '充值中型平板',
                'coupons_value' => '7.00',
                'type' => 2,
                'max_fee' => '40.00',
                'valid_days' => 32,
                'status' => 1,
                'create_time' => '2018-01-10 14:46:48',
                'modify_time' => '2018-01-10 14:46:48',
            ),
            68 => 
            array (
                'id' => 358,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 2,
                'call_code' => 'client_register',
                'name' => '新用户优惠',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-02 17:09:43',
                'modify_time' => '2018-04-02 17:09:43',
            ),
            69 => 
            array (
                'id' => 359,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '桂花糕',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 3,
                'status' => 1,
                'create_time' => '2018-04-16 09:30:46',
                'modify_time' => '2018-04-16 09:39:27',
            ),
            70 => 
            array (
                'id' => 360,
                'category_id' => 100182,
                'category_code' => '0102006',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '折扣券',
                'coupons_value' => '9.50',
                'type' => 2,
                'max_fee' => '5.00',
                'valid_days' => 1,
                'status' => 0,
                'create_time' => '2018-04-16 09:34:21',
                'modify_time' => '2018-04-16 09:40:11',
            ),
            71 => 
            array (
                'id' => 361,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 1,
                'call_type' => 1,
                'call_code' => '',
                'name' => '20元现金券',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2018-04-16 09:37:44',
                'modify_time' => '2018-04-16 09:39:59',
            ),
            72 => 
            array (
                'id' => 362,
                'category_id' => 100193,
                'category_code' => '0104008',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '20元的优惠放送',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-16 16:15:07',
                'modify_time' => '2018-04-16 16:15:07',
            ),
            73 => 
            array (
                'id' => 363,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 2,
                'call_code' => 'invite_friend_c',
                'name' => '10元现金送',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 6,
                'status' => 1,
                'create_time' => '2018-04-16 16:17:13',
                'modify_time' => '2018-04-16 16:17:13',
            ),
            74 => 
            array (
                'id' => 364,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 1,
                'call_type' => 1,
                'call_code' => '',
                'name' => '全中国的优惠券',
                'coupons_value' => '10.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-25 15:19:56',
                'modify_time' => '2018-04-25 15:19:56',
            ),
            75 => 
            array (
                'id' => 365,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '中国优惠券',
                'coupons_value' => '5.00',
                'type' => 2,
                'max_fee' => '30.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-25 15:20:46',
                'modify_time' => '2018-04-25 15:20:46',
            ),
            76 => 
            array (
                'id' => 366,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 0,
                'call_code' => '',
                'name' => '18元优惠券',
                'coupons_value' => '18.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 9,
                'status' => 1,
                'create_time' => '2018-04-27 16:26:41',
                'modify_time' => '2018-04-27 16:26:41',
            ),
            77 => 
            array (
                'id' => 367,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => '',
                'name' => '188优惠券',
                'coupons_value' => '188.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 9,
                'status' => 1,
                'create_time' => '2018-04-27 16:28:11',
                'modify_time' => '2018-04-27 16:28:11',
            ),
            78 => 
            array (
                'id' => 368,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 0,
                'call_type' => 3,
                'call_code' => '110',
                'name' => '全国通用',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-28 14:43:37',
                'modify_time' => '2018-04-28 14:43:37',
            ),
            79 => 
            array (
                'id' => 369,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 0,
                'call_type' => 3,
                'call_code' => '妹纸',
                'name' => '广东省口令',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-28 14:45:59',
                'modify_time' => '2018-04-28 14:45:59',
            ),
            80 => 
            array (
                'id' => 370,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 3,
                'call_code' => '321',
                'name' => '口令口令',
                'coupons_value' => '60.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-28 14:51:01',
                'modify_time' => '2018-04-28 14:51:01',
            ),
            81 => 
            array (
                'id' => 371,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 1,
                'call_type' => 3,
                'call_code' => '方舟来拉',
                'name' => '全国口令',
                'coupons_value' => '40.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-28 15:26:14',
                'modify_time' => '2018-04-28 15:26:14',
            ),
            82 => 
            array (
                'id' => 372,
                'category_id' => 100181,
                'category_code' => '0102',
                'car_type_id' => 1,
                'call_type' => 3,
                'call_code' => '北京口令',
                'name' => '北京口令',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-04-28 15:51:01',
                'modify_time' => '2018-04-28 15:51:07',
            ),
            83 => 
            array (
                'id' => 373,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 0,
                'call_type' => 1,
                'call_code' => '',
                'name' => '广东省优惠券',
                'coupons_value' => '8.00',
                'type' => 2,
                'max_fee' => '10.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2018-04-28 16:34:03',
                'modify_time' => '2018-04-28 16:34:03',
            ),
            84 => 
            array (
                'id' => 374,
                'category_id' => 100193,
                'category_code' => '0104008',
                'car_type_id' => 1,
                'call_type' => 0,
                'call_code' => '',
                'name' => '武汉测试',
                'coupons_value' => '7.00',
                'type' => 2,
                'max_fee' => '25.00',
                'valid_days' => 365,
                'status' => 1,
                'create_time' => '2018-06-06 09:55:42',
                'modify_time' => '2018-06-06 09:55:42',
            ),
            85 => 
            array (
                'id' => 375,
                'category_id' => 100187,
                'category_code' => '0103007',
                'car_type_id' => 0,
                'call_type' => 4,
                'call_code' => '',
                'name' => '舟到系统',
                'coupons_value' => '234.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 0,
                'status' => 1,
                'create_time' => '2018-08-30 17:57:41',
                'modify_time' => '2018-08-30 17:57:41',
            ),
            86 => 
            array (
                'id' => 376,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 4,
                'call_code' => '',
                'name' => '阿加',
                'coupons_value' => '50.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 10,
                'status' => 1,
                'create_time' => '2018-08-31 14:56:27',
                'modify_time' => '2018-08-31 15:26:28',
            ),
            87 => 
            array (
                'id' => 377,
                'category_id' => 5,
                'category_code' => '0101',
                'car_type_id' => 1,
                'call_type' => 4,
                'call_code' => '',
                'name' => '广东省兑换券',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 3,
                'status' => 1,
                'create_time' => '2018-08-31 15:05:43',
                'modify_time' => '2018-08-31 15:05:43',
            ),
            88 => 
            array (
                'id' => 378,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 0,
                'call_type' => 4,
                'call_code' => '',
                'name' => '商品测试优惠劵',
                'coupons_value' => '20.00',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 90,
                'status' => 1,
                'create_time' => '2018-09-12 16:08:18',
                'modify_time' => '2018-09-12 16:08:57',
            ),
            89 => 
            array (
                'id' => 379,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 0,
                'call_type' => 4,
                'call_code' => '',
                'name' => '碳币兑换',
                'coupons_value' => '9.50',
                'type' => 2,
                'max_fee' => '10.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2018-09-15 11:27:00',
                'modify_time' => '2018-09-15 11:27:00',
            ),
            90 => 
            array (
                'id' => 380,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 1,
                'call_type' => 4,
                'call_code' => '',
                'name' => '9折优惠劵',
                'coupons_value' => '9.00',
                'type' => 2,
                'max_fee' => '10.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2018-09-15 14:36:48',
                'modify_time' => '2018-09-15 15:33:11',
            ),
            91 => 
            array (
                'id' => 381,
                'category_id' => 1,
                'category_code' => '01',
                'car_type_id' => 1,
                'call_type' => 0,
                'call_code' => '',
                'name' => '815优惠券',
                'coupons_value' => '8.15',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 30,
                'status' => 1,
                'create_time' => '2018-09-21 11:05:35',
                'modify_time' => '2018-09-21 11:05:35',
            ),
            92 => 
            array (
                'id' => 382,
                'category_id' => 6,
                'category_code' => '0101002',
                'car_type_id' => 1,
                'call_type' => 0,
                'call_code' => '',
                'name' => '测试',
                'coupons_value' => '8.55',
                'type' => 1,
                'max_fee' => '0.00',
                'valid_days' => 3,
                'status' => 1,
                'create_time' => '2018-09-21 12:03:06',
                'modify_time' => '2018-09-21 12:03:06',
            ),
        ));
        
        
    }
}