<?php

use Illuminate\Database\Seeder;

class SysCarRuleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sys_car_rule')->delete();
        
        \DB::table('sys_car_rule')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'name' => 'index/index',
                'title' => '首页',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 0,
                'level' => 1,
                'create_time' => '2017-02-27 10:21:32',
                'modify_time' => '2017-02-27 10:21:34',
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 0,
                'name' => 'auth',
                'title' => '权限管理',
                'islink' => 1,
                'isadmin' => 1,
                'sort' => 254,
                'level' => 1,
                'create_time' => '2017-02-27 10:25:13',
                'modify_time' => '2017-02-27 10:25:15',
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 2,
                'name' => 'department/index',
                'title' => '角色管理',
                'islink' => 1,
                'isadmin' => 1,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-02-27 10:25:48',
                'modify_time' => '2017-02-27 10:25:49',
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 3,
                'name' => 'department/add',
                'title' => '添加角色',
                'islink' => 0,
                'isadmin' => 1,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-02-27 10:26:31',
                'modify_time' => '2017-02-27 10:26:34',
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => 3,
                'name' => 'department/edit',
                'title' => '编辑角色',
                'islink' => 0,
                'isadmin' => 1,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-02-27 10:26:58',
                'modify_time' => '2017-02-27 10:27:00',
            ),
            5 => 
            array (
                'id' => 6,
                'parent_id' => 2,
                'name' => 'user/index',
                'title' => '用户管理',
                'islink' => 1,
                'isadmin' => 1,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-02-27 16:30:50',
                'modify_time' => '2017-02-27 16:30:57',
            ),
            6 => 
            array (
                'id' => 7,
                'parent_id' => 6,
                'name' => 'user/add',
                'title' => '添加用户',
                'islink' => 0,
                'isadmin' => 1,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-02-27 16:31:30',
                'modify_time' => '2017-02-27 16:31:32',
            ),
            7 => 
            array (
                'id' => 8,
                'parent_id' => 6,
                'name' => 'user/edit',
                'title' => '编辑用户',
                'islink' => 0,
                'isadmin' => 1,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-02-27 16:31:57',
                'modify_time' => '2017-02-27 16:32:01',
            ),
            8 => 
            array (
                'id' => 9,
                'parent_id' => 0,
                'name' => 'car',
                'title' => '车辆管理',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 2,
                'level' => 1,
                'create_time' => '2017-02-28 09:51:21',
                'modify_time' => '2017-02-28 09:51:23',
            ),
            9 => 
            array (
                'id' => 10,
                'parent_id' => 9,
                'name' => 'car/index',
                'title' => '车辆列表',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-02-28 09:51:44',
                'modify_time' => '2017-02-28 09:51:46',
            ),
            10 => 
            array (
                'id' => 11,
                'parent_id' => 0,
                'name' => 'profile',
                'title' => '个人中心',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 1,
                'create_time' => '2017-02-28 11:32:03',
                'modify_time' => '2017-02-28 11:32:05',
            ),
            11 => 
            array (
                'id' => 12,
                'parent_id' => 11,
                'name' => 'profile/index',
                'title' => '我的资料',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-02-28 11:32:30',
                'modify_time' => '2017-02-28 11:32:33',
            ),
            12 => 
            array (
                'id' => 13,
                'parent_id' => 11,
                'name' => 'message/index',
                'title' => '消息中心',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-02-28 12:07:24',
                'modify_time' => '2017-02-28 12:07:27',
            ),
            13 => 
            array (
                'id' => 14,
                'parent_id' => 13,
                'name' => 'message/add',
                'title' => '添加消息',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-02-28 17:02:25',
                'modify_time' => '2017-02-28 17:02:28',
            ),
            14 => 
            array (
                'id' => 15,
                'parent_id' => 13,
                'name' => 'message/delete',
                'title' => '删除消息',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-02 15:34:42',
                'modify_time' => '2017-03-02 15:34:44',
            ),
            15 => 
            array (
                'id' => 16,
                'parent_id' => 13,
                'name' => 'message/read',
                'title' => '阅读消息',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-02 17:56:41',
                'modify_time' => '2017-03-02 17:56:44',
            ),
            16 => 
            array (
                'id' => 17,
                'parent_id' => 0,
                'name' => 'train',
                'title' => '车务管理',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 3,
                'level' => 1,
                'create_time' => '2017-03-03 09:17:22',
                'modify_time' => '2017-03-03 09:17:24',
            ),
            17 => 
            array (
                'id' => 18,
                'parent_id' => 17,
                'name' => 'safe/index',
                'title' => '保险管理',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 2,
                'level' => 2,
                'create_time' => '2017-03-03 09:17:58',
                'modify_time' => '2017-03-03 09:18:00',
            ),
            18 => 
            array (
                'id' => 19,
                'parent_id' => 13,
                'name' => 'message/detail',
                'title' => '消息详情',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-03 17:21:52',
                'modify_time' => '2017-03-03 17:21:54',
            ),
            19 => 
            array (
                'id' => 20,
                'parent_id' => 18,
                'name' => 'safe/add',
                'title' => '保险添加',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:13:00',
                'modify_time' => '2017-03-04 10:13:01',
            ),
            20 => 
            array (
                'id' => 21,
                'parent_id' => 18,
                'name' => 'safe/edit',
                'title' => '修改保险',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:13:44',
                'modify_time' => '2017-03-04 10:13:45',
            ),
            21 => 
            array (
                'id' => 22,
                'parent_id' => 17,
                'name' => 'peccancy/index',
                'title' => '违章管理',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 3,
                'level' => 2,
                'create_time' => '2017-03-04 10:12:18',
                'modify_time' => '2017-03-04 10:12:20',
            ),
            22 => 
            array (
                'id' => 23,
                'parent_id' => 22,
                'name' => 'peccancy/add',
                'title' => '违章添加',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:14:50',
                'modify_time' => '2017-03-04 10:14:51',
            ),
            23 => 
            array (
                'id' => 24,
                'parent_id' => 22,
                'name' => 'peccancy/edit',
                'title' => '违章修改',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:15:12',
                'modify_time' => '2017-03-04 10:15:14',
            ),
            24 => 
            array (
                'id' => 25,
                'parent_id' => 17,
                'name' => 'service/index',
                'title' => '维修管理',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-03-04 15:43:26',
                'modify_time' => '2017-03-04 15:43:29',
            ),
            25 => 
            array (
                'id' => 26,
                'parent_id' => 0,
                'name' => 'driver',
                'title' => '司机管理',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 4,
                'level' => 1,
                'create_time' => '2017-03-04 16:30:20',
                'modify_time' => '2017-03-04 16:30:23',
            ),
            26 => 
            array (
                'id' => 27,
                'parent_id' => 26,
                'name' => 'driver/index',
                'title' => '待审核司机',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 254,
                'level' => 2,
                'create_time' => '2017-03-04 16:32:54',
                'modify_time' => '2017-03-04 16:32:57',
            ),
            27 => 
            array (
                'id' => 28,
                'parent_id' => 26,
                'name' => 'driver/checked',
                'title' => '已审核司机',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-03-04 16:33:31',
                'modify_time' => '2017-03-04 16:33:29',
            ),
            28 => 
            array (
                'id' => 29,
                'parent_id' => 26,
                'name' => 'driver/logs',
                'title' => '审核记录',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 256,
                'level' => 2,
                'create_time' => '2017-03-04 16:34:39',
                'modify_time' => '2017-03-04 16:34:44',
            ),
            29 => 
            array (
                'id' => 30,
                'parent_id' => 17,
                'name' => 'maintain/index',
                'title' => '保养管理',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 4,
                'level' => 2,
                'create_time' => '2017-03-06 14:01:21',
                'modify_time' => '2017-03-06 14:01:23',
            ),
            30 => 
            array (
                'id' => 31,
                'parent_id' => 28,
                'name' => 'driver/detail',
                'title' => '司机详情',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 11:12:24',
                'modify_time' => '2017-03-07 11:12:26',
            ),
            31 => 
            array (
                'id' => 32,
                'parent_id' => 28,
                'name' => 'driver/edit',
                'title' => '编辑司机',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 11:13:12',
                'modify_time' => '2017-03-07 11:13:10',
            ),
            32 => 
            array (
                'id' => 33,
                'parent_id' => 10,
                'name' => 'car/unbind',
                'title' => '解绑司机',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:00:37',
                'modify_time' => '2017-03-07 16:00:39',
            ),
            33 => 
            array (
                'id' => 34,
                'parent_id' => 10,
                'name' => 'car/bind',
                'title' => '绑定司机',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:01:00',
                'modify_time' => '2017-03-07 16:01:02',
            ),
            34 => 
            array (
                'id' => 35,
                'parent_id' => 25,
                'name' => 'service/add',
                'title' => '添加维修',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:01:46',
                'modify_time' => '2017-03-07 16:01:48',
            ),
            35 => 
            array (
                'id' => 36,
                'parent_id' => 25,
                'name' => 'service/edit',
                'title' => '修改维修',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:02:06',
                'modify_time' => '2017-03-07 16:02:08',
            ),
            36 => 
            array (
                'id' => 37,
                'parent_id' => 30,
                'name' => 'maintain/add',
                'title' => '保养添加',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:02:42',
                'modify_time' => '2017-03-07 16:02:44',
            ),
            37 => 
            array (
                'id' => 38,
                'parent_id' => 30,
                'name' => 'maintain/edit',
                'title' => '修改保养',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:03:23',
                'modify_time' => '2017-03-07 16:03:25',
            ),
            38 => 
            array (
                'id' => 39,
                'parent_id' => 30,
                'name' => 'maintain/remind',
                'title' => '保养提醒',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:04:11',
                'modify_time' => '2017-03-07 16:04:13',
            ),
            39 => 
            array (
                'id' => 40,
                'parent_id' => 30,
                'name' => 'maintain/addRemind',
                'title' => '添加提醒',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:04:35',
                'modify_time' => '2017-03-07 16:04:37',
            ),
            40 => 
            array (
                'id' => 41,
                'parent_id' => 30,
                'name' => 'maintain/editRemind',
                'title' => '修改提醒',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-07 16:04:56',
                'modify_time' => '2017-03-07 16:04:57',
            ),
            41 => 
            array (
                'id' => 43,
                'parent_id' => 10,
                'name' => 'car/add',
                'title' => '添加车辆',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 0,
                'level' => 3,
                'create_time' => '2017-03-07 16:00:37',
                'modify_time' => '2017-03-07 16:00:39',
            ),
            42 => 
            array (
                'id' => 44,
                'parent_id' => 10,
                'name' => 'car/edit',
                'title' => '编辑车辆',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 1,
                'level' => 3,
                'create_time' => '2017-03-07 16:01:00',
                'modify_time' => '2017-03-07 16:01:02',
            ),
            43 => 
            array (
                'id' => 45,
                'parent_id' => 22,
                'name' => 'peccancy/update',
                'title' => '违章导入',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:15:12',
                'modify_time' => '2017-03-04 10:15:14',
            ),
            44 => 
            array (
                'id' => 46,
                'parent_id' => 18,
                'name' => 'safe/update',
                'title' => '保险导入',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:15:12',
                'modify_time' => '2017-03-04 10:15:14',
            ),
            45 => 
            array (
                'id' => 47,
                'parent_id' => 30,
                'name' => 'maintain/update',
                'title' => '保养导入',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:15:12',
                'modify_time' => '2017-03-04 10:15:14',
            ),
            46 => 
            array (
                'id' => 48,
                'parent_id' => 25,
                'name' => 'service/update',
                'title' => '维修导入',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:15:12',
                'modify_time' => '2017-03-04 10:15:14',
            ),
            47 => 
            array (
                'id' => 49,
                'parent_id' => 10,
                'name' => 'car/update',
                'title' => '车辆导入',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-04 10:15:12',
                'modify_time' => '2017-03-04 10:15:14',
            ),
            48 => 
            array (
                'id' => 50,
                'parent_id' => 0,
                'name' => 'base',
                'title' => '基础数据',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 1,
                'create_time' => '2017-03-17 08:00:58',
                'modify_time' => '2017-03-17 08:01:00',
            ),
            49 => 
            array (
                'id' => 51,
                'parent_id' => 50,
                'name' => 'carsafe/index',
                'title' => '保险公司',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-03-17 08:01:30',
                'modify_time' => '2017-03-17 08:01:32',
            ),
            50 => 
            array (
                'id' => 52,
                'parent_id' => 50,
                'name' => 'carsafe/add',
                'title' => '添加保险公司',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-17 16:21:12',
                'modify_time' => '2017-03-17 16:21:14',
            ),
            51 => 
            array (
                'id' => 53,
                'parent_id' => 50,
                'name' => 'carsafe/edit',
                'title' => '修改保险公司',
                'islink' => 1,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-17 16:21:42',
                'modify_time' => '2017-03-17 16:21:45',
            ),
            52 => 
            array (
                'id' => 54,
                'parent_id' => 10,
                'name' => 'car/show',
                'title' => '查看车辆',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 2,
                'create_time' => '2017-03-22 09:37:27',
                'modify_time' => '2017-03-22 09:37:29',
            ),
            53 => 
            array (
                'id' => 57,
                'parent_id' => 30,
                'name' => 'maintain/deleteRemind',
                'title' => '删除保养提醒',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-20 16:59:00',
                'modify_time' => '2017-03-20 16:59:03',
            ),
            54 => 
            array (
                'id' => 58,
                'parent_id' => 30,
                'name' => 'maintain/destroy',
                'title' => '删除保养',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-20 17:00:22',
                'modify_time' => '2017-03-20 17:00:24',
            ),
            55 => 
            array (
                'id' => 59,
                'parent_id' => 18,
                'name' => 'safe/destroy',
                'title' => '删除保险',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-20 17:37:48',
                'modify_time' => '2017-03-20 17:37:50',
            ),
            56 => 
            array (
                'id' => 60,
                'parent_id' => 22,
                'name' => 'peccancy/destroy',
                'title' => '删除违章',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-20 17:50:13',
                'modify_time' => '2017-03-20 17:50:15',
            ),
            57 => 
            array (
                'id' => 61,
                'parent_id' => 10,
                'name' => 'car/download',
                'title' => '车辆导出',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:51:16',
                'modify_time' => '2017-03-22 17:51:18',
            ),
            58 => 
            array (
                'id' => 62,
                'parent_id' => 18,
                'name' => 'safe/download',
                'title' => '保险导出',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:52:03',
                'modify_time' => '2017-03-22 17:52:04',
            ),
            59 => 
            array (
                'id' => 63,
                'parent_id' => 22,
                'name' => 'peccancy/download',
                'title' => '违章导出',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:52:47',
                'modify_time' => '2017-03-22 17:52:49',
            ),
            60 => 
            array (
                'id' => 64,
                'parent_id' => 30,
                'name' => 'maintain/download',
                'title' => '保养导出',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:53:39',
                'modify_time' => '2017-03-22 17:53:41',
            ),
            61 => 
            array (
                'id' => 65,
                'parent_id' => 25,
                'name' => 'service/download',
                'title' => '维修导出',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:54:16',
                'modify_time' => '2017-03-22 17:54:18',
            ),
            62 => 
            array (
                'id' => 66,
                'parent_id' => 10,
                'name' => 'car/xls',
                'title' => '车辆模板下载',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:51:16',
                'modify_time' => '2017-03-22 17:51:18',
            ),
            63 => 
            array (
                'id' => 67,
                'parent_id' => 18,
                'name' => 'safe/xls',
                'title' => '保险模板下载',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:52:03',
                'modify_time' => '2017-03-22 17:52:04',
            ),
            64 => 
            array (
                'id' => 68,
                'parent_id' => 22,
                'name' => 'peccancy/xls',
                'title' => '违章模板下载',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:52:47',
                'modify_time' => '2017-03-22 17:52:49',
            ),
            65 => 
            array (
                'id' => 69,
                'parent_id' => 30,
                'name' => 'maintain/xls',
                'title' => '保养模板下载',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:53:39',
                'modify_time' => '2017-03-22 17:53:41',
            ),
            66 => 
            array (
                'id' => 70,
                'parent_id' => 25,
                'name' => 'service/xls',
                'title' => '维修模板下载',
                'islink' => 0,
                'isadmin' => 0,
                'sort' => 255,
                'level' => 3,
                'create_time' => '2017-03-22 17:54:16',
                'modify_time' => '2017-03-22 17:54:18',
            ),
        ));
        
        
    }
}