<?php

use Illuminate\Database\Seeder;

class ZdMerchantTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('zd_merchant')->delete();
        
        \DB::table('zd_merchant')->insert(array (
            0 => 
            array (
                'id' => 101,
                'quality_id' => 2,
                'advice_id' => 3,
                'running_id' => 0,
                'user_id' => 2,
                'title' => '深圳市方舟货的有限公司',
                'short_name' => '方舟货的',
                'city' => '深圳',
                'trade' => '货运物流',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2017-11-09',
                'agreement_end_time' => '2018-11-09',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 25,
                'sop' => 1,
                'content' => '{"contacts":"李总","contacts_phone":"13510256663","back_phone":"","address":""}',
                'task_count' => 40,
                'unless_task_count' => 0,
                'warehouse_count' => 3,
                'contract_count' => 0,
                'create_time' => '2017-11-09 16:06:57',
                'modify_time' => '2018-09-17 10:30:37',
            ),
            1 => 
            array (
                'id' => 102,
                'quality_id' => 4,
                'advice_id' => 3,
                'running_id' => 0,
                'user_id' => 1,
                'title' => '南山方舟舟到测试',
                'short_name' => '方舟舟到测试',
                'city' => '深圳',
                'trade' => '互联网',
                'bank' => '中行',
                'bank_no' => '563434343463456546453435',
                'telephone' => '075583898652',
                'agreement_start_time' => '2017-11-16',
                'agreement_end_time' => '2017-11-30',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 50,
                'sop' => 1,
                'content' => '{"contacts":"测试","contacts_phone":"13682509527","back_phone":"","address":""}',
                'task_count' => 49,
                'unless_task_count' => 0,
                'warehouse_count' => 6,
                'contract_count' => 0,
                'create_time' => '2017-11-16 10:26:22',
                'modify_time' => '2018-09-26 17:14:23',
            ),
            2 => 
            array (
                'id' => 103,
                'quality_id' => 4,
                'advice_id' => 10,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '银捷',
                'short_name' => '银捷',
                'city' => '深圳市',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-03-11',
                'agreement_end_time' => '2021-12-17',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 33,
                'sop' => 1,
                'content' => '{"contacts":"林鹏（仓库经理）","contacts_phone":"13410000000","back_phone":"","address":"深圳市龙华新区新区大道鹏华工业园-中商惠民仓库"}',
                'task_count' => 4,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2017-12-11 16:10:59',
                'modify_time' => '2018-07-09 15:15:18',
            ),
            3 => 
            array (
                'id' => 104,
                'quality_id' => 4,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 4,
                'title' => '交互经理创建',
                'short_name' => '交经建',
                'city' => '深圳市',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2017-12-12',
                'agreement_end_time' => '2017-12-17',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 22,
                'sop' => 1,
                'content' => '{"contacts":"122","contacts_phone":"13420000000","back_phone":"","address":""}',
                'task_count' => 2,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2017-12-12 11:51:57',
                'modify_time' => '2018-09-14 11:45:25',
            ),
            4 => 
            array (
                'id' => 105,
                'quality_id' => 2,
                'advice_id' => 10,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '排线测试商户全称',
                'short_name' => '排线测试商户简称',
                'city' => '深圳市',
                'trade' => '1',
                'bank' => '平安银行',
                'bank_no' => '13153415456465453415341354354',
                'telephone' => '075583565984',
                'agreement_start_time' => '2017-12-15',
                'agreement_end_time' => '2017-12-16',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 31,
                'sop' => 1,
                'content' => '{"contacts":"测试","contacts_phone":"18900000000","back_phone":"","address":""}',
                'task_count' => 8,
                'unless_task_count' => 0,
                'warehouse_count' => 2,
                'contract_count' => 0,
                'create_time' => '2017-12-15 14:37:36',
                'modify_time' => '2018-07-07 11:50:39',
            ),
            5 => 
            array (
                'id' => 106,
                'quality_id' => 2,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '你在说什么？我眼睛小听不清',
                'short_name' => '我眼睛小听不清',
                'city' => '北京',
                'trade' => '互联网',
                'bank' => '平安',
                'bank_no' => '7484645433131657876435435435',
                'telephone' => '075586593589',
                'agreement_start_time' => '2017-12-19',
                'agreement_end_time' => '2018-03-28',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 31,
                'sop' => 1,
                'content' => '{"contacts":"1234","contacts_phone":"13655556666","back_phone":"","address":""}',
                'task_count' => 3,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2017-12-19 14:00:54',
                'modify_time' => '2018-09-17 11:27:43',
            ),
            6 => 
            array (
                'id' => 107,
                'quality_id' => 4,
                'advice_id' => 11,
                'running_id' => 7,
                'user_id' => 4,
                'title' => '小小超人',
                'short_name' => '小超人',
                'city' => '深圳市',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2017-12-12',
                'agreement_end_time' => '2017-12-19',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 22,
                'sop' => 1,
                'content' => '{"contacts":"打的费","contacts_phone":"13000000000","back_phone":"","address":""}',
                'task_count' => 1,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2017-12-19 14:06:16',
                'modify_time' => '2018-09-17 11:24:28',
            ),
            7 => 
            array (
                'id' => 108,
                'quality_id' => 4,
                'advice_id' => 10,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '深圳方舟货的有限公司',
                'short_name' => '方舟测试天天',
                'city' => '深圳',
                'trade' => '电子',
                'bank' => '招商银行',
                'bank_no' => '66666666666666',
                'telephone' => '0755-58996555',
                'agreement_start_time' => '2018-08-04',
                'agreement_end_time' => '2018-11-30',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"田甜","contacts_phone":"15572595825","back_phone":"13100100000","address":"深圳南山"}',
                'task_count' => 94,
                'unless_task_count' => 3,
                'warehouse_count' => 7,
                'contract_count' => 0,
                'create_time' => '2018-07-04 12:59:28',
                'modify_time' => '2018-09-14 16:59:53',
            ),
            8 => 
            array (
                'id' => 109,
                'quality_id' => 4,
                'advice_id' => 10,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '周到小测试',
                'short_name' => '周测',
                'city' => '深圳市',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-09-04',
                'agreement_end_time' => '2018-11-15',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 20,
                'sop' => 1,
                'content' => '{"contacts":"大房东","contacts_phone":"13410000000","back_phone":"","address":""}',
                'task_count' => 46,
                'unless_task_count' => 1,
                'warehouse_count' => 4,
                'contract_count' => 0,
                'create_time' => '2018-07-04 15:49:21',
                'modify_time' => '2018-09-05 09:51:05',
            ),
            9 => 
            array (
                'id' => 110,
                'quality_id' => 1,
                'advice_id' => 10,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '深圳方舟货的有限公司',
                'short_name' => '测试天天',
                'city' => '深圳',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-05',
                'agreement_end_time' => '2018-09-05',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"测试2","contacts_phone":"13802201671","back_phone":"","address":""}',
                'task_count' => 24,
                'unless_task_count' => 0,
                'warehouse_count' => 6,
                'contract_count' => 0,
                'create_time' => '2018-07-05 09:24:29',
                'modify_time' => '2018-07-27 17:21:22',
            ),
            10 => 
            array (
                'id' => 111,
                'quality_id' => 4,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '林测试',
                'short_name' => '林测',
                'city' => '深圳市',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-05',
                'agreement_end_time' => '2019-01-15',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 20,
                'sop' => 1,
                'content' => '{"contacts":"三房东","contacts_phone":"13450000001","back_phone":"","address":""}',
                'task_count' => 38,
                'unless_task_count' => 0,
                'warehouse_count' => 4,
                'contract_count' => 0,
                'create_time' => '2018-07-05 10:02:33',
                'modify_time' => '2018-10-09 14:02:26',
            ),
            11 => 
            array (
                'id' => 112,
                'quality_id' => 1,
                'advice_id' => 3,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '开发商户',
                'short_name' => '开发商户',
                'city' => '深圳',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-17',
                'agreement_end_time' => '2018-07-19',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"则需想","contacts_phone":"13266522729","back_phone":"","address":""}',
                'task_count' => 15,
                'unless_task_count' => 0,
                'warehouse_count' => 7,
                'contract_count' => 0,
                'create_time' => '2018-07-06 14:53:49',
                'modify_time' => '2018-07-23 16:23:56',
            ),
            12 => 
            array (
                'id' => 113,
                'quality_id' => 9,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '验收测试商户账号',
                'short_name' => '测试商户',
                'city' => '深圳',
                'trade' => '共享单车',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-23',
                'agreement_end_time' => '2020-02-23',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"张三","contacts_phone":"13510525635","back_phone":"","address":""}',
                'task_count' => 57,
                'unless_task_count' => 0,
                'warehouse_count' => 5,
                'contract_count' => 0,
                'create_time' => '2018-07-23 09:56:09',
                'modify_time' => '2018-07-27 09:58:55',
            ),
            13 => 
            array (
                'id' => 114,
                'quality_id' => 2,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '美婷测试商户账号',
                'short_name' => '测试商户-美婷',
                'city' => '深圳',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-11-23',
                'agreement_end_time' => '2019-07-23',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"小美","contacts_phone":"13511111111","back_phone":"","address":""}',
                'task_count' => 3,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2018-07-23 10:45:40',
                'modify_time' => '2018-09-17 11:24:53',
            ),
            14 => 
            array (
                'id' => 115,
                'quality_id' => 2,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '书芳测试商户账号',
                'short_name' => '测试商户-书芳',
                'city' => '深圳',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-23',
                'agreement_end_time' => '2019-07-23',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"张三","contacts_phone":"13511111111","back_phone":"","address":""}',
                'task_count' => 17,
                'unless_task_count' => 0,
                'warehouse_count' => 4,
                'contract_count' => 0,
                'create_time' => '2018-07-23 11:52:34',
                'modify_time' => '2018-09-06 15:45:04',
            ),
            15 => 
            array (
                'id' => 116,
                'quality_id' => 2,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '测试密码',
                'short_name' => '测试商户',
                'city' => '深圳',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-23',
                'agreement_end_time' => '2018-07-24',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 25,
                'sop' => 1,
                'content' => '{"contacts":"张三","contacts_phone":"13511111111","back_phone":"","address":""}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-07-23 12:04:22',
                'modify_time' => '2018-07-23 12:04:22',
            ),
            16 => 
            array (
                'id' => 117,
                'quality_id' => 1,
                'advice_id' => 3,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '开发123',
                'short_name' => '开发',
                'city' => '深圳',
                'trade' => '1111',
                'bank' => '招商银行',
                'bank_no' => '6217002710000684874',
                'telephone' => '',
                'agreement_start_time' => '2018-07-09',
                'agreement_end_time' => '2018-11-26',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"曾祥浩","contacts_phone":"13266522726","back_phone":"13266522726","address":"11111"}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-07-23 12:12:15',
                'modify_time' => '2018-09-17 11:27:56',
            ),
            17 => 
            array (
                'id' => 120,
                'quality_id' => 1,
                'advice_id' => 3,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '开发234',
                'short_name' => '开发',
                'city' => '深圳',
                'trade' => '1111',
                'bank' => '招商银行',
                'bank_no' => '6217002710000684874',
                'telephone' => '',
                'agreement_start_time' => '2018-07-10',
                'agreement_end_time' => '2018-07-19',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"曾祥浩","contacts_phone":"13266522726","back_phone":"13266522726","address":"11111"}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2018-07-23 12:22:06',
                'modify_time' => '2018-07-23 16:13:34',
            ),
            18 => 
            array (
                'id' => 121,
                'quality_id' => 1,
                'advice_id' => 3,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '的方法11',
                'short_name' => '大时代',
                'city' => '深圳',
                'trade' => '123',
                'bank' => '招商',
                'bank_no' => '6225365271562822 ',
                'telephone' => '07635680873',
                'agreement_start_time' => '2018-07-23',
                'agreement_end_time' => '2018-07-26',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"大飞","contacts_phone":"13266522729","back_phone":"","address":""}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-07-23 13:56:51',
                'modify_time' => '2018-07-23 13:56:51',
            ),
            19 => 
            array (
                'id' => 129,
                'quality_id' => 1,
                'advice_id' => 3,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '华仔连锁烧烤',
                'short_name' => '华仔连锁烧烤',
                'city' => '深圳',
                'trade' => '食品',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-24',
                'agreement_end_time' => '2019-08-24',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 28,
                'sop' => 1,
                'content' => '{"contacts":"华仔","contacts_phone":"13537580621","back_phone":"","address":""}',
                'task_count' => 5,
                'unless_task_count' => 0,
                'warehouse_count' => 3,
                'contract_count' => 0,
                'create_time' => '2018-07-24 16:14:54',
                'modify_time' => '2018-09-17 11:29:35',
            ),
            20 => 
            array (
                'id' => 130,
                'quality_id' => 2,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '验证密码问题',
                'short_name' => '测试密码商户',
                'city' => '深圳',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-25',
                'agreement_end_time' => '2018-07-31',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"张三","contacts_phone":"13511111111","back_phone":"","address":""}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2018-07-25 11:24:52',
                'modify_time' => '2018-09-17 11:28:24',
            ),
            21 => 
            array (
                'id' => 131,
                'quality_id' => 2,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '测试红点出现问题',
                'short_name' => '测试红点出现问题',
                'city' => '深圳',
                'trade' => '',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-25',
                'agreement_end_time' => '2018-07-31',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"张三","contacts_phone":"13511111111","back_phone":"","address":""}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-07-25 12:10:41',
                'modify_time' => '2018-09-17 11:28:11',
            ),
            22 => 
            array (
                'id' => 132,
                'quality_id' => 2,
                'advice_id' => 6,
                'running_id' => 7,
                'user_id' => 1,
                'title' => '舟到测试商户',
                'short_name' => '测试商户-LUO',
                'city' => '深圳',
                'trade' => '城市货运',
                'bank' => '',
                'bank_no' => '',
                'telephone' => '',
                'agreement_start_time' => '2018-07-25',
                'agreement_end_time' => '2019-07-25',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"张三","contacts_phone":"13511111111","back_phone":"","address":""}',
                'task_count' => 3,
                'unless_task_count' => 0,
                'warehouse_count' => 1,
                'contract_count' => 0,
                'create_time' => '2018-07-25 15:23:32',
                'modify_time' => '2018-07-25 15:39:45',
            ),
            23 => 
            array (
                'id' => 133,
                'quality_id' => 16,
                'advice_id' => 17,
                'running_id' => 18,
                'user_id' => 1,
                'title' => '测试大佬',
                'short_name' => '测大',
                'city' => '6',
                'trade' => '',
                'bank' => NULL,
                'bank_no' => NULL,
                'telephone' => '',
                'agreement_start_time' => '2018-09-26',
                'agreement_end_time' => '2018-10-31',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 33,
                'sop' => 1,
                'content' => '{"contacts":"\\u8f85\\u5bfc\\u8d39","contacts_phone":"14242555555","address":"\\u53d1\\u987a\\u4e30"}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-09-26 16:11:15',
                'modify_time' => '2018-09-26 16:11:15',
            ),
            24 => 
            array (
                'id' => 134,
                'quality_id' => 16,
                'advice_id' => 17,
                'running_id' => 18,
                'user_id' => 1,
                'title' => '反对方答复',
                'short_name' => '大幅度',
                'city' => '6',
                'trade' => '',
                'bank' => NULL,
                'bank_no' => NULL,
                'telephone' => '',
                'agreement_start_time' => '2018-09-26',
                'agreement_end_time' => '2018-10-31',
                'invoice' => 0,
                'repayment' => 1,
                'repayment_day' => 54,
                'sop' => 1,
                'content' => '{"contacts":"\\u5730\\u65b9","contacts_phone":"13410111110","address":"\\u7684\\u8303\\u5fb7\\u8428\\u53d1"}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-09-26 16:50:53',
                'modify_time' => '2018-09-26 16:50:53',
            ),
            25 => 
            array (
                'id' => 135,
                'quality_id' => 16,
                'advice_id' => 17,
                'running_id' => 0,
                'user_id' => 1,
                'title' => '测试林',
                'short_name' => '测试林',
                'city' => '6',
                'trade' => '',
                'bank' => NULL,
                'bank_no' => NULL,
                'telephone' => '',
                'agreement_start_time' => '2018-09-26',
                'agreement_end_time' => '2018-10-31',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 12,
                'sop' => 1,
                'content' => '{"contacts":"\\u6d4b\\u8bd5\\u6797","contacts_phone":"13232323232","address":"\\u6d4b\\u8bd5\\u6797\\u6d4b\\u8bd5\\u6797"}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-09-26 16:51:01',
                'modify_time' => '2018-09-26 16:51:01',
            ),
            26 => 
            array (
                'id' => 136,
                'quality_id' => 1,
                'advice_id' => 17,
                'running_id' => 18,
                'user_id' => 1,
                'title' => '死神',
                'short_name' => '死神',
                'city' => '6',
                'trade' => '11111',
                'bank' => '开发',
                'bank_no' => NULL,
                'telephone' => '0763-5680872',
                'agreement_start_time' => '2018-09-12',
                'agreement_end_time' => '2018-10-24',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 30,
                'sop' => 1,
                'content' => '{"contacts":"\\u66fe\\u7965\\u6d69","contacts_phone":"13266522765","back_phone":"13266522700","address":"\\u6492\\u6253\\u53d1\\u70b9\\u662f\\u65af\\u8482\\u82ac"}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-09-26 16:59:11',
                'modify_time' => '2018-09-26 16:59:11',
            ),
            27 => 
            array (
                'id' => 137,
                'quality_id' => 16,
                'advice_id' => 17,
                'running_id' => 18,
                'user_id' => 1,
                'title' => '首单返',
                'short_name' => '地方',
                'city' => '6',
                'trade' => '',
                'bank' => NULL,
                'bank_no' => NULL,
                'telephone' => '',
                'agreement_start_time' => '2018-09-26',
                'agreement_end_time' => '2018-11-01',
                'invoice' => 1,
                'repayment' => 1,
                'repayment_day' => 45,
                'sop' => 1,
                'content' => '{"contacts":"\\u521a\\u53d1\\u7684","contacts_phone":"13412121212","address":"\\u80a1\\u4efd"}',
                'task_count' => 0,
                'unless_task_count' => 0,
                'warehouse_count' => 0,
                'contract_count' => 0,
                'create_time' => '2018-09-26 17:08:43',
                'modify_time' => '2018-09-26 17:08:43',
            ),
        ));
        
        
    }
}