<?php

use Illuminate\Database\Seeder;

class ZdSysRuleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('zd_sys_rule')->delete();
        
        \DB::table('zd_sys_rule')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'name' => 'setting',
                'title' => '系统管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-set',
                'sort' => 120,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 0,
                'create_time' => '2017-06-27 11:55:47',
                'modify_time' => '2017-10-13 14:47:23',
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 1,
                'name' => 'rule/index',
                'title' => '系统菜单',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 21,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-06-27 14:33:37',
                'modify_time' => '2017-06-27 14:33:37',
            ),
            2 => 
            array (
                'id' => 5,
                'parent_id' => 2,
                'name' => 'rule/add',
                'title' => '添加系统菜单',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 21,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-06-27 14:34:32',
                'modify_time' => '2017-06-27 14:34:32',
            ),
            3 => 
            array (
                'id' => 6,
                'parent_id' => 2,
                'name' => 'rule/edit',
                'title' => '修改系统菜单',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 11,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-06-27 14:36:50',
                'modify_time' => '2017-06-27 14:36:50',
            ),
            4 => 
            array (
                'id' => 7,
                'parent_id' => 1,
                'name' => 'role/index',
                'title' => '部门管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 12,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-06-27 14:56:50',
                'modify_time' => '2017-06-27 14:56:50',
            ),
            5 => 
            array (
                'id' => 8,
                'parent_id' => 7,
                'name' => 'role/add',
                'title' => '添加部门',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 22,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-06-27 14:57:45',
                'modify_time' => '2017-07-03 14:56:44',
            ),
            6 => 
            array (
                'id' => 9,
                'parent_id' => 7,
                'name' => 'role/edit',
                'title' => '编辑部门',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 50,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-06-27 14:59:14',
                'modify_time' => '2017-07-03 14:57:01',
            ),
            7 => 
            array (
                'id' => 10,
                'parent_id' => 1,
                'name' => 'user/index',
                'title' => '系统用户',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 1,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-03 11:48:23',
                'modify_time' => '2017-07-03 15:05:30',
            ),
            8 => 
            array (
                'id' => 11,
                'parent_id' => 10,
                'name' => 'user/add',
                'title' => '添加系统用户',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 5,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-03 11:52:08',
                'modify_time' => '2017-10-16 16:30:48',
            ),
            9 => 
            array (
                'id' => 12,
                'parent_id' => 10,
                'name' => 'user/edit',
                'title' => '编辑系统用户',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 5,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-03 11:53:07',
                'modify_time' => '2017-07-03 11:53:07',
            ),
            10 => 
            array (
                'id' => 13,
                'parent_id' => 0,
                'name' => 'index/index',
                'title' => '首页',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-shouye-shouye',
                'sort' => 0,
                'isverify' => 0,
                'level' => 1,
                'isclick' => 1,
                'create_time' => '2017-07-03 12:01:51',
                'modify_time' => '2017-07-03 12:01:53',
            ),
            11 => 
            array (
                'id' => 14,
                'parent_id' => 10,
                'name' => 'user/toggle',
                'title' => '切换用户状态',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 20,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-03 15:04:52',
                'modify_time' => '2017-07-03 15:05:08',
            ),
            12 => 
            array (
                'id' => 15,
                'parent_id' => 10,
                'name' => 'user/allot',
                'title' => '分配用户权限',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => 'icon',
                'sort' => 255,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-03 15:32:38',
                'modify_time' => '2017-07-03 15:32:38',
            ),
            13 => 
            array (
                'id' => 16,
                'parent_id' => 0,
                'name' => 'task',
                'title' => '发布线路任务',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-bianji',
                'sort' => 2,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 0,
                'create_time' => '2017-07-04 01:33:13',
                'modify_time' => '2017-09-18 15:21:06',
            ),
            14 => 
            array (
                'id' => 17,
                'parent_id' => 16,
                'name' => 'task/major',
                'title' => '招主司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 1,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-04 01:34:37',
                'modify_time' => '2017-07-04 01:34:37',
            ),
            15 => 
            array (
                'id' => 18,
                'parent_id' => 16,
                'name' => 'task/deputy',
                'title' => '招临时司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 2,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-04 01:35:25',
                'modify_time' => '2017-07-19 14:47:30',
            ),
            16 => 
            array (
                'id' => 19,
                'parent_id' => 0,
                'name' => 'base',
                'title' => '基本信息',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-gerenziliao',
                'sort' => 110,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 0,
                'create_time' => '2017-07-06 09:29:45',
                'modify_time' => '2017-10-13 14:47:41',
            ),
            17 => 
            array (
                'id' => 20,
                'parent_id' => 19,
                'name' => 'merchant/index',
                'title' => '商户管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-06 09:30:30',
                'modify_time' => '2017-07-06 09:36:19',
            ),
            18 => 
            array (
                'id' => 21,
                'parent_id' => 20,
                'name' => 'merchant/add',
                'title' => '添加商户',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-06 09:31:08',
                'modify_time' => '2017-07-06 09:31:08',
            ),
            19 => 
            array (
                'id' => 22,
                'parent_id' => 20,
                'name' => 'merchant/edit',
                'title' => '修改商户',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-06 09:31:35',
                'modify_time' => '2017-10-17 18:02:39',
            ),
            20 => 
            array (
                'id' => 23,
                'parent_id' => 20,
                'name' => 'merchant/export',
                'title' => '商户导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 110,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-06 14:31:01',
                'modify_time' => '2017-07-06 14:31:01',
            ),
            21 => 
            array (
                'id' => 24,
                'parent_id' => 0,
                'name' => 'warehouse/index',
                'title' => '仓管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-cangku',
                'sort' => 100,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 1,
                'create_time' => '2017-07-06 14:47:43',
                'modify_time' => '2017-07-08 15:38:11',
            ),
            22 => 
            array (
                'id' => 27,
                'parent_id' => 24,
                'name' => 'warehouse/add',
                'title' => '添加仓库',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-06 14:48:47',
                'modify_time' => '2017-07-06 14:49:59',
            ),
            23 => 
            array (
                'id' => 28,
                'parent_id' => 24,
                'name' => 'warehouse/edit',
                'title' => '修改仓库',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-06 14:49:34',
                'modify_time' => '2017-07-06 14:49:34',
            ),
            24 => 
            array (
                'id' => 29,
                'parent_id' => 19,
                'name' => 'driver/index',
                'title' => '司机管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 100,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-12 15:40:08',
                'modify_time' => '2017-07-12 16:01:41',
            ),
            25 => 
            array (
                'id' => 30,
                'parent_id' => 29,
                'name' => 'driver/selfpending',
                'title' => '待审核自营司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 100,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-12 15:41:36',
                'modify_time' => '2017-09-28 10:55:19',
            ),
            26 => 
            array (
                'id' => 31,
                'parent_id' => 29,
                'name' => 'driver/selfchecked',
                'title' => '已审核自营司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-12 15:43:14',
                'modify_time' => '2017-09-28 10:57:59',
            ),
            27 => 
            array (
                'id' => 32,
                'parent_id' => 29,
                'name' => 'driver/societypending',
                'title' => '待审核社会司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-12 15:46:01',
                'modify_time' => '2017-09-28 10:56:50',
            ),
            28 => 
            array (
                'id' => 33,
                'parent_id' => 29,
                'name' => 'driver/societychecked',
                'title' => '已审核社会司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 105,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-12 15:46:53',
                'modify_time' => '2017-09-28 11:06:34',
            ),
            29 => 
            array (
                'id' => 34,
                'parent_id' => 29,
                'name' => 'driver/societyverify',
                'title' => '审核社会司机',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 107,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-12 15:47:22',
                'modify_time' => '2017-10-16 17:27:22',
            ),
            30 => 
            array (
                'id' => 35,
                'parent_id' => 29,
                'name' => 'driver/selfverify',
                'title' => '审核自营司机',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-12 15:50:32',
                'modify_time' => '2017-10-16 17:26:31',
            ),
            31 => 
            array (
                'id' => 36,
                'parent_id' => 39,
                'name' => 'safe/index',
                'title' => '保险设置',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-13 11:20:20',
                'modify_time' => '2017-10-16 17:28:21',
            ),
            32 => 
            array (
                'id' => 37,
                'parent_id' => 39,
                'name' => 'safe/add',
                'title' => '添加保险',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 107,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-13 11:21:08',
                'modify_time' => '2017-09-27 17:14:15',
            ),
            33 => 
            array (
                'id' => 38,
                'parent_id' => 36,
                'name' => 'safe/toggle',
                'title' => '切换保险状态',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-13 11:21:38',
                'modify_time' => '2017-07-13 11:21:38',
            ),
            34 => 
            array (
                'id' => 39,
                'parent_id' => 1,
                'name' => 'config/index',
                'title' => '系统配置',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 120,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-18 10:55:04',
                'modify_time' => '2017-09-27 13:45:45',
            ),
            35 => 
            array (
                'id' => 41,
                'parent_id' => 0,
                'name' => 'task/index',
                'title' => '线路任务管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-renwu',
                'sort' => 3,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 1,
                'create_time' => '2017-07-19 14:53:23',
                'modify_time' => '2017-07-19 14:53:23',
            ),
            36 => 
            array (
                'id' => 42,
                'parent_id' => 41,
                'name' => 'task/copy',
                'title' => '复制任务',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 1,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-21 01:50:31',
                'modify_time' => '2017-07-21 01:50:31',
            ),
            37 => 
            array (
                'id' => 43,
                'parent_id' => 39,
                'name' => 'config/edit',
                'title' => '系统配置项',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 100,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-07-22 11:31:50',
                'modify_time' => '2017-10-13 14:45:26',
            ),
            38 => 
            array (
                'id' => 44,
                'parent_id' => 41,
                'name' => 'task/show',
                'title' => '选司机',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 2,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-07-24 10:24:16',
                'modify_time' => '2017-08-29 11:01:25',
            ),
            39 => 
            array (
                'id' => 45,
                'parent_id' => 0,
                'name' => 'order/index',
                'title' => '出车单管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-che',
                'sort' => 99,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:18:42',
                'modify_time' => '2017-10-18 14:11:15',
            ),
            40 => 
            array (
                'id' => 46,
                'parent_id' => 45,
                'name' => 'order/undo',
                'title' => '设置不配送',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:26:51',
                'modify_time' => '2017-08-10 14:26:51',
            ),
            41 => 
            array (
                'id' => 47,
                'parent_id' => 45,
                'name' => 'order/dispatch',
                'title' => '设置配送',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:27:28',
                'modify_time' => '2017-08-10 14:27:28',
            ),
            42 => 
            array (
                'id' => 48,
                'parent_id' => 45,
                'name' => 'order/cancel',
                'title' => '运营取消',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:29:45',
                'modify_time' => '2017-08-10 14:29:45',
            ),
            43 => 
            array (
                'id' => 49,
                'parent_id' => 45,
                'name' => 'order/finish',
                'title' => '一键完成',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:30:05',
                'modify_time' => '2017-08-15 16:56:07',
            ),
            44 => 
            array (
                'id' => 50,
                'parent_id' => 45,
                'name' => 'order/agent',
                'title' => '代签到',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:30:24',
                'modify_time' => '2017-08-15 16:56:22',
            ),
            45 => 
            array (
                'id' => 51,
                'parent_id' => 45,
                'name' => 'order/drivers',
                'title' => '改派司机列表',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 107,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:30:46',
                'modify_time' => '2017-08-15 16:56:36',
            ),
            46 => 
            array (
                'id' => 52,
                'parent_id' => 45,
                'name' => 'order/reassign',
                'title' => '改派司机',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-10 14:37:35',
                'modify_time' => '2017-08-15 16:56:48',
            ),
            47 => 
            array (
                'id' => 53,
                'parent_id' => 53,
                'name' => 'bill_pending',
                'title' => '财务中心',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => 'fa',
                'sort' => 106,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 0,
                'create_time' => '2017-08-15 17:03:34',
                'modify_time' => '2017-08-15 17:05:27',
            ),
            48 => 
            array (
                'id' => 54,
                'parent_id' => 0,
                'name' => 'finance',
                'title' => '财务中心',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-qian',
                'sort' => 106,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 0,
                'create_time' => '2017-08-15 17:07:40',
                'modify_time' => '2017-09-18 15:18:31',
            ),
            49 => 
            array (
                'id' => 55,
                'parent_id' => 54,
                'name' => 'bill/index',
                'title' => '商户账单',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 100,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-15 17:09:11',
                'modify_time' => '2017-08-15 17:55:25',
            ),
            50 => 
            array (
                'id' => 57,
                'parent_id' => 55,
                'name' => 'bill/checked',
                'title' => '已出账单',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-15 17:11:41',
                'modify_time' => '2017-08-15 17:11:41',
            ),
            51 => 
            array (
                'id' => 59,
                'parent_id' => 55,
                'name' => 'bill/pending',
                'title' => '未出账单',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-15 17:13:16',
                'modify_time' => '2017-08-15 17:13:16',
            ),
            52 => 
            array (
                'id' => 60,
                'parent_id' => 54,
                'name' => 'driveraccount/index',
                'title' => '司机账户',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-18 12:04:53',
                'modify_time' => '2017-09-27 17:35:38',
            ),
            53 => 
            array (
                'id' => 61,
                'parent_id' => 54,
                'name' => 'merchantaccount/index',
                'title' => '商户账户',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-18 12:10:07',
                'modify_time' => '2017-09-27 17:35:59',
            ),
            54 => 
            array (
                'id' => 62,
                'parent_id' => 55,
                'name' => 'bill/repay',
                'title' => '商户还款',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-22 15:03:24',
                'modify_time' => '2017-08-22 15:45:51',
            ),
            55 => 
            array (
                'id' => 63,
                'parent_id' => 55,
                'name' => 'bill/export',
                'title' => '导出已出账单',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-22 15:08:30',
                'modify_time' => '2017-10-18 14:07:59',
            ),
            56 => 
            array (
                'id' => 64,
                'parent_id' => 61,
                'name' => 'merchantaccount/export',
                'title' => '商户账户导出',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-22 15:11:44',
                'modify_time' => '2017-10-19 15:03:06',
            ),
            57 => 
            array (
                'id' => 65,
                'parent_id' => 60,
                'name' => 'driveraccount/download',
                'title' => '司机账户详情导出',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-22 15:12:53',
                'modify_time' => '2017-10-19 15:04:24',
            ),
            58 => 
            array (
                'id' => 66,
                'parent_id' => 55,
                'name' => 'repaylog/detail',
                'title' => '还款记录',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-22 15:33:53',
                'modify_time' => '2017-10-24 15:12:56',
            ),
            59 => 
            array (
                'id' => 68,
                'parent_id' => 41,
                'name' => 'task/delete',
                'title' => '删除任务',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 12:16:57',
                'modify_time' => '2017-09-09 09:59:06',
            ),
            60 => 
            array (
                'id' => 69,
                'parent_id' => 41,
                'name' => 'task/abandon',
                'title' => '废弃任务',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 12:22:42',
                'modify_time' => '2017-08-25 12:22:42',
            ),
            61 => 
            array (
                'id' => 70,
                'parent_id' => 41,
                'name' => 'task/choose',
                'title' => '选择司机',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 12:23:17',
                'modify_time' => '2017-08-25 12:25:25',
            ),
            62 => 
            array (
                'id' => 71,
                'parent_id' => 41,
                'name' => 'task/none',
                'title' => '全都不选',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 107,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 12:23:53',
                'modify_time' => '2017-08-25 12:24:43',
            ),
            63 => 
            array (
                'id' => 72,
                'parent_id' => 41,
                'name' => 'task/rescind',
                'title' => '无责任解约',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 12:24:27',
                'modify_time' => '2017-08-25 12:25:08',
            ),
            64 => 
            array (
                'id' => 73,
                'parent_id' => 41,
                'name' => 'task/detail',
                'title' => '司机详情 ',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 107,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 15:45:23',
                'modify_time' => '2017-08-25 15:45:23',
            ),
            65 => 
            array (
                'id' => 74,
                'parent_id' => 41,
                'name' => 'task/driverlist',
                'title' => '指派司机列表',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 15:57:50',
                'modify_time' => '2017-09-28 10:51:39',
            ),
            66 => 
            array (
                'id' => 75,
                'parent_id' => 41,
                'name' => 'task/taskassign',
                'title' => '指派司机',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 109,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 15:58:09',
                'modify_time' => '2017-09-27 13:53:59',
            ),
            67 => 
            array (
                'id' => 76,
                'parent_id' => 41,
                'name' => 'task/buysafe',
                'title' => '购买保价',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 110,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 16:10:31',
                'modify_time' => '2017-09-28 10:51:52',
            ),
            68 => 
            array (
                'id' => 77,
                'parent_id' => 19,
                'name' => 'car/index',
                'title' => '车辆管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 111,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-08-25 16:21:28',
                'modify_time' => '2017-11-16 17:17:46',
            ),
            69 => 
            array (
                'id' => 78,
                'parent_id' => 77,
                'name' => 'car/export',
                'title' => '车辆信息导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 112,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-08-25 16:22:03',
                'modify_time' => '2017-08-25 16:22:03',
            ),
            70 => 
            array (
                'id' => 79,
                'parent_id' => 41,
                'name' => 'task/info',
                'title' => '任务详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 109,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-09-14 14:01:01',
                'modify_time' => '2017-09-14 14:01:01',
            ),
            71 => 
            array (
                'id' => 80,
                'parent_id' => 29,
                'name' => 'driver/edit',
                'title' => '编辑司机信息',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-09-04 14:55:30',
                'modify_time' => '2017-09-04 14:55:30',
            ),
            72 => 
            array (
                'id' => 81,
                'parent_id' => 29,
                'name' => 'driver/toggle',
                'title' => '切换司机状态',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-09-04 14:58:45',
                'modify_time' => '2017-09-04 14:58:45',
            ),
            73 => 
            array (
                'id' => 83,
                'parent_id' => 29,
                'name' => 'driver/check',
                'title' => '司机审核',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-09-04 15:00:51',
                'modify_time' => '2017-09-04 15:00:51',
            ),
            74 => 
            array (
                'id' => 84,
                'parent_id' => 29,
                'name' => 'driver/upload',
                'title' => '上传头像',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-09-04 15:01:32',
                'modify_time' => '2017-09-04 15:01:32',
            ),
            75 => 
            array (
                'id' => 85,
                'parent_id' => 29,
                'name' => 'driver/drivertag',
                'title' => '司机标签',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2017-09-04 15:03:07',
                'modify_time' => '2017-09-28 11:17:41',
            ),
            76 => 
            array (
                'id' => 86,
                'parent_id' => 60,
                'name' => 'driveraccount/detail',
                'title' => '司机账单详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-27 17:53:31',
                'modify_time' => '2017-09-27 17:56:27',
            ),
            77 => 
            array (
                'id' => 87,
                'parent_id' => 61,
                'name' => 'merchantaccount/detail',
                'title' => '商户账户详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-27 17:54:34',
                'modify_time' => '2017-10-19 15:02:36',
            ),
            78 => 
            array (
                'id' => 90,
                'parent_id' => 60,
                'name' => 'driveraccount/export',
                'title' => '司机账户导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 103,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 09:24:55',
                'modify_time' => '2017-10-19 15:04:39',
            ),
            79 => 
            array (
                'id' => 91,
                'parent_id' => 61,
                'name' => 'merchantaccount/download',
                'title' => '商户账户详情导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 09:26:38',
                'modify_time' => '2017-10-19 15:01:57',
            ),
            80 => 
            array (
                'id' => 92,
                'parent_id' => 45,
                'name' => 'order/detail',
                'title' => '任务单详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 105,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:10:11',
                'modify_time' => '2017-09-28 10:10:46',
            ),
            81 => 
            array (
                'id' => 93,
                'parent_id' => 29,
                'name' => 'driver/selfshow',
                'title' => '自营司机详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 107,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:14:26',
                'modify_time' => '2017-09-28 10:14:26',
            ),
            82 => 
            array (
                'id' => 94,
                'parent_id' => 29,
                'name' => 'driver/societyshow',
                'title' => '社会司机详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:15:37',
                'modify_time' => '2017-10-19 14:49:45',
            ),
            83 => 
            array (
                'id' => 96,
                'parent_id' => 24,
                'name' => 'warehouse/export',
                'title' => '仓库导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:24:59',
                'modify_time' => '2017-09-28 10:24:59',
            ),
            84 => 
            array (
                'id' => 97,
                'parent_id' => 24,
                'name' => 'warehouse/delete',
                'title' => '删除仓库',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:25:33',
                'modify_time' => '2017-09-28 11:23:51',
            ),
            85 => 
            array (
                'id' => 98,
                'parent_id' => 45,
                'name' => 'order/export',
                'title' => '出车单导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:31:55',
                'modify_time' => '2017-09-28 11:23:33',
            ),
            86 => 
            array (
                'id' => 99,
                'parent_id' => 24,
                'name' => 'warehouse/show',
                'title' => '仓库详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:33:24',
                'modify_time' => '2017-09-28 11:20:30',
            ),
            87 => 
            array (
                'id' => 100,
                'parent_id' => 24,
                'name' => 'warehouse/toggle',
                'title' => '切换仓库',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 10:35:09',
                'modify_time' => '2017-09-28 11:25:08',
            ),
            88 => 
            array (
                'id' => 101,
                'parent_id' => 29,
                'name' => 'driver/addtag',
                'title' => '添加司机标签',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 108,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 11:19:09',
                'modify_time' => '2017-09-28 11:19:09',
            ),
            89 => 
            array (
                'id' => 102,
                'parent_id' => 29,
                'name' => 'driver/deltag',
                'title' => '删除标签',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 115,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 11:19:58',
                'modify_time' => '2017-09-28 11:21:09',
            ),
            90 => 
            array (
                'id' => 103,
                'parent_id' => 29,
                'name' => 'driver/societyaccount',
                'title' => '社会司机账号',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 115,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 11:22:25',
                'modify_time' => '2017-09-28 11:22:25',
            ),
            91 => 
            array (
                'id' => 104,
                'parent_id' => 29,
                'name' => 'driver/taglist',
                'title' => '司机标签',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 120,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-09-28 11:29:44',
                'modify_time' => '2017-09-28 11:29:44',
            ),
            92 => 
            array (
                'id' => 105,
                'parent_id' => 41,
                'name' => 'task/isshow',
                'title' => '修改任务显示',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 6,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-09-30 15:59:49',
                'modify_time' => '2017-10-23 17:48:53',
            ),
            93 => 
            array (
                'id' => 106,
                'parent_id' => 55,
                'name' => 'bill/download',
                'title' => '导出未出账单',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 105,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-10-18 14:08:33',
                'modify_time' => '2017-10-19 15:03:19',
            ),
            94 => 
            array (
                'id' => 107,
                'parent_id' => 55,
                'name' => 'bill/detail',
                'title' => '商户账单详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 109,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 0,
                'create_time' => '2017-10-23 17:48:29',
                'modify_time' => '2017-10-23 17:49:59',
            ),
            95 => 
            array (
                'id' => 108,
                'parent_id' => 0,
                'name' => 'time',
                'title' => '配送点管理',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => 'icon-ditudianxuan',
                'sort' => 100,
                'isverify' => 1,
                'level' => 1,
                'isclick' => 1,
                'create_time' => '2017-11-27 14:30:47',
                'modify_time' => '2017-12-09 09:57:56',
            ),
            96 => 
            array (
                'id' => 109,
                'parent_id' => 108,
                'name' => 'time/index',
                'title' => '配送点列表',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-11-27 14:36:02',
                'modify_time' => '2017-12-09 09:58:13',
            ),
            97 => 
            array (
                'id' => 110,
                'parent_id' => 108,
                'name' => 'point/detail',
                'title' => '配送点详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-12-04 13:54:19',
                'modify_time' => '2017-12-19 17:48:32',
            ),
            98 => 
            array (
                'id' => 112,
                'parent_id' => 108,
                'name' => 'point/import',
                'title' => '配送点导入',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 0,
                'create_time' => '2017-12-11 15:50:12',
                'modify_time' => '2017-12-11 15:50:12',
            ),
            99 => 
            array (
                'id' => 113,
                'parent_id' => 108,
                'name' => 'point/location',
                'title' => '地图定位',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 0,
                'create_time' => '2017-12-11 15:50:55',
                'modify_time' => '2017-12-11 15:59:19',
            ),
            100 => 
            array (
                'id' => 114,
                'parent_id' => 108,
                'name' => 'point/delete',
                'title' => '配送点删除',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 102,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-12-11 15:52:09',
                'modify_time' => '2017-12-11 15:52:09',
            ),
            101 => 
            array (
                'id' => 115,
                'parent_id' => 108,
                'name' => 'line/circle',
                'title' => '地图排线',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '地图排线',
                'sort' => 103,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-12-11 15:55:31',
                'modify_time' => '2017-12-11 15:58:29',
            ),
            102 => 
            array (
                'id' => 116,
                'parent_id' => 108,
                'name' => 'line/point',
                'title' => '排序地图点',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-12-11 15:56:38',
                'modify_time' => '2017-12-11 15:58:19',
            ),
            103 => 
            array (
                'id' => 117,
                'parent_id' => 108,
                'name' => 'line/change',
                'title' => '线路保存',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 105,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-12-11 15:57:22',
                'modify_time' => '2017-12-11 15:57:22',
            ),
            104 => 
            array (
                'id' => 118,
                'parent_id' => 108,
                'name' => 'line/export',
                'title' => '线路导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 106,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-12-11 15:57:53',
                'modify_time' => '2017-12-11 15:57:53',
            ),
            105 => 
            array (
                'id' => 119,
                'parent_id' => 41,
                'name' => 'task/import',
                'title' => '导入路线',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 110,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 0,
                'create_time' => '2017-12-15 10:11:09',
                'modify_time' => '2017-12-15 10:11:09',
            ),
            106 => 
            array (
                'id' => 120,
                'parent_id' => 45,
                'name' => 'order/change',
                'title' => '到仓时间及价格变更',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 200,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 1,
                'create_time' => '2017-12-15 16:18:39',
                'modify_time' => '2017-12-15 16:18:39',
            ),
            107 => 
            array (
                'id' => 122,
                'parent_id' => 108,
                'name' => 'point/export',
                'title' => '配送点导出',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 2,
                'isclick' => 0,
                'create_time' => '2017-12-18 17:17:05',
                'modify_time' => '2017-12-19 17:49:50',
            ),
            108 => 
            array (
                'id' => 123,
                'parent_id' => 29,
                'name' => 'driver/cooperatepending',
                'title' => '待审核合作司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 101,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2018-03-12 11:02:59',
                'modify_time' => '2018-03-12 11:26:13',
            ),
            109 => 
            array (
                'id' => 124,
                'parent_id' => 29,
                'name' => 'driver/cooperateverify',
                'title' => '合作司机审核',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 130,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2018-03-12 11:05:22',
                'modify_time' => '2018-03-12 11:05:22',
            ),
            110 => 
            array (
                'id' => 125,
                'parent_id' => 29,
                'name' => 'driver/cooperatechecked',
                'title' => '已审核合作司机',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 104,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2018-03-12 11:07:05',
                'modify_time' => '2018-03-12 14:21:33',
            ),
            111 => 
            array (
                'id' => 126,
                'parent_id' => 29,
                'name' => 'driver/cooperateshow',
                'title' => '合作司机详情',
                'islink' => 0,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 131,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2018-03-12 11:14:27',
                'modify_time' => '2018-03-12 11:14:27',
            ),
            112 => 
            array (
                'id' => 127,
                'parent_id' => 29,
                'name' => 'driver/history',
                'title' => '司机审核记录',
                'islink' => 1,
                'isadmin' => 0,
                'icon' => '',
                'sort' => 132,
                'isverify' => 1,
                'level' => 3,
                'isclick' => 1,
                'create_time' => '2018-03-12 15:46:48',
                'modify_time' => '2018-03-12 15:46:48',
            ),
        ));
        
        
    }
}