<?php

use Illuminate\Database\Seeder;

class ZdSysRule1TableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('zd_sys_rule1')->delete();
        
        \DB::table('zd_sys_rule1')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'name' => 'sysconfig.base',
                'title' => '系统管理',
                'islink' => 1,
                'icon' => 'md-reverse-camera',
                'sort' => 255,
                'create_time' => '2018-08-03 17:56:46',
                'modify_time' => '2018-08-16 17:06:36',
            ),
            1 => 
            array (
                'id' => 3,
                'parent_id' => 1,
                'name' => 'sysconfig.permission.index',
                'title' => '权限&菜单',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 255,
                'create_time' => '2018-08-03 17:56:46',
                'modify_time' => '2018-08-08 10:43:40',
            ),
            2 => 
            array (
                'id' => 4,
                'parent_id' => 1,
                'name' => 'sysconfig.role.index',
                'title' => '角色管理',
                'islink' => 1,
                'icon' => '',
                'sort' => 255,
                'create_time' => '2018-08-03 17:56:46',
                'modify_time' => '2018-08-03 17:56:47',
            ),
            3 => 
            array (
                'id' => 5,
                'parent_id' => 1,
                'name' => 'sysconfig.admin.index',
                'title' => '用户管理',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 255,
                'create_time' => '2018-08-03 17:56:46',
                'modify_time' => '2018-08-08 10:44:34',
            ),
            4 => 
            array (
                'id' => 9,
                'parent_id' => 3,
                'name' => 'sysconfig.permission.store',
                'title' => '添加',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-08 10:47:07',
                'modify_time' => '2018-08-08 10:47:07',
            ),
            5 => 
            array (
                'id' => 10,
                'parent_id' => 3,
                'name' => 'sysconfig.permission.update',
                'title' => '更新',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-08 11:08:12',
                'modify_time' => '2018-08-09 10:18:37',
            ),
            6 => 
            array (
                'id' => 11,
                'parent_id' => 3,
                'name' => 'sysconfig.permission.destroy',
                'title' => '删除',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-08 11:09:16',
                'modify_time' => '2018-08-08 11:09:16',
            ),
            7 => 
            array (
                'id' => 12,
                'parent_id' => 1,
                'name' => 'sysconfig.config.index',
                'title' => '系统配置',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-08 11:26:42',
                'modify_time' => '2018-08-08 13:50:23',
            ),
            8 => 
            array (
                'id' => 13,
                'parent_id' => 12,
                'name' => 'sysconfig.config.update',
                'title' => '更新',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-09 10:18:25',
                'modify_time' => '2018-08-09 10:18:25',
            ),
            9 => 
            array (
                'id' => 14,
                'parent_id' => 1,
                'name' => 'sysconfig.safe.index',
                'title' => '保险设置',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-09 10:20:11',
                'modify_time' => '2018-08-09 10:21:27',
            ),
            10 => 
            array (
                'id' => 15,
                'parent_id' => 0,
                'name' => 'time.index',
                'title' => '配送点管理',
                'islink' => 1,
                'icon' => 'md-pizza',
                'sort' => 1,
                'create_time' => '2018-08-10 15:16:25',
                'modify_time' => '2018-08-10 15:16:25',
            ),
            11 => 
            array (
                'id' => 16,
                'parent_id' => 0,
                'name' => 'base.index',
                'title' => '基本信息',
                'islink' => 1,
                'icon' => 'md-qr-scanner',
                'sort' => 1,
                'create_time' => '2018-08-13 11:05:24',
                'modify_time' => '2018-08-16 17:06:01',
            ),
            12 => 
            array (
                'id' => 17,
                'parent_id' => 16,
                'name' => 'base.driver.manage',
                'title' => '司机管理',
                'islink' => 1,
                'icon' => 'base.driver',
                'sort' => 1,
                'create_time' => '2018-08-13 11:06:05',
                'modify_time' => '2018-08-13 12:20:59',
            ),
            13 => 
            array (
                'id' => 18,
                'parent_id' => 17,
                'name' => 'base.driver.index',
                'title' => '自营司机',
                'islink' => 1,
                'icon' => 'base.driver.index',
                'sort' => 1,
                'create_time' => '2018-08-13 11:07:47',
                'modify_time' => '2018-08-13 12:21:11',
            ),
            14 => 
            array (
                'id' => 19,
                'parent_id' => 17,
                'name' => 'base.driver.work',
                'title' => '合作司机',
                'islink' => 1,
                'icon' => 'base.driver.work',
                'sort' => 1,
                'create_time' => '2018-08-13 11:09:46',
                'modify_time' => '2018-08-13 12:21:22',
            ),
            15 => 
            array (
                'id' => 20,
                'parent_id' => 17,
                'name' => 'base.driver.social',
                'title' => '社会司机',
                'islink' => 1,
                'icon' => 'base.driver.social',
                'sort' => 1,
                'create_time' => '2018-08-14 09:41:28',
                'modify_time' => '2018-08-14 09:41:28',
            ),
            16 => 
            array (
                'id' => 21,
                'parent_id' => 18,
                'name' => 'driver.index',
                'title' => '自营司机列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-14 11:58:21',
                'modify_time' => '2018-08-14 11:58:21',
            ),
            17 => 
            array (
                'id' => 22,
                'parent_id' => 19,
                'name' => 'driver.work',
                'title' => '合作司机列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-14 11:58:43',
                'modify_time' => '2018-08-14 11:58:43',
            ),
            18 => 
            array (
                'id' => 23,
                'parent_id' => 20,
                'name' => 'driver.social',
                'title' => '社会司机列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-14 11:59:01',
                'modify_time' => '2018-08-14 11:59:01',
            ),
            19 => 
            array (
                'id' => 24,
                'parent_id' => 18,
                'name' => 'driver.index.show',
                'title' => '查看自营司机',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-14 11:59:23',
                'modify_time' => '2018-08-14 11:59:23',
            ),
            20 => 
            array (
                'id' => 25,
                'parent_id' => 19,
                'name' => 'driver.work.show',
                'title' => '查看合作司机',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-14 11:59:47',
                'modify_time' => '2018-08-14 11:59:47',
            ),
            21 => 
            array (
                'id' => 26,
                'parent_id' => 20,
                'name' => 'driver.social.show',
                'title' => '查看社会司机',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-14 12:00:07',
                'modify_time' => '2018-08-14 12:00:07',
            ),
            22 => 
            array (
                'id' => 27,
                'parent_id' => 16,
                'name' => 'base.merchant.index',
                'title' => '商户信息',
                'islink' => 1,
                'icon' => 'base.merchant.index',
                'sort' => 1,
                'create_time' => '2018-08-14 12:01:44',
                'modify_time' => '2018-08-14 12:01:44',
            ),
            23 => 
            array (
                'id' => 28,
                'parent_id' => 27,
                'name' => 'merchants.index',
                'title' => '商户列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-14 12:02:50',
                'modify_time' => '2018-08-14 12:02:50',
            ),
            24 => 
            array (
                'id' => 31,
                'parent_id' => 16,
                'name' => 'base.car.index',
                'title' => '车辆管理',
                'islink' => 1,
                'icon' => 'base.car',
                'sort' => 1,
                'create_time' => '2018-08-16 14:58:27',
                'modify_time' => '2018-08-16 15:03:51',
            ),
            25 => 
            array (
                'id' => 32,
                'parent_id' => 31,
                'name' => 'car.index',
                'title' => '车辆列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-16 14:59:56',
                'modify_time' => '2018-08-16 15:03:41',
            ),
            26 => 
            array (
                'id' => 33,
                'parent_id' => 0,
                'name' => 'warehouse.index',
                'title' => '仓库管理',
                'islink' => 1,
                'icon' => 'md-planet',
                'sort' => 1,
                'create_time' => '2018-08-16 17:00:17',
                'modify_time' => '2018-08-16 17:00:17',
            ),
            27 => 
            array (
                'id' => 34,
                'parent_id' => 33,
                'name' => 'warehouse.list',
                'title' => '仓库列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-16 17:01:21',
                'modify_time' => '2018-08-16 17:01:21',
            ),
            28 => 
            array (
                'id' => 35,
                'parent_id' => 33,
                'name' => 'warehouse.create',
                'title' => '添加仓库',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-16 17:02:02',
                'modify_time' => '2018-08-16 17:02:02',
            ),
            29 => 
            array (
                'id' => 36,
                'parent_id' => 33,
                'name' => 'warehouse.update',
                'title' => '更新仓库',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-16 17:02:24',
                'modify_time' => '2018-08-16 17:02:24',
            ),
            30 => 
            array (
                'id' => 37,
                'parent_id' => 33,
                'name' => 'warehouse.show',
                'title' => '获取仓库',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-16 17:02:50',
                'modify_time' => '2018-08-16 17:02:50',
            ),
            31 => 
            array (
                'id' => 38,
                'parent_id' => 33,
                'name' => 'warehouse.destroy',
                'title' => '删除仓库',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-16 17:03:17',
                'modify_time' => '2018-08-16 17:03:17',
            ),
            32 => 
            array (
                'id' => 39,
                'parent_id' => 0,
                'name' => 'task.push',
                'title' => '发布线路任务',
                'islink' => 1,
                'icon' => 'ios-create',
                'sort' => 255,
                'create_time' => '2018-08-20 10:17:25',
                'modify_time' => '2018-08-27 10:25:15',
            ),
            33 => 
            array (
                'id' => 40,
                'parent_id' => 39,
                'name' => 'task.create',
                'title' => '招司机',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 255,
                'create_time' => '2018-08-20 10:26:44',
                'modify_time' => '2018-09-04 09:27:48',
            ),
            34 => 
            array (
                'id' => 41,
                'parent_id' => 0,
                'name' => 'task.order',
                'title' => '出车单管理',
                'islink' => 1,
                'icon' => 'md-archive',
                'sort' => 1,
                'create_time' => '2018-08-20 16:37:15',
                'modify_time' => '2018-08-20 16:37:15',
            ),
            35 => 
            array (
                'id' => 42,
                'parent_id' => 41,
                'name' => 'task.order.index',
                'title' => '出车单列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-20 16:38:06',
                'modify_time' => '2018-08-20 16:38:06',
            ),
            36 => 
            array (
                'id' => 43,
                'parent_id' => 41,
                'name' => 'task.order.show',
                'title' => '查看出车单',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-20 16:38:43',
                'modify_time' => '2018-08-20 16:38:43',
            ),
            37 => 
            array (
                'id' => 45,
                'parent_id' => 0,
                'name' => 'task.lists',
                'title' => '线路任务管理',
                'islink' => 1,
                'icon' => 'md-aperture',
                'sort' => 1,
                'create_time' => '2018-08-27 10:25:36',
                'modify_time' => '2018-08-27 10:59:00',
            ),
            38 => 
            array (
                'id' => 46,
                'parent_id' => 45,
                'name' => 'task.index',
                'title' => '线路任务列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-27 10:28:41',
                'modify_time' => '2018-08-27 10:28:41',
            ),
            39 => 
            array (
                'id' => 47,
                'parent_id' => 0,
                'name' => 'finance.index',
                'title' => '财务管理',
                'islink' => 1,
                'icon' => 'md-analytics',
                'sort' => 1,
                'create_time' => '2018-08-27 12:01:47',
                'modify_time' => '2018-08-28 13:49:35',
            ),
            40 => 
            array (
                'id' => 48,
                'parent_id' => 47,
                'name' => 'bill.month',
                'title' => '商户已出账单',
                'islink' => 1,
                'icon' => 'jmnnj',
                'sort' => 1,
                'create_time' => '2018-08-27 12:03:35',
                'modify_time' => '2018-08-30 15:14:25',
            ),
            41 => 
            array (
                'id' => 49,
                'parent_id' => 47,
                'name' => 'bill.day',
                'title' => '商户未出账单',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-28 13:50:39',
                'modify_time' => '2018-08-30 15:14:36',
            ),
            42 => 
            array (
                'id' => 50,
                'parent_id' => 47,
                'name' => 'account.driver',
                'title' => '司机账户',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-29 11:05:15',
                'modify_time' => '2018-09-10 10:48:33',
            ),
            43 => 
            array (
                'id' => 51,
                'parent_id' => 47,
                'name' => 'account.merchant',
                'title' => '商户账户',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-08-29 15:40:06',
                'modify_time' => '2018-08-29 15:40:06',
            ),
            44 => 
            array (
                'id' => 52,
                'parent_id' => 47,
                'name' => 'award.index',
                'title' => '司机奖惩',
                'islink' => 1,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-09-03 14:54:26',
                'modify_time' => '2018-09-03 14:54:26',
            ),
            45 => 
            array (
                'id' => 53,
                'parent_id' => 48,
                'name' => 'bill.repay',
                'title' => '商户还款',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-09-10 10:12:06',
                'modify_time' => '2018-09-10 10:12:06',
            ),
            46 => 
            array (
                'id' => 54,
                'parent_id' => 48,
                'name' => 'bill.log',
                'title' => '还款记录',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 2,
                'create_time' => '2018-09-10 10:15:02',
                'modify_time' => '2018-09-10 10:15:02',
            ),
            47 => 
            array (
                'id' => 55,
                'parent_id' => 48,
                'name' => 'bill.total',
                'title' => '商户待还款总和',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-10 10:15:54',
                'modify_time' => '2018-09-25 16:04:05',
            ),
            48 => 
            array (
                'id' => 56,
                'parent_id' => 48,
                'name' => 'bill.export',
                'title' => '还款导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-09-10 10:16:39',
                'modify_time' => '2018-09-10 10:16:39',
            ),
            49 => 
            array (
                'id' => 57,
                'parent_id' => 48,
                'name' => 'bill.download',
                'title' => '账户明细导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 5,
                'create_time' => '2018-09-10 10:17:23',
                'modify_time' => '2018-09-10 10:18:54',
            ),
            50 => 
            array (
                'id' => 58,
                'parent_id' => 48,
                'name' => 'bill.statistics',
                'title' => '还款月统计',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 7,
                'create_time' => '2018-09-10 10:22:39',
                'modify_time' => '2018-09-10 10:25:09',
            ),
            51 => 
            array (
                'id' => 59,
                'parent_id' => 48,
                'name' => 'bill.analysis',
                'title' => '还款日统计',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 8,
                'create_time' => '2018-09-10 10:24:50',
                'modify_time' => '2018-09-10 10:24:50',
            ),
            52 => 
            array (
                'id' => 60,
                'parent_id' => 50,
                'name' => 'account.driver.single',
                'title' => '司机账户列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 2,
                'create_time' => '2018-09-10 10:39:49',
                'modify_time' => '2018-09-10 10:39:49',
            ),
            53 => 
            array (
                'id' => 61,
                'parent_id' => 50,
                'name' => 'account.driver.statistics',
                'title' => '司机账户统计',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-10 10:41:06',
                'modify_time' => '2018-09-10 10:41:06',
            ),
            54 => 
            array (
                'id' => 62,
                'parent_id' => 50,
                'name' => 'account.driver.export',
                'title' => '司机账户导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 4,
                'create_time' => '2018-09-10 10:43:05',
                'modify_time' => '2018-09-25 16:04:30',
            ),
            55 => 
            array (
                'id' => 63,
                'parent_id' => 50,
                'name' => 'account.driver.download',
                'title' => '司机账户详情导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 5,
                'create_time' => '2018-09-10 10:43:58',
                'modify_time' => '2018-09-10 10:43:58',
            ),
            56 => 
            array (
                'id' => 64,
                'parent_id' => 51,
                'name' => 'account.merchant.single',
                'title' => '商户账单详情',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 2,
                'create_time' => '2018-09-10 10:49:37',
                'modify_time' => '2018-09-10 10:49:37',
            ),
            57 => 
            array (
                'id' => 65,
                'parent_id' => 51,
                'name' => 'account.merchant.statistics\'',
                'title' => '商户详情',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-10 10:50:33',
                'modify_time' => '2018-09-10 10:50:33',
            ),
            58 => 
            array (
                'id' => 66,
                'parent_id' => 51,
                'name' => 'account.merchant.export',
                'title' => '商户账户导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-10 10:51:05',
                'modify_time' => '2018-09-10 10:51:05',
            ),
            59 => 
            array (
                'id' => 68,
                'parent_id' => 51,
                'name' => 'account.merchant.download',
                'title' => '商户详情导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 5,
                'create_time' => '2018-09-10 10:52:29',
                'modify_time' => '2018-09-10 10:52:29',
            ),
            60 => 
            array (
                'id' => 69,
                'parent_id' => 52,
                'name' => 'award.store',
                'title' => '添加',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 2,
                'create_time' => '2018-09-10 10:53:47',
                'modify_time' => '2018-09-10 10:53:47',
            ),
            61 => 
            array (
                'id' => 70,
                'parent_id' => 52,
                'name' => 'award.update',
                'title' => '更新',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-10 10:54:21',
                'modify_time' => '2018-09-10 10:54:21',
            ),
            62 => 
            array (
                'id' => 71,
                'parent_id' => 52,
                'name' => 'award.destroy',
                'title' => '删除',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 5,
                'create_time' => '2018-09-10 10:54:51',
                'modify_time' => '2018-09-10 10:54:51',
            ),
            63 => 
            array (
                'id' => 72,
                'parent_id' => 52,
                'name' => 'award.show',
                'title' => '显示',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 6,
                'create_time' => '2018-09-10 10:55:31',
                'modify_time' => '2018-09-10 10:55:43',
            ),
            64 => 
            array (
                'id' => 73,
                'parent_id' => 52,
                'name' => 'award.export',
                'title' => '导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 7,
                'create_time' => '2018-09-10 10:56:21',
                'modify_time' => '2018-09-10 10:56:34',
            ),
            65 => 
            array (
                'id' => 74,
                'parent_id' => 27,
                'name' => 'contract.show',
                'title' => '商户合同',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-09-10 11:06:17',
                'modify_time' => '2018-09-10 11:06:17',
            ),
            66 => 
            array (
                'id' => 75,
                'parent_id' => 27,
                'name' => 'contract.upload',
                'title' => '上传商户合同',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-10 11:07:08',
                'modify_time' => '2018-09-10 11:07:08',
            ),
            67 => 
            array (
                'id' => 76,
                'parent_id' => 27,
                'name' => 'contract.update',
                'title' => '更新商户合同',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 5,
                'create_time' => '2018-09-10 11:07:41',
                'modify_time' => '2018-09-10 11:07:41',
            ),
            68 => 
            array (
                'id' => 128,
                'parent_id' => 15,
                'name' => 'time.import',
                'title' => '导入配送点',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-09-26 09:42:17',
                'modify_time' => '2018-09-26 09:42:17',
            ),
            69 => 
            array (
                'id' => 129,
                'parent_id' => 15,
                'name' => 'point.index',
                'title' => '配送点列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 2,
                'create_time' => '2018-09-26 09:42:38',
                'modify_time' => '2018-09-26 09:42:38',
            ),
            70 => 
            array (
                'id' => 130,
                'parent_id' => 129,
                'name' => 'point.show',
                'title' => '配送点详情',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-09-26 09:43:01',
                'modify_time' => '2018-09-26 09:43:01',
            ),
            71 => 
            array (
                'id' => 131,
                'parent_id' => 129,
                'name' => 'point.update',
                'title' => '配送点更新',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 2,
                'create_time' => '2018-09-26 09:43:21',
                'modify_time' => '2018-09-26 09:43:21',
            ),
            72 => 
            array (
                'id' => 132,
                'parent_id' => 129,
                'name' => 'point.delete',
                'title' => '配送点删除',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-26 09:43:40',
                'modify_time' => '2018-09-26 09:43:40',
            ),
            73 => 
            array (
                'id' => 133,
                'parent_id' => 129,
                'name' => 'point.export',
                'title' => '配送点导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 4,
                'create_time' => '2018-09-26 09:44:13',
                'modify_time' => '2018-09-26 09:44:13',
            ),
            74 => 
            array (
                'id' => 134,
                'parent_id' => 15,
                'name' => 'point.line',
                'title' => '配送点路线列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-26 09:44:33',
                'modify_time' => '2018-09-26 09:44:33',
            ),
            75 => 
            array (
                'id' => 135,
                'parent_id' => 134,
                'name' => 'time.change',
                'title' => '保存全部配送点',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 1,
                'create_time' => '2018-09-26 09:44:57',
                'modify_time' => '2018-09-26 09:44:57',
            ),
            76 => 
            array (
                'id' => 136,
                'parent_id' => 134,
                'name' => 'point.download',
                'title' => '配送点线路导出',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 2,
                'create_time' => '2018-09-26 09:45:17',
                'modify_time' => '2018-09-26 09:45:17',
            ),
            77 => 
            array (
                'id' => 137,
                'parent_id' => 134,
                'name' => 'point.taskline',
                'title' => '发布线路任务列表',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 3,
                'create_time' => '2018-09-26 09:45:41',
                'modify_time' => '2018-09-26 09:45:41',
            ),
            78 => 
            array (
                'id' => 138,
                'parent_id' => 134,
                'name' => 'point.tasklinepoint',
                'title' => '发布任务路线详情',
                'islink' => 0,
                'icon' => NULL,
                'sort' => 4,
                'create_time' => '2018-09-26 09:46:08',
                'modify_time' => '2018-09-26 09:46:08',
            ),
        ));
        
        
    }
}