<?php

use Illuminate\Database\Seeder;

class ZdTaskOfferTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('zd_task_offer')->delete();
        
        \DB::table('zd_task_offer')->insert(array (
            0 => 
            array (
                'id' => 129,
                'task_id' => 1000157,
                'driver_id' => 5401,
                'unit_price' => '350.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '350.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 14:40:12',
                'modify_time' => '2018-07-23 14:40:12',
            ),
            1 => 
            array (
                'id' => 130,
                'task_id' => 1000158,
                'driver_id' => 5405,
                'unit_price' => '266.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '266.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 14:57:27',
                'modify_time' => '2018-07-23 14:57:27',
            ),
            2 => 
            array (
                'id' => 131,
                'task_id' => 1000159,
                'driver_id' => 5531,
                'unit_price' => '100.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 15:09:46',
                'modify_time' => '2018-07-23 15:09:46',
            ),
            3 => 
            array (
                'id' => 132,
                'task_id' => 1000160,
                'driver_id' => 5531,
                'unit_price' => '100.15',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.15',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 15:13:28',
                'modify_time' => '2018-07-23 15:13:28',
            ),
            4 => 
            array (
                'id' => 133,
                'task_id' => 1000161,
                'driver_id' => 5401,
                'unit_price' => '201.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '201.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 15:14:32',
                'modify_time' => '2018-07-23 15:14:32',
            ),
            5 => 
            array (
                'id' => 134,
                'task_id' => 1000164,
                'driver_id' => 5511,
                'unit_price' => '200.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 15:57:27',
                'modify_time' => '2018-07-23 15:57:27',
            ),
            6 => 
            array (
                'id' => 135,
                'task_id' => 1000167,
                'driver_id' => 5367,
                'unit_price' => '100.01',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.01',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 16:18:50',
                'modify_time' => '2018-07-23 16:18:50',
            ),
            7 => 
            array (
                'id' => 137,
                'task_id' => 1000171,
                'driver_id' => 5526,
                'unit_price' => '380.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '380.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '舟到系统变更司机',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 16:48:28',
                'modify_time' => '2018-07-23 16:48:28',
            ),
            8 => 
            array (
                'id' => 138,
                'task_id' => 1000172,
                'driver_id' => 5503,
                'unit_price' => '350.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '350.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 17:29:23',
                'modify_time' => '2018-07-23 17:29:23',
            ),
            9 => 
            array (
                'id' => 139,
                'task_id' => 1000174,
                'driver_id' => 5531,
                'unit_price' => '100.23',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.23',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 17:46:05',
                'modify_time' => '2018-07-23 17:46:05',
            ),
            10 => 
            array (
                'id' => 141,
                'task_id' => 1000175,
                'driver_id' => 5367,
                'unit_price' => '200.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 17:48:51',
                'modify_time' => '2018-07-23 17:48:51',
            ),
            11 => 
            array (
                'id' => 142,
                'task_id' => 1000176,
                'driver_id' => 5404,
                'unit_price' => '450.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '450.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 18:06:59',
                'modify_time' => '2018-07-23 18:06:59',
            ),
            12 => 
            array (
                'id' => 143,
                'task_id' => 1000177,
                'driver_id' => 5488,
                'unit_price' => '410.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '410.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-23 18:09:27',
                'modify_time' => '2018-07-23 18:09:27',
            ),
            13 => 
            array (
                'id' => 145,
                'task_id' => 1000180,
                'driver_id' => 5531,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 10:55:10',
                'modify_time' => '2018-07-24 10:55:10',
            ),
            14 => 
            array (
                'id' => 146,
                'task_id' => 1000180,
                'driver_id' => 5519,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 10:56:23',
                'modify_time' => '2018-07-24 10:56:23',
            ),
            15 => 
            array (
                'id' => 148,
                'task_id' => 1000192,
                'driver_id' => 5423,
                'unit_price' => '20.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '20.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 11:37:51',
                'modify_time' => '2018-07-24 11:37:51',
            ),
            16 => 
            array (
                'id' => 149,
                'task_id' => 1000193,
                'driver_id' => 5404,
                'unit_price' => '29.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '29.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 11:49:43',
                'modify_time' => '2018-07-24 11:49:43',
            ),
            17 => 
            array (
                'id' => 150,
                'task_id' => 1000197,
                'driver_id' => 5405,
                'unit_price' => '500.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 13:38:25',
                'modify_time' => '2018-07-24 13:38:25',
            ),
            18 => 
            array (
                'id' => 151,
                'task_id' => 1000198,
                'driver_id' => 5403,
                'unit_price' => '100.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 13:44:17',
                'modify_time' => '2018-07-24 13:44:17',
            ),
            19 => 
            array (
                'id' => 152,
                'task_id' => 1000207,
                'driver_id' => 5371,
                'unit_price' => '20.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '20.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 14:24:57',
                'modify_time' => '2018-07-24 14:24:57',
            ),
            20 => 
            array (
                'id' => 153,
                'task_id' => 1000209,
                'driver_id' => 5371,
                'unit_price' => '10.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '10.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-24 14:37:40',
                'modify_time' => '2018-07-24 14:37:40',
            ),
            21 => 
            array (
                'id' => 158,
                'task_id' => 1000232,
                'driver_id' => 5479,
                'unit_price' => '222.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '222.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 09:31:00',
                'modify_time' => '2018-07-25 09:31:00',
            ),
            22 => 
            array (
                'id' => 159,
                'task_id' => 1000235,
                'driver_id' => 5370,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '长期放假，不需要配送',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 09:59:47',
                'modify_time' => '2018-07-25 09:59:47',
            ),
            23 => 
            array (
                'id' => 160,
                'task_id' => 1000236,
                'driver_id' => 5370,
                'unit_price' => '254.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '254.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '长期放假，不需要配送',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 10:11:53',
                'modify_time' => '2018-07-25 10:11:53',
            ),
            24 => 
            array (
                'id' => 161,
                'task_id' => 1000237,
                'driver_id' => 5370,
                'unit_price' => '233.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '233.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 10:20:19',
                'modify_time' => '2018-07-25 10:20:19',
            ),
            25 => 
            array (
                'id' => 162,
                'task_id' => 1000238,
                'driver_id' => 5511,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '长期放假，不需要配送',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 10:31:16',
                'modify_time' => '2018-07-25 10:31:16',
            ),
            26 => 
            array (
                'id' => 163,
                'task_id' => 1000239,
                'driver_id' => 5511,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 10:48:04',
                'modify_time' => '2018-07-25 10:48:04',
            ),
            27 => 
            array (
                'id' => 164,
                'task_id' => 1000251,
                'driver_id' => 5503,
                'unit_price' => '500.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 12:17:46',
                'modify_time' => '2018-07-25 12:17:46',
            ),
            28 => 
            array (
                'id' => 165,
                'task_id' => 1000258,
                'driver_id' => 5371,
                'unit_price' => '20.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '20.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 13:46:33',
                'modify_time' => '2018-07-25 13:46:33',
            ),
            29 => 
            array (
                'id' => 166,
                'task_id' => 1000269,
                'driver_id' => 5405,
                'unit_price' => '200.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 15:06:16',
                'modify_time' => '2018-07-25 15:06:16',
            ),
            30 => 
            array (
                'id' => 167,
                'task_id' => 1000270,
                'driver_id' => 5405,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 15:11:59',
                'modify_time' => '2018-07-25 15:11:59',
            ),
            31 => 
            array (
                'id' => 168,
                'task_id' => 1000272,
                'driver_id' => 5371,
                'unit_price' => '2.01',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.01',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 15:22:11',
                'modify_time' => '2018-07-25 15:22:11',
            ),
            32 => 
            array (
                'id' => 169,
                'task_id' => 1000273,
                'driver_id' => 5503,
                'unit_price' => '380.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '380.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 15:28:20',
                'modify_time' => '2018-07-25 15:28:20',
            ),
            33 => 
            array (
                'id' => 171,
                'task_id' => 1000274,
                'driver_id' => 5405,
                'unit_price' => '450.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '450.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 15:35:27',
                'modify_time' => '2018-07-25 15:35:27',
            ),
            34 => 
            array (
                'id' => 172,
                'task_id' => 1000275,
                'driver_id' => 5391,
                'unit_price' => '360.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '360.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 15:40:23',
                'modify_time' => '2018-07-25 15:40:23',
            ),
            35 => 
            array (
                'id' => 173,
                'task_id' => 1000171,
                'driver_id' => 5405,
                'unit_price' => '450.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '450.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 18:17:37',
                'modify_time' => '2018-07-25 18:17:37',
            ),
            36 => 
            array (
                'id' => 175,
                'task_id' => 1000277,
                'driver_id' => 5404,
                'unit_price' => '250.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '250.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-25 18:20:51',
                'modify_time' => '2018-07-25 18:20:51',
            ),
            37 => 
            array (
                'id' => 177,
                'task_id' => 1000280,
                'driver_id' => 5391,
                'unit_price' => '360.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '360.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 09:19:15',
                'modify_time' => '2018-07-26 09:19:15',
            ),
            38 => 
            array (
                'id' => 178,
                'task_id' => 1000281,
                'driver_id' => 5424,
                'unit_price' => '350.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '350.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 09:19:45',
                'modify_time' => '2018-07-26 09:19:45',
            ),
            39 => 
            array (
                'id' => 179,
                'task_id' => 1000284,
                'driver_id' => 5526,
                'unit_price' => '650.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '650.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 09:42:23',
                'modify_time' => '2018-07-26 09:42:23',
            ),
            40 => 
            array (
                'id' => 180,
                'task_id' => 1000286,
                'driver_id' => 5371,
                'unit_price' => '2.01',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.01',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '长期放假，不需要配送',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 09:51:04',
                'modify_time' => '2018-07-26 09:51:04',
            ),
            41 => 
            array (
                'id' => 181,
                'task_id' => 1000291,
                'driver_id' => 5531,
                'unit_price' => '100.01',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.01',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 10:31:12',
                'modify_time' => '2018-07-26 10:31:12',
            ),
            42 => 
            array (
                'id' => 183,
                'task_id' => 1000295,
                'driver_id' => 5403,
                'unit_price' => '200.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 10:46:36',
                'modify_time' => '2018-07-26 10:46:36',
            ),
            43 => 
            array (
                'id' => 186,
                'task_id' => 1000297,
                'driver_id' => 5401,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 11:25:15',
                'modify_time' => '2018-07-26 11:25:15',
            ),
            44 => 
            array (
                'id' => 187,
                'task_id' => 1000302,
                'driver_id' => 5531,
                'unit_price' => '100.23',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.23',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 13:51:35',
                'modify_time' => '2018-07-26 13:51:35',
            ),
            45 => 
            array (
                'id' => 188,
                'task_id' => 1000303,
                'driver_id' => 5503,
                'unit_price' => '20.32',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '20.32',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 13:54:55',
                'modify_time' => '2018-07-26 13:54:55',
            ),
            46 => 
            array (
                'id' => 190,
                'task_id' => 1000305,
                'driver_id' => 5488,
                'unit_price' => '350.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '350.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 14:03:06',
                'modify_time' => '2018-07-26 14:03:06',
            ),
            47 => 
            array (
                'id' => 191,
                'task_id' => 1000309,
                'driver_id' => 5488,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 14:42:06',
                'modify_time' => '2018-07-26 14:42:06',
            ),
            48 => 
            array (
                'id' => 195,
                'task_id' => 1000314,
                'driver_id' => 5390,
                'unit_price' => '600.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '600.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 15:14:42',
                'modify_time' => '2018-07-26 15:14:42',
            ),
            49 => 
            array (
                'id' => 196,
                'task_id' => 1000313,
                'driver_id' => 5390,
                'unit_price' => '300.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '300.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 15:15:02',
                'modify_time' => '2018-07-26 15:15:02',
            ),
            50 => 
            array (
                'id' => 197,
                'task_id' => 1000316,
                'driver_id' => 5390,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '0.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 15:43:33',
                'modify_time' => '2018-07-26 15:43:33',
            ),
            51 => 
            array (
                'id' => 198,
                'task_id' => 1000317,
                'driver_id' => 5390,
                'unit_price' => '233.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '233.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 15:49:38',
                'modify_time' => '2018-07-26 15:49:38',
            ),
            52 => 
            array (
                'id' => 199,
                'task_id' => 1000318,
                'driver_id' => 5514,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '0.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 15:55:45',
                'modify_time' => '2018-07-26 15:55:45',
            ),
            53 => 
            array (
                'id' => 202,
                'task_id' => 1000320,
                'driver_id' => 5371,
                'unit_price' => '200.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 16:10:44',
                'modify_time' => '2018-07-26 16:10:44',
            ),
            54 => 
            array (
                'id' => 203,
                'task_id' => 1000322,
                'driver_id' => 5390,
                'unit_price' => '344.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '344.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 16:20:18',
                'modify_time' => '2018-07-26 16:20:18',
            ),
            55 => 
            array (
                'id' => 204,
                'task_id' => 1000323,
                'driver_id' => 5503,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '0.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '舟到系统变更司机',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 16:50:12',
                'modify_time' => '2018-07-26 16:50:12',
            ),
            56 => 
            array (
                'id' => 208,
                'task_id' => 1000323,
                'driver_id' => 5415,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '0.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 16:52:13',
                'modify_time' => '2018-07-26 16:52:13',
            ),
            57 => 
            array (
                'id' => 209,
                'task_id' => 1000324,
                'driver_id' => 5415,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '0.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 16:52:39',
                'modify_time' => '2018-07-26 16:52:39',
            ),
            58 => 
            array (
                'id' => 210,
                'task_id' => 1000331,
                'driver_id' => 5471,
                'unit_price' => '320.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '320.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-26 18:29:52',
                'modify_time' => '2018-07-26 18:29:52',
            ),
            59 => 
            array (
                'id' => 211,
                'task_id' => 1000341,
                'driver_id' => 5503,
                'unit_price' => '500.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-27 09:20:07',
                'modify_time' => '2018-07-27 09:20:07',
            ),
            60 => 
            array (
                'id' => 212,
                'task_id' => 1000355,
                'driver_id' => 5390,
                'unit_price' => '200.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-27 12:21:44',
                'modify_time' => '2018-07-27 12:21:44',
            ),
            61 => 
            array (
                'id' => 220,
                'task_id' => 1000356,
                'driver_id' => 5531,
                'unit_price' => '20.12',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '20.12',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-27 13:35:32',
                'modify_time' => '2018-07-27 13:35:32',
            ),
            62 => 
            array (
                'id' => 221,
                'task_id' => 1000370,
                'driver_id' => 5531,
                'unit_price' => '200.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-27 17:16:34',
                'modify_time' => '2018-07-27 17:16:34',
            ),
            63 => 
            array (
                'id' => 222,
                'task_id' => 1000376,
                'driver_id' => 5365,
                'unit_price' => '12.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '12.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '换仓库了',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-28 09:48:43',
                'modify_time' => '2018-07-28 09:48:43',
            ),
            64 => 
            array (
                'id' => 223,
                'task_id' => 1000377,
                'driver_id' => 5365,
                'unit_price' => '31.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '31.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-28 10:18:49',
                'modify_time' => '2018-07-28 10:18:49',
            ),
            65 => 
            array (
                'id' => 225,
                'task_id' => 1000378,
                'driver_id' => 5365,
                'unit_price' => '33.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '33.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-28 10:33:26',
                'modify_time' => '2018-07-28 10:33:26',
            ),
            66 => 
            array (
                'id' => 228,
                'task_id' => 1000381,
                'driver_id' => 5404,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '0.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '舟到系统变更司机',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-31 15:08:15',
                'modify_time' => '2018-07-31 15:08:15',
            ),
            67 => 
            array (
                'id' => 238,
                'task_id' => 1000381,
                'driver_id' => 5503,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '0.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-31 15:12:24',
                'modify_time' => '2018-07-31 15:12:24',
            ),
            68 => 
            array (
                'id' => 247,
                'task_id' => 1000382,
                'driver_id' => 5503,
                'unit_price' => '360.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '360.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '不需要配送了',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-31 15:23:39',
                'modify_time' => '2018-07-31 15:23:39',
            ),
            69 => 
            array (
                'id' => 249,
                'task_id' => 1000383,
                'driver_id' => 5503,
                'unit_price' => '100.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-07-31 15:31:24',
                'modify_time' => '2018-07-31 15:31:24',
            ),
            70 => 
            array (
                'id' => 250,
                'task_id' => 1000387,
                'driver_id' => 5503,
                'unit_price' => '773.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '773.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-08-04 11:21:41',
                'modify_time' => '2018-08-04 11:21:41',
            ),
            71 => 
            array (
                'id' => 251,
                'task_id' => 1000403,
                'driver_id' => 5390,
                'unit_price' => '77.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '77.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-08-14 16:15:20',
                'modify_time' => '2018-08-14 16:15:20',
            ),
            72 => 
            array (
                'id' => 254,
                'task_id' => 1000405,
                'driver_id' => 5390,
                'unit_price' => '65.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '65.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '换仓库了',
                'cancel_reason' => NULL,
                'create_time' => '2018-08-29 17:25:37',
                'modify_time' => '2018-08-29 17:25:37',
            ),
            73 => 
            array (
                'id' => 255,
                'task_id' => 1000406,
                'driver_id' => 5390,
                'unit_price' => '33.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '33.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-08-29 17:49:53',
                'modify_time' => '2018-08-29 17:49:53',
            ),
            74 => 
            array (
                'id' => 256,
                'task_id' => 1000407,
                'driver_id' => 5471,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-03 10:02:12',
                'modify_time' => '2018-09-03 10:02:12',
            ),
            75 => 
            array (
                'id' => 257,
                'task_id' => 1000408,
                'driver_id' => 5471,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-03 11:40:34',
                'modify_time' => '2018-09-03 11:40:34',
            ),
            76 => 
            array (
                'id' => 258,
                'task_id' => 1000409,
                'driver_id' => 5471,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '合并线路',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-03 11:44:59',
                'modify_time' => '2018-09-03 11:44:59',
            ),
            77 => 
            array (
                'id' => 264,
                'task_id' => 1000411,
                'driver_id' => 5394,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-04 17:40:05',
                'modify_time' => '2018-09-04 17:40:05',
            ),
            78 => 
            array (
                'id' => 265,
                'task_id' => 1000412,
                'driver_id' => 5390,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '舟到系统变更司机',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-04 17:40:05',
                'modify_time' => '2018-09-04 17:40:05',
            ),
            79 => 
            array (
                'id' => 267,
                'task_id' => 1000412,
                'driver_id' => 5534,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '舟到系统变更司机',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-04 17:43:06',
                'modify_time' => '2018-09-04 17:43:06',
            ),
            80 => 
            array (
                'id' => 272,
                'task_id' => 1000412,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '舟到系统变更司机',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-04 17:46:36',
                'modify_time' => '2018-09-04 17:46:36',
            ),
            81 => 
            array (
                'id' => 274,
                'task_id' => 1000412,
                'driver_id' => 5499,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-05 09:43:49',
                'modify_time' => '2018-09-05 09:43:49',
            ),
            82 => 
            array (
                'id' => 275,
                'task_id' => 1000413,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '换仓库了',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-05 09:44:14',
                'modify_time' => '2018-09-05 09:44:14',
            ),
            83 => 
            array (
                'id' => 278,
                'task_id' => 1000415,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '换仓库了',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-05 09:56:14',
                'modify_time' => '2018-09-05 09:56:14',
            ),
            84 => 
            array (
                'id' => 279,
                'task_id' => 1000416,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '换仓库了',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-05 11:27:38',
                'modify_time' => '2018-09-05 11:27:38',
            ),
            85 => 
            array (
                'id' => 282,
                'task_id' => 1000418,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-07 11:52:32',
                'modify_time' => '2018-09-07 11:52:32',
            ),
            86 => 
            array (
                'id' => 283,
                'task_id' => 1000419,
                'driver_id' => 5390,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-10 12:18:44',
                'modify_time' => '2018-09-10 12:18:44',
            ),
            87 => 
            array (
                'id' => 284,
                'task_id' => 1000420,
                'driver_id' => 5499,
                'unit_price' => '500.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-12 10:58:48',
                'modify_time' => '2018-09-12 10:58:48',
            ),
            88 => 
            array (
                'id' => 287,
                'task_id' => 1000421,
                'driver_id' => 5423,
                'unit_price' => '300.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '300.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-12 11:04:34',
                'modify_time' => '2018-09-12 11:04:34',
            ),
            89 => 
            array (
                'id' => 288,
                'task_id' => 1000422,
                'driver_id' => 5471,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-12 11:37:01',
                'modify_time' => '2018-09-12 11:37:01',
            ),
            90 => 
            array (
                'id' => 289,
                'task_id' => 1000423,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-12 11:41:25',
                'modify_time' => '2018-09-12 11:41:25',
            ),
            91 => 
            array (
                'id' => 290,
                'task_id' => 1000424,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '合并线路',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-12 14:18:45',
                'modify_time' => '2018-09-12 14:18:45',
            ),
            92 => 
            array (
                'id' => 291,
                'task_id' => 1000425,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '合并线路',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-12 16:18:41',
                'modify_time' => '2018-09-12 16:18:41',
            ),
            93 => 
            array (
                'id' => 294,
                'task_id' => 1000426,
                'driver_id' => 5534,
                'unit_price' => '2.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '2.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-14 11:40:58',
                'modify_time' => '2018-09-14 11:40:58',
            ),
            94 => 
            array (
                'id' => 295,
                'task_id' => 1000428,
                'driver_id' => 5422,
                'unit_price' => '110.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '110.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-14 15:10:49',
                'modify_time' => '2018-09-14 15:10:49',
            ),
            95 => 
            array (
                'id' => 296,
                'task_id' => 1000429,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 2,
                'rescind_reason' => '撤线',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-14 16:45:02',
                'modify_time' => '2018-09-14 16:45:02',
            ),
            96 => 
            array (
                'id' => 297,
                'task_id' => 1000430,
                'driver_id' => 5519,
                'unit_price' => '50.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '50.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-14 17:00:15',
                'modify_time' => '2018-09-14 17:00:15',
            ),
            97 => 
            array (
                'id' => 298,
                'task_id' => 1000432,
                'driver_id' => 5423,
                'unit_price' => '350.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '350.00',
                'remark' => '舟到系统指派司机',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-17 19:02:45',
                'modify_time' => '2018-09-17 19:02:45',
            ),
            98 => 
            array (
                'id' => 299,
                'task_id' => 1001000,
                'driver_id' => 5534,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:28:21',
                'modify_time' => '2018-09-26 11:28:21',
            ),
            99 => 
            array (
                'id' => 300,
                'task_id' => 1000432,
                'driver_id' => 5526,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:28:21',
                'modify_time' => '2018-09-26 11:28:21',
            ),
            100 => 
            array (
                'id' => 301,
                'task_id' => 1000432,
                'driver_id' => 5519,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:28:21',
                'modify_time' => '2018-09-26 11:28:21',
            ),
            101 => 
            array (
                'id' => 435,
                'task_id' => 1001145,
                'driver_id' => 5488,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:46:01',
                'modify_time' => '2018-09-26 11:46:01',
            ),
            102 => 
            array (
                'id' => 436,
                'task_id' => 1001145,
                'driver_id' => 5486,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:46:14',
                'modify_time' => '2018-09-26 11:46:14',
            ),
            103 => 
            array (
                'id' => 437,
                'task_id' => 1001145,
                'driver_id' => 5491,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '200.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:46:14',
                'modify_time' => '2018-09-26 11:46:14',
            ),
            104 => 
            array (
                'id' => 536,
                'task_id' => 1001285,
                'driver_id' => 5526,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:50:34',
                'modify_time' => '2018-09-26 11:50:34',
            ),
            105 => 
            array (
                'id' => 537,
                'task_id' => 1001286,
                'driver_id' => 5519,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '500.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:50:34',
                'modify_time' => '2018-09-26 11:50:34',
            ),
            106 => 
            array (
                'id' => 538,
                'task_id' => 1001287,
                'driver_id' => 5454,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:51:11',
                'modify_time' => '2018-09-26 11:51:11',
            ),
            107 => 
            array (
                'id' => 539,
                'task_id' => 1001288,
                'driver_id' => 5440,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:51:11',
                'modify_time' => '2018-09-26 11:51:11',
            ),
            108 => 
            array (
                'id' => 540,
                'task_id' => 1001289,
                'driver_id' => 5437,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:51:11',
                'modify_time' => '2018-09-26 11:51:11',
            ),
            109 => 
            array (
                'id' => 541,
                'task_id' => 1001290,
                'driver_id' => 5436,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '100.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-09-26 11:51:11',
                'modify_time' => '2018-09-26 11:51:11',
            ),
            110 => 
            array (
                'id' => 542,
                'task_id' => 1001293,
                'driver_id' => 5534,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '12.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-10-10 14:33:30',
                'modify_time' => '2018-10-10 14:33:30',
            ),
            111 => 
            array (
                'id' => 543,
                'task_id' => 1001294,
                'driver_id' => 5527,
                'unit_price' => '0.00',
                'percentage' => '0.0',
                'manage_fee' => '0.00',
                'driver_income_fee' => '66.00',
                'remark' => '',
                'status' => 1,
                'rescind_reason' => '',
                'cancel_reason' => NULL,
                'create_time' => '2018-10-10 14:34:44',
                'modify_time' => '2018-10-10 14:34:44',
            ),
        ));
        
        
    }
}