<?php

use Illuminate\Database\Seeder;

class ZdWarehouseTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('zd_warehouse')->delete();
        
        \DB::table('zd_warehouse')->insert(array (
            0 => 
            array (
                'id' => 101,
                'merchant_id' => 101,
                'title' => '南北长',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '李小明',
                'contacts_phone' => '13223232541',
                'backup_contacts' => '["",""]',
                'address' => '广东省深圳市南山区粤海街道中洲控股中心',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.93364,
                'latitude' => 22.51736,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2017-11-09 16:08:49',
                'modify_time' => '2018-07-06 17:20:18',
            ),
            1 => 
            array (
                'id' => 102,
                'merchant_id' => 101,
                'title' => '福看看',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440304',
                'category_zone' => '广东省 深圳市 福田区',
                'contacts' => '阿福',
                'contacts_phone' => '13566667777',
                'backup_contacts' => '["",""]',
            'address' => '广东省深圳市福田区福保街道福民路194号中石油碧辟加油站(石厦北三街)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 114.054309,
                'latitude' => 22.523347,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2017-11-09 16:37:07',
                'modify_time' => '2018-07-23 19:55:10',
            ),
            2 => 
            array (
                'id' => 103,
                'merchant_id' => 101,
                'title' => '罗湖',
                'category_position' => 'tr_0 tr_440000 tr_441900 tr_441901003',
                'category_zone' => '广东省 东莞市 东城街道',
                'contacts' => '李四',
                'contacts_phone' => '13562545632',
                'backup_contacts' => '["",""]',
                'address' => '广东省深圳市罗湖区黄贝街道文锦南路鸿昌广场',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 114.13104,
                'latitude' => 22.544133,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2017-11-09 16:38:56',
                'modify_time' => '2018-07-06 17:12:29',
            ),
            3 => 
            array (
                'id' => 104,
                'merchant_id' => 102,
                'title' => '林仓管',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440303',
                'category_zone' => '广东省 深圳市 罗湖区',
                'contacts' => '我管仓',
                'contacts_phone' => '15220147496',
                'backup_contacts' => '["",""]',
                'address' => 'D多平真',
                'description' => '当代东方的冯绍峰',
                'instruction' => '发顺丰第三方斯蒂芬',
                'longitude' => 114.082554,
                'latitude' => 22.537319,
                'remark' => '发顺丰微风无法',
                'status' => 1,
                'create_time' => '2017-11-16 10:32:04',
                'modify_time' => '2017-11-16 10:32:04',
            ),
            4 => 
            array (
                'id' => 106,
                'merchant_id' => 102,
                'title' => '测试仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440304',
                'category_zone' => '广东省 深圳市 福田区',
                'contacts' => '曾祥浩',
                'contacts_phone' => '13266522726',
                'backup_contacts' => '["",""]',
            'address' => '车公庙(地铁站)',
                'description' => '',
                'instruction' => '',
                'longitude' => 114.02583,
                'latitude' => 22.536247,
                'remark' => '',
                'status' => 1,
                'create_time' => '2017-11-16 11:15:32',
                'modify_time' => '2017-11-16 11:15:32',
            ),
            5 => 
            array (
                'id' => 107,
                'merchant_id' => 103,
                'title' => '商惠民仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440323',
                'category_zone' => '广东省 深圳市 龙华新区',
                'contacts' => '尔尔',
                'contacts_phone' => '13798278743',
                'backup_contacts' => '["",""]',
                'address' => '鹏华工业园',
                'description' => '中商惠民仓库',
                'instruction' => '',
                'longitude' => 114.005731,
                'latitude' => 22.639162,
                'remark' => '',
                'status' => 1,
                'create_time' => '2017-12-11 16:14:16',
                'modify_time' => '2017-12-13 11:37:07',
            ),
            6 => 
            array (
                'id' => 108,
                'merchant_id' => 105,
                'title' => '南山排线',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '测试',
                'contacts_phone' => '13682509527',
                'backup_contacts' => '["13682509527","显示"]',
                'address' => '012312',
                'description' => '',
                'instruction' => '',
                'longitude' => 113.934096,
                'latitude' => 22.517679,
                'remark' => '',
                'status' => 1,
                'create_time' => '2017-12-15 14:39:03',
                'modify_time' => '2018-07-04 14:02:02',
            ),
            7 => 
            array (
                'id' => 109,
                'merchant_id' => 105,
            'title' => '莲花北(地铁站)',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440304',
                'category_zone' => '广东省 深圳市 福田区',
                'contacts' => 'test',
                'contacts_phone' => '13900000000',
                'backup_contacts' => '["",""]',
            'address' => '莲花北(地铁站)',
                'description' => '',
                'instruction' => '',
                'longitude' => 114.059402,
                'latitude' => 22.560538,
                'remark' => '',
                'status' => 1,
                'create_time' => '2017-12-16 10:06:18',
                'modify_time' => '2017-12-16 10:06:18',
            ),
            8 => 
            array (
                'id' => 110,
                'merchant_id' => 106,
                'title' => '停车费',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440304',
                'category_zone' => '广东省 深圳市 福田区',
                'contacts' => '1234',
                'contacts_phone' => '13555556666',
                'backup_contacts' => '["",""]',
                'address' => '莲花山公园',
                'description' => '',
                'instruction' => '',
                'longitude' => 114.058572,
                'latitude' => 22.553523,
                'remark' => '',
                'status' => 1,
                'create_time' => '2017-12-19 14:02:01',
                'modify_time' => '2017-12-19 14:02:01',
            ),
            9 => 
            array (
                'id' => 111,
                'merchant_id' => 107,
                'title' => '超 人',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '233',
                'contacts_phone' => '13450000000',
                'backup_contacts' => '["",""]',
            'address' => '南山(地铁站)',
                'description' => '是辅导书方法',
                'instruction' => '啊啊啊啊啊啊啊反反复复付付',
                'longitude' => 113.923596,
                'latitude' => 22.524022,
                'remark' => '',
                'status' => 1,
                'create_time' => '2017-12-19 14:33:32',
                'modify_time' => '2017-12-19 14:33:32',
            ),
            10 => 
            array (
                'id' => 112,
                'merchant_id' => 110,
                'title' => '仓库4',
                'category_position' => 'tr_0 tr_440000 tr_442000 tr_442001001',
                'category_zone' => '广东省 中山市 石岐区街道',
                'contacts' => '，哦，默',
                'contacts_phone' => '18676349856',
                'backup_contacts' => '',
                'address' => '夜市街',
                'description' => '公共',
                'instruction' => '红了',
                'longitude' => 113.25567,
                'latitude' => 22.690905,
                'remark' => '啦啦噜',
                'status' => 1,
                'create_time' => '2018-07-05 09:51:01',
                'modify_time' => '2018-07-06 15:38:05',
            ),
            11 => 
            array (
                'id' => 113,
                'merchant_id' => 109,
                'title' => '流量用',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省中山市石岐区街道',
                'contacts' => '离开了',
                'contacts_phone' => '15012814913',
                'backup_contacts' => '',
                'address' => '东莞植物园东莞植物园',
                'description' => '图文信息',
                'instruction' => '天助自助者',
                'longitude' => 113.747687,
                'latitude' => 22.967355,
                'remark' => '录取了',
                'status' => 1,
                'create_time' => '2018-07-05 10:12:15',
                'modify_time' => '2018-07-09 09:20:57',
            ),
            12 => 
            array (
                'id' => 114,
                'merchant_id' => 111,
                'title' => '妹子仓',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '134',
                'contacts_phone' => '13416666666',
                'backup_contacts' => '',
            'address' => '白石洲(地铁站)白石洲(地铁站)',
                'description' => '摩卡困Elly哦哪里spit',
                'instruction' => 'took不YY',
                'longitude' => 113.967048,
                'latitude' => 22.539604,
                'remark' => '闷闷',
                'status' => 1,
                'create_time' => '2018-07-05 10:44:21',
                'modify_time' => '2018-07-05 10:44:21',
            ),
            13 => 
            array (
                'id' => 115,
                'merchant_id' => 108,
                'title' => '深圳南山仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440303',
                'category_zone' => '广东省 深圳市 罗湖区',
                'contacts' => '天天',
                'contacts_phone' => '13012345678',
                'backup_contacts' => '',
                'address' => '地王大厦',
                'description' => '地铁站',
                'instruction' => '122333',
                'longitude' => 114.109938,
                'latitude' => 22.542393,
                'remark' => '仓库不能太多货品',
                'status' => 1,
                'create_time' => '2018-07-05 14:36:43',
                'modify_time' => '2018-07-05 14:36:43',
            ),
            14 => 
            array (
                'id' => 116,
                'merchant_id' => 108,
                'title' => '福田仓库1',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440303',
                'category_zone' => '广东省 深圳市 罗湖区',
                'contacts' => '听听',
                'contacts_phone' => '13411111111',
                'backup_contacts' => '',
            'address' => '福田(地铁站)',
                'description' => '地铁站',
                'instruction' => '123456',
                'longitude' => 114.052879,
                'latitude' => 22.540087,
                'remark' => '哈哈哈哈哈哈',
                'status' => 1,
                'create_time' => '2018-07-06 11:14:02',
                'modify_time' => '2018-07-07 10:25:26',
            ),
            15 => 
            array (
                'id' => 117,
                'merchant_id' => 110,
                'title' => '深圳仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440303',
                'category_zone' => '广东省 深圳市 罗湖区',
                'contacts' => '条条',
                'contacts_phone' => '13111141111',
                'backup_contacts' => '',
            'address' => '南山(地铁站)',
                'description' => '南山地铁站',
                'instruction' => '去地铁站',
                'longitude' => 113.923596,
                'latitude' => 22.524022,
                'remark' => '仓库备注',
                'status' => 1,
                'create_time' => '2018-07-06 12:05:49',
                'modify_time' => '2018-07-06 12:05:49',
            ),
            16 => 
            array (
                'id' => 118,
                'merchant_id' => 111,
                'title' => '新建',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '接你啊',
                'contacts_phone' => '13465976764',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座中洲控股中心A座',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-06 14:23:52',
                'modify_time' => '2018-07-06 14:23:52',
            ),
            17 => 
            array (
                'id' => 119,
                'merchant_id' => 108,
                'title' => '南山仓库2',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '天天',
                'contacts_phone' => '13166666666',
                'backup_contacts' => '',
                'address' => '后海地铁站D1口',
                'description' => '中洲大厦',
                'instruction' => '有电梯',
                'longitude' => 113.939996,
                'latitude' => 22.517732,
                'remark' => '啊啊可口可乐了可口可乐',
                'status' => 1,
                'create_time' => '2018-07-09 09:23:26',
                'modify_time' => '2018-07-09 09:23:26',
            ),
            18 => 
            array (
                'id' => 120,
                'merchant_id' => 112,
                'title' => '设备撒',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440303',
                'category_zone' => '广东省 深圳市 罗湖区',
                'contacts' => '第三方',
                'contacts_phone' => '13266522726',
                'backup_contacts' => '["13266522726","小程序"]',
                'address' => '哈哈哈2元店',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.790239,
                'latitude' => 22.743598,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-09 13:45:22',
                'modify_time' => '2018-07-17 14:43:49',
            ),
            19 => 
            array (
                'id' => 121,
                'merchant_id' => 109,
                'title' => '仓鼠',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '聂树斌',
                'contacts_phone' => '13461949966',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座中洲控股中心A座',
                'description' => '啦啦啦啦啦啦',
                'instruction' => 'lol哦咯',
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '咩酷狗',
                'status' => 1,
                'create_time' => '2018-07-09 14:21:33',
                'modify_time' => '2018-07-09 14:21:33',
            ),
            20 => 
            array (
                'id' => 122,
                'merchant_id' => 110,
                'title' => '南山中州',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '天天',
                'contacts_phone' => '13112345678',
                'backup_contacts' => '',
                'address' => '中洲控股中心中洲控股中心',
                'description' => '后悔地铁站',
                'instruction' => '123',
                'longitude' => 113.933665,
                'latitude' => 22.517327,
                'remark' => '仓库',
                'status' => 1,
                'create_time' => '2018-07-10 09:49:32',
                'modify_time' => '2018-07-10 09:49:32',
            ),
            21 => 
            array (
                'id' => 123,
                'merchant_id' => 108,
                'title' => 'ios南山中洲仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '天天',
                'contacts_phone' => '13162955555',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座',
                'description' => '后海',
                'instruction' => NULL,
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '1',
                'status' => 1,
                'create_time' => '2018-07-10 09:59:04',
                'modify_time' => '2018-07-10 09:59:04',
            ),
            22 => 
            array (
                'id' => 124,
                'merchant_id' => 109,
                'title' => '中秋佳节',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '干部处',
                'contacts_phone' => '13416363633',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座中洲控股中心A座',
                'description' => '看看',
                'instruction' => '么咯一起',
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '也看过',
                'status' => 1,
                'create_time' => '2018-07-10 16:58:14',
                'modify_time' => '2018-07-10 16:58:14',
            ),
            23 => 
            array (
                'id' => 125,
                'merchant_id' => 108,
                'title' => '临时仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '天天',
                'contacts_phone' => '15919408756',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座',
                'description' => '地铁',
                'instruction' => '地铁站',
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '天天',
                'status' => 1,
                'create_time' => '2018-07-11 14:24:32',
                'modify_time' => '2018-07-11 14:24:32',
            ),
            24 => 
            array (
                'id' => 126,
                'merchant_id' => 110,
                'title' => 'Gfgfg',
                'category_position' => 'tr_0 tr_440000 tr_441900 tr_441901003',
                'category_zone' => '广东省 东莞市 东城街道',
                'contacts' => 'Fdfd',
                'contacts_phone' => '19898989434',
                'backup_contacts' => '',
                'address' => '东莞市科学技术局',
                'description' => 'Dfdfd',
                'instruction' => 'Fdfdf',
                'longitude' => 113.761647,
                'latitude' => 23.024552,
                'remark' => 'Fdfde',
                'status' => 1,
                'create_time' => '2018-07-16 11:40:54',
                'modify_time' => '2018-07-16 11:40:54',
            ),
            25 => 
            array (
                'id' => 127,
                'merchant_id' => 112,
                'title' => '啦啦',
                'category_position' => 'tr_0 tr_440000 tr_442101',
                'category_zone' => '广东省 东沙群岛',
                'contacts' => '啦啦',
                'contacts_phone' => '13138151031',
                'backup_contacts' => '',
                'address' => '宝安区',
                'description' => '啦啦',
                'instruction' => '啦啦',
                'longitude' => 113.88402,
                'latitude' => 22.555259,
                'remark' => '啦啦',
                'status' => 1,
                'create_time' => '2018-07-16 17:21:20',
                'modify_time' => '2018-07-16 17:21:20',
            ),
            26 => 
            array (
                'id' => 128,
                'merchant_id' => 112,
                'title' => '啦啦',
                'category_position' => 'tr_0 tr_440000 tr_442101',
                'category_zone' => '广东省 东沙群岛',
                'contacts' => '啦啦',
                'contacts_phone' => '13138151031',
                'backup_contacts' => '',
                'address' => '啦啦吧',
                'description' => '啦啦',
                'instruction' => '啦啦',
                'longitude' => 109.628802,
                'latitude' => 18.226105,
                'remark' => '啦啦',
                'status' => 1,
                'create_time' => '2018-07-16 17:25:10',
                'modify_time' => '2018-07-16 17:25:10',
            ),
            27 => 
            array (
                'id' => 129,
                'merchant_id' => 112,
                'title' => '啦啦',
                'category_position' => 'tr_0 tr_440000 tr_442101',
                'category_zone' => '广东省 东沙群岛',
                'contacts' => '啦啦',
                'contacts_phone' => '13138181031',
                'backup_contacts' => '',
                'address' => '啦啦吧',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 109.628802,
                'latitude' => 18.226105,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-16 17:54:44',
                'modify_time' => '2018-07-16 17:54:44',
            ),
            28 => 
            array (
                'id' => 130,
                'merchant_id' => 112,
                'title' => '硅谷',
                'category_position' => 'tr_0 tr_440000 tr_442101',
                'category_zone' => '广东省 东沙群岛',
                'contacts' => '哈哈',
                'contacts_phone' => '13138151031',
                'backup_contacts' => '',
            'address' => '哈哈镜(红旗路总店)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 87.61706,
                'latitude' => 43.795419,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-17 14:43:25',
                'modify_time' => '2018-07-17 14:43:25',
            ),
            29 => 
            array (
                'id' => 131,
                'merchant_id' => 112,
                'title' => '滚滚滚',
                'category_position' => 'tr_0 tr_440000 tr_442101',
                'category_zone' => '广东省 东沙群岛',
                'contacts' => '1313815103',
                'contacts_phone' => '13138151031',
                'backup_contacts' => '',
                'address' => '哈哈不锈钢门闸厂',
                'description' => '1441111',
                'instruction' => NULL,
                'longitude' => 106.511333,
                'latitude' => 29.583541,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-17 14:45:01',
                'modify_time' => '2018-07-27 10:20:05',
            ),
            30 => 
            array (
                'id' => 132,
                'merchant_id' => 109,
                'title' => '美丽西部数据',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市罗湖区',
                'contacts' => '白vv红',
                'contacts_phone' => '13266522726',
                'backup_contacts' => '',
                'address' => '深圳市罗湖中学深圳市罗湖中学',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 114.123097,
                'latitude' => 22.535977,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-17 14:49:17',
                'modify_time' => '2018-07-17 14:49:17',
            ),
            31 => 
            array (
                'id' => 133,
                'merchant_id' => 112,
                'title' => '规划局',
                'category_position' => 'tr_0 tr_440000 tr_442101',
                'category_zone' => '广东省 东沙群岛',
                'contacts' => '1313815103',
                'contacts_phone' => '13058180596',
                'backup_contacts' => '',
                'address' => '哈哈',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 102.09539,
                'latitude' => 28.509207,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-17 14:51:17',
                'modify_time' => '2018-07-17 14:51:17',
            ),
            32 => 
            array (
                'id' => 134,
                'merchant_id' => 111,
                'title' => '加我微信YY兔兔V5',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省中山市石岐区街道',
                'contacts' => '陈阳',
                'contacts_phone' => '15012814913',
                'backup_contacts' => '',
                'address' => '高雅轩名门高雅轩名门',
                'description' => '默默',
                'instruction' => '通知一下',
                'longitude' => 113.431812,
                'latitude' => 22.344173,
                'remark' => '通知一下',
                'status' => 1,
                'create_time' => '2018-07-19 09:25:31',
                'modify_time' => '2018-07-19 09:25:31',
            ),
            33 => 
            array (
                'id' => 135,
                'merchant_id' => 114,
                'title' => '世界之窗',
                'category_position' => 'tr_0 tr_440000 tr_445300 tr_445302',
                'category_zone' => '广东省 云浮市 云城区',
                'contacts' => '1382323896',
                'contacts_phone' => '13823238961',
                'backup_contacts' => '',
            'address' => '地税局(公交站)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 111.56488,
                'latitude' => 22.752188,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-23 13:59:31',
                'modify_time' => '2018-07-23 13:59:31',
            ),
            34 => 
            array (
                'id' => 136,
                'merchant_id' => 113,
                'title' => '南山仓',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '李先生',
                'contacts_phone' => '13510525635',
                'backup_contacts' => '',
            'address' => '白石洲(公交站)白石洲(公交站)',
                'description' => '白石洲',
                'instruction' => '白石洲地铁口附近',
                'longitude' => 113.968773,
                'latitude' => 22.53944,
                'remark' => '仓库在路边上',
                'status' => 1,
                'create_time' => '2018-07-23 14:29:52',
                'modify_time' => '2018-07-23 14:29:52',
            ),
            35 => 
            array (
                'id' => 137,
                'merchant_id' => 110,
                'title' => '测试南山仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '天天',
                'contacts_phone' => '15919408756',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座',
                'description' => '后海地铁站',
                'instruction' => '红绿灯',
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '仓库很多',
                'status' => 1,
                'create_time' => '2018-07-23 15:03:46',
                'modify_time' => '2018-07-23 15:03:46',
            ),
            36 => 
            array (
                'id' => 138,
                'merchant_id' => 115,
                'title' => '白石洲',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '袁',
                'contacts_phone' => '13716945731',
                'backup_contacts' => '',
            'address' => '白石洲(地铁站)白石洲(地铁站)',
                'description' => '中信花园',
                'instruction' => NULL,
                'longitude' => 113.967048,
                'latitude' => 22.539604,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-23 15:19:02',
                'modify_time' => '2018-07-23 15:19:02',
            ),
            37 => 
            array (
                'id' => 139,
                'merchant_id' => 120,
                'title' => '监控',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省东莞市东城街道',
                'contacts' => '陈杨',
                'contacts_phone' => '15012814913',
                'backup_contacts' => '',
                'address' => '深圳北站深圳北站',
                'description' => '龙门',
                'instruction' => '龙门',
                'longitude' => 114.029113,
                'latitude' => 22.609725,
                'remark' => '监控',
                'status' => 1,
                'create_time' => '2018-07-23 16:13:34',
                'modify_time' => '2018-07-23 16:13:34',
            ),
            38 => 
            array (
                'id' => 145,
                'merchant_id' => 102,
                'title' => '萝莉控',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440303',
                'category_zone' => '广东省 深圳市 罗湖区',
                'contacts' => '冷落了',
                'contacts_phone' => '13265522726',
                'backup_contacts' => '',
            'address' => '罗湖(地铁站)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 114.118666,
                'latitude' => 22.532083,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-24 11:55:40',
                'modify_time' => '2018-07-24 11:55:40',
            ),
            39 => 
            array (
                'id' => 153,
                'merchant_id' => 102,
                'title' => '哈哈哈',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省东沙群岛',
                'contacts' => '哈哈哈',
                'contacts_phone' => '15012814913',
                'backup_contacts' => '',
                'address' => '恐龙寺恐龙寺',
                'description' => '龙门',
                'instruction' => '空间',
                'longitude' => 103.172904,
                'latitude' => 30.251223,
                'remark' => '通知一下',
                'status' => 1,
                'create_time' => '2018-07-24 11:58:15',
                'modify_time' => '2018-07-24 11:58:15',
            ),
            40 => 
            array (
                'id' => 154,
                'merchant_id' => 102,
                'title' => '哈哈哈',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省东沙群岛',
                'contacts' => '哈哈哈',
                'contacts_phone' => '15012814913',
                'backup_contacts' => '',
                'address' => '恐龙寺恐龙寺',
                'description' => '龙门',
                'instruction' => '空间',
                'longitude' => 103.172904,
                'latitude' => 30.251223,
                'remark' => '通知一下',
                'status' => 1,
                'create_time' => '2018-07-24 11:58:19',
                'modify_time' => '2018-07-24 11:58:19',
            ),
            41 => 
            array (
                'id' => 155,
                'merchant_id' => 113,
                'title' => '银湖仓',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440304',
                'category_zone' => '广东省 深圳市 福田区',
                'contacts' => '张三',
                'contacts_phone' => '13510525635',
                'backup_contacts' => '',
                'address' => '深圳北站',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 114.029113,
                'latitude' => 22.609725,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-24 14:57:00',
                'modify_time' => '2018-07-24 14:57:00',
            ),
            42 => 
            array (
                'id' => 156,
                'merchant_id' => 129,
                'title' => '龙华店',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市罗湖区',
                'contacts' => '二',
                'contacts_phone' => '13536363636',
                'backup_contacts' => '',
                'address' => '原来是美食坊原来是美食坊',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.82318,
                'latitude' => 22.732736,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-24 16:16:55',
                'modify_time' => '2018-07-24 16:16:55',
            ),
            43 => 
            array (
                'id' => 157,
                'merchant_id' => 113,
                'title' => '罗湖仓',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '张三',
                'contacts_phone' => '13510525635',
                'backup_contacts' => '',
            'address' => '白石洲(地铁站)白石洲(地铁站)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.967048,
                'latitude' => 22.539604,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-24 18:33:41',
                'modify_time' => '2018-07-24 18:33:41',
            ),
            44 => 
            array (
                'id' => 158,
                'merchant_id' => 130,
                'title' => '南山仓',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440304',
                'category_zone' => '广东省 深圳市 福田区',
                'contacts' => '张三',
                'contacts_phone' => '13510525635',
                'backup_contacts' => '',
            'address' => '南山区委(公交站)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.926758,
                'latitude' => 22.532404,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-25 14:30:35',
                'modify_time' => '2018-07-25 14:30:35',
            ),
            45 => 
            array (
                'id' => 159,
                'merchant_id' => 129,
                'title' => '龙岗平湖分店牒',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省云浮市云城区',
                'contacts' => '何必呢',
                'contacts_phone' => '15235758425',
                'backup_contacts' => '',
                'address' => '献给你献给你',
                'description' => '啊啊啊月底前',
                'instruction' => '',
                'longitude' => 112.231174,
                'latitude' => 22.690126,
                'remark' => '',
                'status' => 1,
                'create_time' => '2018-07-25 14:38:08',
                'modify_time' => '2018-07-25 15:28:03',
            ),
            46 => 
            array (
                'id' => 163,
                'merchant_id' => 132,
                'title' => '南山仓',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '张三',
                'contacts_phone' => '13566667777',
                'backup_contacts' => '',
                'address' => '白石洲地铁站A口',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.967899,
                'latitude' => 22.539824,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-25 15:26:42',
                'modify_time' => '2018-07-25 15:26:42',
            ),
            47 => 
            array (
                'id' => 164,
                'merchant_id' => 115,
                'title' => '深圳市南山区白石洲',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '袁书芳',
                'contacts_phone' => '13716945731',
                'backup_contacts' => '',
            'address' => '白石洲(地铁站)白石洲(地铁站)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.967048,
                'latitude' => 22.539604,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-26 09:32:48',
                'modify_time' => '2018-07-26 09:32:48',
            ),
            48 => 
            array (
                'id' => 165,
                'merchant_id' => 115,
                'title' => '深圳市南山区白石洲',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '袁书芳',
                'contacts_phone' => '13716945731',
                'backup_contacts' => '',
            'address' => '白石洲(地铁站)白石洲(地铁站)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.967048,
                'latitude' => 22.539604,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-26 09:32:48',
                'modify_time' => '2018-07-26 09:32:48',
            ),
            49 => 
            array (
                'id' => 166,
                'merchant_id' => 115,
                'title' => '深圳市南山区白石洲深',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省深圳市南山区',
                'contacts' => '袁书芳',
                'contacts_phone' => '13716945731',
                'backup_contacts' => '',
                'address' => '世界之窗世界之窗',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.972976,
                'latitude' => 22.534607,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-26 09:35:48',
                'modify_time' => '2018-07-26 09:35:48',
            ),
            50 => 
            array (
                'id' => 167,
                'merchant_id' => 113,
                'title' => '福利彩票仓库南山',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440303',
                'category_zone' => '广东省 深圳市 罗湖区',
                'contacts' => '张三',
                'contacts_phone' => '13510525635',
                'backup_contacts' => '',
            'address' => '南山(地铁站)',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 113.923596,
                'latitude' => 22.524022,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-07-26 09:36:20',
                'modify_time' => '2018-07-26 09:36:20',
            ),
            51 => 
            array (
                'id' => 168,
                'merchant_id' => 102,
                'title' => '同我讲监控哦哦咯哦',
                'category_position' => 'tr_0 tr_',
                'category_zone' => '广东省-东莞市-南城街道',
                'contacts' => '陈杨',
                'contacts_phone' => '15012814913',
                'backup_contacts' => '',
            'address' => '白丽人(乌沙分店)',
                'description' => '咯www',
                'instruction' => '通知一下',
                'longitude' => 113.791272,
                'latitude' => 22.79134,
                'remark' => '恐龙妹',
                'status' => 1,
                'create_time' => '2018-07-26 10:29:51',
                'modify_time' => '2018-07-26 11:13:06',
            ),
            52 => 
            array (
                'id' => 169,
                'merchant_id' => 108,
                'title' => '7.26主仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '天天',
                'contacts_phone' => '13112345678',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座',
                'description' => '后海地铁站',
                'instruction' => '红绿灯',
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '哈哈哈哈哈哈哈哈哈',
                'status' => 1,
                'create_time' => '2018-07-26 10:44:01',
                'modify_time' => '2018-07-26 10:44:01',
            ),
            53 => 
            array (
                'id' => 170,
                'merchant_id' => 113,
                'title' => '南山仓',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '张三',
                'contacts_phone' => '15611112222',
                'backup_contacts' => '',
            'address' => '广东省深圳市南山区白石洲(地铁站)',
                'description' => '',
                'instruction' => '',
                'longitude' => 113.967048,
                'latitude' => 22.539604,
                'remark' => '',
                'status' => 1,
                'create_time' => '2018-07-26 15:05:11',
                'modify_time' => '2018-07-26 15:05:11',
            ),
            54 => 
            array (
                'id' => 171,
                'merchant_id' => 108,
                'title' => '30测试仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440304',
                'category_zone' => '广东省 深圳市 福田区',
                'contacts' => '天天',
                'contacts_phone' => '13112345678',
                'backup_contacts' => '',
                'address' => '中洲控股中心A座',
                'description' => '路途',
                'instruction' => '路程123',
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '测试仓库',
                'status' => 1,
                'create_time' => '2018-07-27 12:20:17',
                'modify_time' => '2018-07-27 12:20:17',
            ),
            55 => 
            array (
                'id' => 172,
                'merchant_id' => 110,
                'title' => '福田仓',
                'category_position' => 'tr_0 tr_440000 tr_442101',
                'category_zone' => '广东省 东沙群岛',
                'contacts' => '张亮',
                'contacts_phone' => '13225720391',
                'backup_contacts' => '',
                'address' => '宁波大学',
                'description' => '木楼',
                'instruction' => '福田地铁站',
                'longitude' => 121.637491,
                'latitude' => 29.908471,
                'remark' => '大仓库',
                'status' => 1,
                'create_time' => '2018-07-27 15:53:24',
                'modify_time' => '2018-07-27 15:54:44',
            ),
            56 => 
            array (
                'id' => 173,
                'merchant_id' => 129,
                'title' => '大布头仓库',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440323',
                'category_zone' => '广东省 深圳市 龙华新区',
                'contacts' => '邓小华',
                'contacts_phone' => '13537580621',
                'backup_contacts' => '',
                'address' => '广东省深圳市龙华区环观中路108号',
                'description' => '方舟来拉观澜分公司',
                'instruction' => '',
                'longitude' => 114.064755,
                'latitude' => 22.703831,
                'remark' => '',
                'status' => 1,
                'create_time' => '2018-07-28 10:13:30',
                'modify_time' => '2018-07-28 10:13:30',
            ),
            57 => 
            array (
                'id' => 174,
                'merchant_id' => 111,
                'title' => '中洲控股',
                'category_position' => 'tr_0 tr_440000 tr_440300 tr_440305',
                'category_zone' => '广东省 深圳市 南山区',
                'contacts' => '第三方',
                'contacts_phone' => '13411101010',
                'backup_contacts' => '',
                'address' => '广东省深圳市南山区中洲控股中心A座',
                'description' => '',
                'instruction' => '',
                'longitude' => 113.933363,
                'latitude' => 22.517441,
                'remark' => '',
                'status' => 1,
                'create_time' => '2018-08-29 17:21:49',
                'modify_time' => '2018-08-29 17:21:49',
            ),
            58 => 
            array (
                'id' => 178,
                'merchant_id' => 104,
                'title' => 'vgff',
                'category_position' => NULL,
                'category_zone' => '广东省深圳市罗湖区',
                'contacts' => 'hhgg',
                'contacts_phone' => '13266522726',
                'backup_contacts' => '',
                'address' => '罗湖口岸派出所',
                'description' => NULL,
                'instruction' => NULL,
                'longitude' => 114.11686,
                'latitude' => 22.527634,
                'remark' => NULL,
                'status' => 1,
                'create_time' => '2018-09-14 11:35:37',
                'modify_time' => '2018-09-14 11:35:37',
            ),
        ));
        
        
    }
}